### ISSUE TITLE
Implement kXR_query config "sitename" response

### ISSUE THREAD

**Issue by bbockelm** [dCache/dcache#1035]
Currently, dCache implements a handful of responses to the kXR_query config request (such as readv_iov_mx).  See http://xrootd.org/doc/dev4/XRdv300.htm#_Toc372751551 for a reference.

CMS is starting to use the value of the "sitename" response to identify the sites.  This way, when a site causes an error, instead of saying an error occurred at 202.122.33.118, we can say "Beijing-LCG2".

Having the human-readable site name in the exception message allows users and operators to better triage tickets before they get to the experts.

I was thinking about tying this to the value of "info-provider.site-unique-id" if set.  Would there be interest in accepting such a patch?

**Comment by gbehrmann** [comment]
See https://rb.dcache.org/r/8372/
