### ISSUE TITLE
Messages dropped, despite queue containing sufficient capacity

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#1535]
There's a problem that results in the following log messages like:

`24 May 2015 12:35:40 (DCap-gsi-prometheus) [] Dropping message: Task Delivery-of-MessageEvent(source=<CM: S=[>DCap-gsi-prometheus@dCacheDomain];D=[>SRM-prometheus@dCacheDomain];C=dmg.cells.services.login.LoginBrokerInfo;O=<1432463740975:343310>;LO=<1432463740975:343309>>) rejected from java.util.concurrent.ThreadPoolExecutor@74c6add[Running, pool size = 100, active threads = 0, queued tasks = 1, completed tasks = 51660]`

This shows a message is dropped despite the message queue having sufficient capacity to hold it.

This exact message is triggered by commit c8fa0566, but the effect is likely present earlier.

The effect is intermittent, with some messages being delivered without any problem.

Since commit c8fa0566, the dropped messages include those that are the replacement for loginbroker: the LoginBrokerInfo topic.  Currently the `srm` and `info` services are the subscribers of the `LoginBrokerInfo` topic.

The failure to deliver messages means that doors disappear from `srm` and `info` and reappear once a message is successfully.  There are two knock-on effects:
* doors will disappear and reappear from info-provider,
* transfers initiated using SRM will fail if the door(s) to support the transfer appear absent to the srm door.

**Comment by gbehrmann** [comment]
The described symptoms do not appear with any released version. The bug however also affects previous releases and I suggest rephrasing the report such that it describes the observable problems.

**Comment by gbehrmann** [comment]
Fixed. The fix should be backported once 2.13 has been released and field tested.
