### ISSUE TITLE
nfs door does not times out when talking to PoolManager

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#1625]
If requested file is not available, then PoolManager will put request into suspended state. Nevertheless NFS door must wait not longer then 3s and reply 'try later' to the client. This does not happen.

**Comment by gbehrmann** [comment]
You can disable suspending files in pool manager. I think that is what we have done at NDGF.

**Comment by kofemann** [comment]
this is what we have now as well, but this does not solve the bug :)

**Comment by kofemann** [comment]
fixed in https://github.com/dcache/dcache/commit/34af5230ca8c438f3759194e947faa6df9c23f54

**Comment by gbehrmann** [comment]
Oh, so this wasn't with the latest release? Always test with the latest release before submitting a bug report ;-)

**Comment by kofemann** [comment]
yes, we have multiple instances. One of them latest 2.12.11 and other one is older.
