### ISSUE TITLE
rpcbind startup error reported as a bug

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#1626]
we should not report as a BUG  permission issues when portmap failed to bind to port 111.

**Comment by gbehrmann** [comment]
Specifically, this error is erroneous:

    08 Jun 2015 20:06:51 (System) [] Bug detected in dCache; please report this to <support@dcache.org> with the following information.java.lang.RuntimeException: dmg.util.CommandThrowableException: (3) Failed to create bean 'rpcbind' : Permission denied

**Comment by gbehrmann** [comment]
Fixed by 60ddcf9370563c5d0dc01c4bc29002ae05fc235e.
