### ISSUE TITLE
ACLs are not inherited when uploading with SRM

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#1639]
When uploading with the SRM protocol, the file inherits the ACLs from the upload directory (if any) rather than from the parent directory.

The expected result is that a file being uploaded inherits the ACLs from its parent directory, just like it does when any other protocol is used.

**Comment by chrber** [comment]
Are these related http://rt.dcache.org/Ticket/Display.html?id=8767 ? ... except that it is not acls, but unix permissions?

**Comment by gbehrmann** [comment]
Possibly. Not the same issue, but could structurally be similar. Please create a new github issue to track it.
