### ISSUE TITLE
debian packages dependencies - add descriptions for the Recommends/Suggests

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1641]
Hi.

The Debian packages have several dependencies, including some packages which are just recommended/suggested:
 --\ Suggests (1)
    --- ruby  --\ Recommends (2)
    --- libxml2-utils
    --- python-psycopg2
 
IMHO, the package description should contain information for what these are actually used, so that one can decide whether they're needed on the specific system or not.

Cheers,
Chris.

**Comment by gbehrmann** [comment]
The Debian policy agrees: https://www.debian.org/doc/debian-policy/ch-binary.html#s-descriptions, at least for significant dependencies. IMO, we should describe the two recommended dependencies (which also means we need to figure out where that python dependency is :-) ).

**Comment by calestyo** [comment]
;-)

There's a number of prominent packages which do that "description" of recommended/suggested deps and which may be taken as an style example, specifically the devscripts package.
