### ISSUE TITLE
Request: option to limit the number of getfilerequests per user

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#1691]
The SRM has this setting, I assume to limit the number of *running* get requests per user, with a default value of 100:
srm.request.get.max-by-same-user=${srm.request.max-by-same-user}

Wouldn't it be nice to have something similar to limit the *waiting* or *total* get requests per user, so that one uninformed user can't DoS all other users by overloading our SRM with TURLs?

References:
https://ggus.eu/?mode=ticket_info&ticket_id=112413
https://ggus.eu/?mode=ticket_info&ticket_id=114478

Thanks!
Onno

**Comment by gbehrmann** [comment]
Indeed, although the `max-by-same-user` feature is severely broken, see #1533. I just submitted a patch to obsolete `max-by-same-user` and replace it with a more powerful and scalable solution. Next step is to implement a similar feature for RQUEUED.
