### ISSUE TITLE
pinboard date/time

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1772]
Hi.

According to the release notes:

> Timestamps in the in-memory pinboard log used to follow a 12 hour format.
> The format has now been localized, meaning it will follow the conventions of the current local.

However this seems not to be the case (2.13.4).

E.g. I have:
dcache.log.format.pinboard=%d{yyyy-MM-dd HH:mm:ssXXX} [%t] [%X{org.dcache.ndc}] %m

And the pinboard looks like:
[dCache](PoolManager@storagesystem) admin > show pinboard
3:39:49 PM 2015-07-21 15:39:49+02:00 [pool-3-thread-1] [door:xrootd_lcg-lrz-dc62:AAUbYsnAtWA xrootd_lcg-lrz-dc62 PoolMgrSelectReadPool 0000CECB36DC19DA48EC9D4D6E8A5D67DA0D] AskIfAvailable found the object

while the locale is set as follows:
root@lcg-lrz-dcache:~# date +%X
15:57:14
root@lcg-lrz-dcache:~# date +%x
2015-07-21
root@lcg-lrz-dcache:~# date +%c
2015-07-21 15:57:16

So no format would match the actually used "3:39:49 PM".

Moreover, the above shows IMHO quite clearly what I've reported already earlier:
There should be simply no fixed time in the pinboard, i.e. the "3:39:49 PM" should go away and instead a dcache.log.format.pinboard default value should be set that contains the date/time, as I did above.

Cheers,
Chris.

**Comment by gbehrmann** [comment]
So what is your local?

**Comment by gbehrmann** [comment]
See eg http://stackoverflow.com/questions/10707238/locale-getdefault-returns-en-always

**Comment by calestyo** [comment]
My local is a own creation which is basically en_US, except everything non ISO like decimal . and so on, replaced with ISO conforming stuff.

**Comment by gbehrmann** [comment]
I don't think Java will pick that up. Quoting the link above:

> When the JVM starts in a *nix environment, it will do this:
> 
> * Scan the environment for LC_ALL
> * If LC_ALL doesn't exist, scan the environment for LANG
> * If the JVM setting user.language is set, use that in place of the environment variables.
> * If nothing is set, default to en_US (I believe this is the final failure case)

Thus if you have LC_ALL or LANG defined, those are the locals used. How those locals look is defined in the JVM.

I can accept the issue as a feature request to expose the formatting as a logback format string, but as far as I know the current behaviour is as claimed in the release notes.

**Comment by calestyo** [comment]
> How those locals look is defined in the JVM.
Java...o.O

Anyway, yes, the enhancement request here is, that dCache shouldn't assume a default format string (even if taken from some hardcoded java locale) but rather do the whole thing via a logback format string.

And I think there should be a common option a la "dcache.foo.[time|date]-format" or something like that, where all other options (including logback.xml) pull their value from :-)
