### ISSUE TITLE
tab expansion large possibilities offer misses a newline

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1774]
Hey.

When expanding a set that has a lot of members (e.g. hitting tab below after the lcg-lrz-dc, which would be all our pools), then dCache prints the:
"Display all 341 possibilities? (y or n)" offer.

However, there's a newline missing, so the input line is cluttered up:
[dCache] (local) admin > \c lcg-lrz-dcDisplay all 341 possibilities? (y or n)

instead it should be:
[dCache] (local) admin > \c lcg-lrz-dc
Display all 341 possibilities? (y or n)
and editing should continue in the actual line (not below), so the cursor has to be moved back afterwards.

Cheers,
Chris.

**Comment by gbehrmann** [comment]
See jline/jline2#128. Awaiting new release of jline2.

**Comment by calestyo** [comment]
Ah. I see :)

If it goes by me, we could also simply close that bug now.

**Comment by gbehrmann** [comment]
@calestyo, could you check the behaviour with 2.14 and close the bug if it is resolved? Thanks.

**Comment by calestyo** [comment]
works at least since 2.15.3 :)
