### ISSUE TITLE
systemd-ify dCache

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1782]
Hey.

I've brought this up several times before at meetings, and I think it's good to have it in the records and a "bug" where ideas and stuff like that can be collected.

As the title says, there should be support for systemd in dCache (i.e. with respect to service start/stop/etc.).
But such support shouldn't be just a "dumb" conversion of a sysvinit init script to systemd - as you perhaps know systemd provides many features which especially dCache could benefit from.

1) generator units
The idea would be, to have a unit generator, which dynamically creates units based on the respective node's dcache.conf and layout.
So one would have for example a
dcache.service
which is more or less the same what our current init script is - start it and all domains get started, stop it, all domains stopped and so on.

But in addition there would be the dynamically generated units, things like:
dcache@dCacheDomain.service
dcache@namespaceDomain.service
dcache@pool1.service
dcache@pool2.service
and so on, which of course affect just the respective domain.

As you can see this would at least in parts replace the "dcache" script.
It could also speed things up, like parallel start/stop of the domains.

It could also be explored whether this could be used to make sensible dependencies or orderings.

2) watchdog functionality
handle restarting of crashed domains at the systemd level, and not the dCache level

3) maybe even socket based activation

4) Usage of jailing functionality
e.g. restricting domains to only /var and other locations they actually need
or setting resource usage limits

Cheers,
Chris.

**Comment by maswan** [comment]
We found a real issue in production for this. If you have restarted dcache with just the dcache command "dcache restart", systemd will lose track of dcache and think it is dead ("inactive"). This means that the dcache prerm command in the deb package won't actually stop dcache on package upgrade, and same with other commands like orderly shutdown before reboot.

**Comment by gbehrmann** [comment]
Unfortunately I don't see a quick fix for the problems maswan cited. The 'dcache' script would have to detect when the dcache it runs should run under systemd (which isn't just 'if systemd is installed' as you could have e.g. a tarball installation on the same system) - and then it would have to reinvoke itself through systemd and detect that that has happened.

One could imagine separating /usr/bin/dcache from /etc/init.d/dcache such that the former calls the latter rather than the other way around like today. That's still tedious for a dcache install that doesn't run as a system service, but it is probably doable. This would also be a stepping stone for then replacing /etc/init.d/dcache with a systemd generator (or whatever the proper term is).

**Comment by gbehrmann** [comment]
FYI: I wrote a patch for this which is still in review. The patch provides real and full systemd integration in the sense of using systemd generators to dynamically define services based on dCache configuration and also relies on systemd to monitor the process (no more daemon script).

The todo I still have is proper syslog definitions and the stdout from dCache logging goes through systemd and to syslog. I want to configure syslog to split them up into per-domain log files like we had before.

**Comment by calestyo** [comment]
nice :)

**Comment by calestyo** [comment]
What's the status on this? :-)

**Comment by gbehrmann** [comment]
Was about to write that it was sitting in review, but I see Tigran reviewed it. The thing that is missing is that I need to refine the logging a little bit before I am satisfied.

**Comment by calestyo** [comment]
I think we can probably close this... even though it's still quite broken, there is * some * systemd support now,... and tickets are open for most of the issues I've found.
