### ISSUE TITLE
PnfsCancelUpload failing

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#1826]
I see the following errors with current tip of master:

    02 Sep 2015 11:12:03 (PnfsManager) [dh4:482:srm2:prepareToPut:-2147482379:-2147482378 SRM-sisyphus PnfsCancelUpload] Name space transaction failed: Transaction rolled back because it has been marked as rollback-only
    02 Sep 2015 11:12:03 (SRM-sisyphus) [dh4:482:srm2:prepareToPut:-2147482379:-2147482378] Failed to abort put after failure: Name space transaction failed.

**Comment by gbehrmann** [comment]
Okay - let me look at it when I am back tomorrow. Do you have any other pointers as to what triggers this?

**Comment by gbehrmann** [comment]
https://rb.dcache.org/r/8518/
