### ISSUE TITLE
pool manager does not fall back to a link with low priority if needed

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#1849]
On a  system two links with different priorities, if no space available in the high priority
link write will fail, even if more space available in the low priority link.

(this behavior observed in other cases as well)

**Comment by gbehrmann** [comment]
Is space manager involved? Please provide instructions for how to reproduce.

**Comment by kofemann** [comment]
this is only in pool selection, no Space manager involved:

https://github.com/dCache/dcache/blob/master/modules/dcache/src/main/java/diskCacheV111/poolManager/PoolMonitorV5.java#L184

The behaviour was always like that and was desired. Nevertheless, we may re-consider old decisions
