### ISSUE TITLE
migration modules migrates to rdonly pools

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1958]
Hi.

Apparently the migration module writes to rdonly marked pools:
[dCache] (lcg-lrz-dc01_0@pool_lcg-lrz-dc01_0) admin > \s lcg-lrz-dc04_11 migration info 1
Command    : migration move -target=pgroup -concurrency=2 -- atlas_DataDisk
State      : RUNNING
Queued     : 6948
Attempts   : 1448
Targets    : lcg-lrz-dc03_9,lcg-lrz-dc49_5,lcg-lrz-dc41_4,lcg-lrz-dc45_0,lcg-lrz-dc64_2,lcg-lrz-dc64_1,lcg-lrz-dc60_5,lcg-lrz-dc60_4,lcg-lrz-dc64_0,lcg-lrz-dc41_2,lcg-lrz-dc60_2,lcg-lrz-dc41_0,lcg-lrz-dc60_1,lcg-lrz-dc60_0,lcg-lrz-dc49_4,lcg-lrz-dc03_4,lcg-lrz-dc07_0,lcg-lrz-dc49_1,lcg-lrz-dc64_9,lcg-lrz-dc07_1,lcg-lrz-dc64_7,lcg-lrz-dc64_6,lcg-lrz-dc03_0,lcg-lrz-dc49_0,lcg-lrz-dc41_5,lcg-lrz-dc03_1,lcg-lrz-dc45_2,lcg-lrz-dc03_2,lcg-lrz-dc64_4,lcg-lrz-dc01_10,lcg-lrz-dc01_11,lcg-lrz-dc56_0,lcg-lrz-dc52_4,lcg-lrz-dc10_0,lcg-lrz-dc52_3,lcg-lrz-dc33_1,lcg-lrz-dc52_1,lcg-lrz-dc10_1,lcg-lrz-dc52_0,lcg-lrz-dc56_5,lcg-lrz-dc56_4,lcg-lrz-dc14_0,lcg-lrz-dc37_1,lcg-lrz-dc56_3,lcg-lrz-dc52_5,lcg-lrz-dc56_1,lcg-lrz-dc14_1,lcg-lrz-dc42_2,lcg-lrz-dc65_2,lcg-lrz-dc61_6,lcg-lrz-dc65_1,lcg-lrz-dc42_0,lcg-lrz-dc65_0,lcg-lrz-dc62_10,lcg-lrz-dc61_0,lcg-lrz-dc04_2,lcg-lrz-dc65_9,lcg-lrz-dc04_3,lcg-lrz-dc04_4,lcg-lrz-dc08_0,lcg-lrz-dc65_7,lcg-lrz-dc08_1,lcg-lrz-dc46_2,lcg-lrz-dc65_6,lcg-lrz-dc46_3,lcg-lrz-dc46_0,lcg-lrz-dc65_4,lcg-lrz-dc61_7,lcg-lrz-dc03_10,lcg-lrz-dc03_11,lcg-lrz-dc53_2,lcg-lrz-dc53_1,lcg-lrz-dc11_1,lcg-lrz-dc53_0,lcg-lrz-dc11_0,lcg-lrz-dc57_6,lcg-lrz-dc57_5,lcg-lrz-dc38_1,lcg-lrz-dc57_3,lcg-lrz-dc57_2,lcg-lrz-dc53_5,lcg-lrz-dc34_1,lcg-lrz-dc15_1,lcg-lrz-dc57_0,lcg-lrz-dc53_4,lcg-lrz-dc15_0,lcg-lrz-dc02_10,lcg-lrz-dc01_9,lcg-lrz-dc09_1,lcg-lrz-dc02_11,lcg-lrz-dc66_1,lcg-lrz-dc62_4,lcg-lrz-dc66_0,lcg-lrz-dc43_2,lcg-lrz-dc01_0,lcg-lrz-dc43_0,lcg-lrz-dc62_1,lcg-lrz-dc62_0,lcg-lrz-dc66_9,lcg-lrz-dc66_7,lcg-lrz-dc47_3,lcg-lrz-dc66_6,lcg-lrz-dc09_0,lcg-lrz-dc01_1,lcg-lrz-dc66_4,lcg-lrz-dc01_2,lcg-lrz-dc47_2,lcg-lrz-dc62_7,lcg-lrz-dc01_4,lcg-lrz-dc62_6,lcg-lrz-dc66_2,lcg-lrz-dc47_0,lcg-lrz-dc50_5,lcg-lrz-dc50_4,lcg-lrz-dc54_0,lcg-lrz-dc31_0,lcg-lrz-dc12_0,lcg-lrz-dc31_1,lcg-lrz-dc50_2,lcg-lrz-dc50_1,lcg-lrz-dc63_10,lcg-lrz-dc50_0,lcg-lrz-dc58_6,lcg-lrz-dc54_9,lcg-lrz-dc58_5,lcg-lrz-dc16_1,lcg-lrz-dc54_8,lcg-lrz-dc54_7,lcg-lrz-dc58_3,lcg-lrz-dc54_6,lcg-lrz-dc58_1,lcg-lrz-dc54_5,lcg-lrz-dc12_1,lcg-lrz-dc58_0,lcg-lrz-dc16_0,lcg-lrz-dc35_1,lcg-lrz-dc04_12,lcg-lrz-dc02_9,lcg-lrz-dc67_9,lcg-lrz-dc67_0,lcg-lrz-dc40_4,lcg-lrz-dc63_4,lcg-lrz-dc44_0,lcg-lrz-dc40_2,lcg-lrz-dc63_1,lcg-lrz-dc63_0,lcg-lrz-dc40_0,lcg-lrz-dc29_0,lcg-lrz-dc02_4,lcg-lrz-dc67_7,lcg-lrz-dc67_6,lcg-lrz-dc48_2,lcg-lrz-dc29_1,lcg-lrz-dc48_3,lcg-lrz-dc02_0,lcg-lrz-dc67_4,lcg-lrz-dc48_0,lcg-lrz-dc02_1,lcg-lrz-dc63_7,lcg-lrz-dc02_2,lcg-lrz-dc63_6,lcg-lrz-dc44_2,lcg-lrz-dc67_2,lcg-lrz-dc67_1,lcg-lrz-dc59_7,lcg-lrz-dc59_6,lcg-lrz-dc51_5,lcg-lrz-dc32_1,lcg-lrz-dc55_1,lcg-lrz-dc51_4,lcg-lrz-dc55_0,lcg-lrz-dc51_1,lcg-lrz-dc51_0,lcg-lrz-dc55_7,lcg-lrz-dc55_5,lcg-lrz-dc59_1,lcg-lrz-dc13_1,lcg-lrz-dc59_0,lcg-lrz-dc55_4,lcg-lrz-dc13_0,lcg-lrz-dc55_2
Completed  : 1446 files; 752430164402 bytes; 17%
Total      : 4282083893402 bytes
Concurrency: 2
Running tasks:
[1437] 00004C9D74A2ECEC4EA19E204E559846259B: TASK.Copying -> [lcg-lrz-dc04_12@local]
[1447] 000046460C31CF7249BCA0609953D546E142: TASK.Copying -> [lcg-lrz-dc11_0@local]

lcg-lrz-dc04_12  (enabled=true;active=29;rdOnly=true;links=0;pgroups=1;hsm=[];mode=enabled)

Chris.

**Comment by gbehrmann** [comment]
The pool you refer to is not read-only (mode=enabled). Only pool selection in pool manager is switched to only use this pool for reads, but pool manager is only used by doors. This is by design as the configuration controlling end-user transfers should not restrict the admin in moving files internally.

Mark the pool itself read-only if you want to prevent anything from writing (in that case migration module can still write if you use the appropriate force option).

**Comment by calestyo** [comment]
Ah, I see.... perhaps something one can more clearly document in the help psu set pool.

Or at least for me it wasn't obvious that things like the migration module wouldn't use the pool manager for it selections.

:)
Thanks

**Comment by calestyo** [comment]
One more on this:
I've now disabled the pools via pool disable -rdonly...

After once stumbling again over the issue that dcache fails miserable when the localhost name points to the loopback device, as it should be... :-(
... I still noted that the migration jobs were put to sleep every now and then:
```
Command    : migration move -target=pgroup -concurrency=3 -- atlas_ProdDisk
State      : SLEEPING
Queued     : 1284
Attempts   : 75
Targets    : lcg-lrz-dc60_6,lcg-lrz-dc01_9,lcg-lrz-dc61_1,lcg-lrz-dc02_9,lcg-lrz-dc15_9,lcg-lrz-dc49_3,lcg-lrz-dc63_9,lcg-lrz-dc62_9,lcg-lrz-dc65_5,lcg-lrz-dc64_5
Completed  : 65 files; 6092770675 bytes; 3%
Total      : 163902645139 bytes
Concurrency: 3
Running tasks:
[494] 00007EFFC584E32D417D834D967FA76C1530: TASK.Copying -> [lcg-lrz-dc02_9@local]
Most recent errors:
00:56:24 [427] 0000B67C3E8416BD476B9366F0999566D191: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:56:34 [430] 00002ECF7C54E5C54FDA9C0EFD9A25D365DE: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:57:01 [437] 000019C9F8A445914719867DB8959BC24DDA: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:58:07 [458] 00000C0F4E3CBEA849528989FA22EF2FA533: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:58:37 [465] 00001B9AFCE7718644FE8D88E2EAC0AB8F8D: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:58:47 [468] 0000D1BF55F5F80847589775D652EF9876A7: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:58:57 [469] 00003B3761F7CF174E9387B9F3992A7CF486: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:59:17 [480] 0000AACCD9DF67794E939A1C66D898126B97: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
00:59:48 [495] 00007920C09BA0DE4C988B39D580940A67E4: Pool [lcg-lrz-dc49_3@local] failed (Pool is disabled)
```

So when the pool itself is set read only, the migration module still tries it, fails and puts itself a sleep.
Wouldn't it be reasonable that in the rdonly-disabled case, the migration module doesn't sleep (but instead perhaps not retry that pool for the sleep timeout)?


Cheers,
Chris.

**Comment by gbehrmann** [comment]
> After once stumbling again over the issue that dcache fails miserable when the localhost name points to the loopback device, as it should be... :-(

`localhost`always points to the loopback and this is the first time I hear that dCache fails miserably when it does. If instead you mean the fully qualified DNS name of the external interface, then it is the first time I hear that that shouldn't point to the interface it is a name of.

**Comment by gbehrmann** [comment]
Actually, I though migration module would not select a disabled pool, but it seems I am mistaken. That needs to be fixed.

**Comment by calestyo** [comment]
Ah sorry I meant to write "the local<SPACE> hostname"...
Well in the past I've already had some tickets opened that this causes troubles.

For any Debian based distro having the local host name (and the FQDN) pointed to 127.0.1.1 is default since years... and it seems that all others will probably follow sooner or later when libnss-myhostname becomes more and more "default/mandatory" via systemd...
And libnss-myhostname would also resolve to the loopback unless some global address has been specifically configured.

In any case... no software can rely that the hostname (short or fqdn) resolves to the right global address (there may be many)... there is not even a MUST that these names resolve at all.

So as said previously,... dCache shouldn't use that hack to discover its own global address, or at least that's what I guess it's used for :)


And for the migration module case... shall I open a separate issue on that or do you already take care of it?

**Comment by gbehrmann** [comment]
> For any Debian based distro having the local host name (and the FQDN) pointed to 127.0.1.1 is default since years... 

Yes and the current manual clearly states that one should replace that with persistent IP if the host has a persistent IP.

The mere existence of something libnss-hostname demonstrates that the local hostname is intended to be resolvable, as is the fact Debian goes to trouble to bind it by default (to the loopback for the lack of a persistent IP).

libnss-hostname documentation states:

- The local, configured hostname is resolved to all locally configured IP addresses ordered by their scope, or — if none are configured — the IPv4 address 127.0.0.2 (which is on the local loopback) and the IPv6 address ::1 (which is the local host).

I.e. only if there are no configured non-loopback IP addresses does it resolve to a loop back address. Otherwise it resolves to a real address. The docs fail to say how they order by scope, but my guess is they take the IP with the largest scope - i.e. the global IP address rather than the site local one. Thus this NSS plugin does exactly what Java and dCache expects.

Further, the docs says:

> Various software relies on an always-resolvable local hostname. When using dynamic hostnames, this is traditionally achieved by patching /etc/hosts at the same time as changing the hostname. This is problematic since it requires a writable /etc file system and is fragile because the file might be edited by the administrator at the same time. With nss-myhostname enabled, changing /etc/hosts is unnecessary, and on many systems, the file becomes entirely optional.

I guess by "various software" they only mean dCache? It is nice to know they went to all that trouble to make this NSS plugin just to make dCache work :-)

**Comment by calestyo** [comment]
Well as I've said... I rather consider that suggestion historic.
Even if a hostname has a persistent address it may still be configured dynamically (DHCP) in that case it would be useless to set it in /etc/hosts...
Plus, remember the case of multi-homed or NATed noted... if not before, that mode fails at least then.

I haven't said that the hostname shouldn't resolve, just that there is no standard whatsoever that requires this and that properly written software shouldn't depend on it.
And of course things like libnss-myhostname are to workaround the problems introduced by such software while at the same time trying to avoid the shortcomings of /etc/hosts.
But even libnss-myhostname won't be able to solve the general problem that address determination doesn't work reliable that way.

I haven't used it in a while, but last time I did, it always resolved to loopback, even though I had global scoped addresses... maybe they changed that.... or maybe one needs to somehow specially configure it.

Anyway... looking at a number of other well known dameons, ssh, apache, postgresql, just to name some - none of them uses the local hostname to determine it's own global address. And for good reason.

**Comment by calestyo** [comment]
But to come more back to the migration module and rdonly thingy:
I may have noted another issue with that... or maybe I just do it logically wrong:

The idea is, that I set a pool rdonly while I migrate all its data away,... either because I want to re-install it or because I want to phase the hardware out.

What's strange now is, that my cleaner pops out errors like these:
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc54_0: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc52_0: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc54_6: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc49_4: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc53_5: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc49_0: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc52_3: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc54_8: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc52_5: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc54_9: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc52_4: Pool is disabled
2015-11-25 15:10:52+01:00 (cleaner) [] Failed to remove files from lcg-lrz-dc50_5: Pool is disabled

And always on the pools that I've set rdonly... there are only 2500 of these messages so it can't be per file, but maybe it just doesn't log it that often.

Could it be that there's some issue, that either the location info isn't properly cleared while the pool is rdonly and the files migrated away,... or that files that are deleted in chimera (in the meantime) remain on the pool because it's rdonly, then get migrated (because scheduled by the migration module)... and then become dark data?

I wouldn't know how to verify that right now, but the error message sounds like that

**Comment by gbehrmann** [comment]
> Even if a hostname has a persistent address it may still be configured dynamically (DHCP) in that case it would be useless to set it in /etc/hosts...

Sure, and dCache doesn't require you to put it i /etc/hosts - if you use DHCP for your servers, then as long as DNS does its job dCache will be happy.

Obviously the daemons you mention don't use the host name because they don't need to - they are single process systems. dCache consists of many nodes that need to talk to each other.

What is the problem with NAT? I mean, if your machine isn't reachable from the outside why would you need to know that IP?

For multi-homed machines you have to configure the address, so there is no way we can magically guess is.

**Comment by gbehrmann** [comment]
Regarding cleaner, pools don't allow files to be cleaned if disabled. That's why your cleaner complains. Once the pool stops being disabled the cleaner will clean them.

**Comment by gbehrmann** [comment]
This thread is intermixed with the thread in #1966. Those discussions should happen on user-forum where other admins may comment on how to properly configure a server. As it is, this issue is no longer descriptive of a particular problem and will be closed as invalid.

**Comment by calestyo** [comment]
"Regarding cleaner, pools don't allow files to be cleaned if disabled. That's why your cleaner complains. Once the pool stops being disabled the cleaner will clean them."

That's just the problem here... in the way I use -rdonly, i.e. to vacuum the pool, it typically doesn't come back, since we phase it out, for example.

So the two problems I think may exist here:
- if I migrate the files away with the migration module (which isn't apparently affected by -rdonly, at least in terms of moving data away), then the pool is empty, but I'd guess from that error message, that the location info isn't changed or is it?
- And even if the location info is updated properly... what if the pool that I phase out never comes back under a new name... than that entry will remain forever in the cleaner, right?
