### ISSUE TITLE
commands piped into admin shell fail

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1959]
Hi.

When I pipe commands like these into the admin shell:
# cat x 
\s lcg-lrz-dc01_0 migration ls
\s lcg-lrz-dc01_1 migration ls
\s lcg-lrz-dc01_2 migration ls
\s lcg-lrz-dc01_3 migration ls

it fails:

# cat x | ssh -p 59999 localhost
NoRouteToCell[Failed to deliver AuthorizedString message <1447942740734:96972> to [>lcg-lrz-dc01_0@local]: Route for >lcg-lrz-dc01_0@local< not found at >core<]
NoRouteToCell[Failed to deliver AuthorizedString message <1447942740735:96974> to [>lcg-lrz-dc01_1@local]: Route for >lcg-lrz-dc01_1@local< not found at >core<]
NoRouteToCell[Failed to deliver AuthorizedString message <1447942740736:96976> to [>lcg-lrz-dc01_2@local]: Route for >lcg-lrz-dc01_2@local< not found at >core<]
NoRouteToCell[Failed to deliver AuthorizedString message <1447942740738:96978> to [>lcg-lrz-dc01_3@local]: Route for >lcg-lrz-dc01_3@local< not found at >core<]

It works however when I manually past them into the already logged in shell.

Cheers,
Chris.

(2.13.10-1)

**Comment by gbehrmann** [comment]
I cannot reproduce this on our system:

    behrmann@piggy:~$ cat /tmp/foo 
    \s serenity_nsc_liu_se_031 migration ls
    \s serenity_nsc_liu_se_032 migration ls
    \s serenity_nsc_liu_se_033 migration ls
    \s serenity_nsc_liu_se_034 migration ls
    behrmann@piggy:~$ cat /tmp/foo | ssh -p 22224 -l admin localhost
    Pseudo-terminal will not be allocated because stdin is not a terminal.


Any more information you can give me?

**Comment by calestyo** [comment]
I just debugged a bit more, and it's actually a mistake on my side.

x was generated by a pool listing script, which uses colour output and I hadn't made it so, that it doesn't produce that output when it's connected to no terminal.

So it sends all these control codes and obviously dcache fails on them

My fault. Sorry.
