### ISSUE TITLE
xrootd door/mover does not detect filesize mismatch 

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2021]
On upload, xroot client (at lease for ALICE) can provide file size. Nevertheless dCache ignores it and does reflect in billing log if provided value mismatched received file size.

**xrootd request:**

```
open[X,Y,/path/to/file.root,authz=...&oss.asize=834908160]
```

**billing log**

```
2015.12.12 16:45:25 [pool:XXXX:transfer][0000C5F71364988A4E20BD4127484DF9BBAF,822083584]
[/path/to/file;/path/to/file]
X:Y@Z 822083584 369978 true
{Xrootd-2.7:A.B.C.D:abcd}
[door:Xrootd-XXX@xrootdDomain:AAAA-1111] {0:""}
```

**Comment by gbehrmann** [comment]
That attribute is not part of the xrootd spec, but we may add support for it.

**Comment by kofemann** [comment]
Probably we just ignore it, as this is only a hint : http://xrootd.org/doc/prod/ofs_config.htm#_Toc327979849
