### ISSUE TITLE
suggested enhancement: automatically unmount /pnfs when stopping NFS service

### ISSUE THREAD

**Issue by rptaylor** [dCache/dcache#2085]
Hi,

One may easily forget to unmount /pnfs on a dCache server before stopping dCache. This can cause 'df', etc. to hang. Even yum may hang (although this may have only been on an older OS), which makes for a rather inauspicious start to a scheduled downtime.

It would be useful if 'dcache stop' automatically unmounted /pnfs if it existed, before stopping the domains.
I'm just trying to think how to do this .... I can't seem to find any configurable dcache property that defines the path where the NFS filesystem is served from though.

I'm primarily thinking of the case where /pnfs is served from and mounted on the same system.

Do you think it would be useful to have a general solution or should I just write my own script?

Thanks.

**Comment by kofemann** [comment]
Hi Ryan,

I run into this issue my self many times. I think we can't reliably unmount /pnfs, but we can fail shutting down the domain with nfs door if it's mounted on localhost. Nevertheless, some kind of '--force' will be required.

Tigran.

**Comment by rptaylor** [comment]
Hi Tigran,

Sure, that sounds equally good.

Thanks!

**Comment by rptaylor** [comment]
We just improved our documentation to make sure NFS is unmounted first.
