### ISSUE TITLE
pool registers wrong file size if transfer failed

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2109]
The write, the mover must call WriteHandleImpl#commit() and then WriteHandleImpl.close(). If close
is called without commit, then we assume that transfer failed and WriteHandleImpl.fail() is called.
Typically, prost-prcessing procedure registers file size. Nevertheless, in case of failure, the real file size is not propagated to file attributes and value provided by a client will be stored in the name space.
 See https://github.com/dCache/dcache/blob/master/modules/dcache/src/main/java/org/dcache/pool/repository/v5/WriteHandleImpl.java#L373

**Comment by gbehrmann** [comment]
This is not a bug - it is exactly as it is supposed to be. If the client defined what the correct file size is, then that's the file size stored in the name space. If the upload to the pool is incomplete, this doesn't change what the correct size is - it just means the copy in the pool is broken. The same goes for the checksum.

Think of it this way: If the upload succeeded and the file was corrupted on the pool a week later, do you then also want to change the size and checksum in chimera to now match the corrupted copy? No? Then why should we do this when the corruption is applied on upload?

**Comment by kofemann** [comment]
To me it still sounds strange, that file size will be shown a some number even if the client didn't sent a byte. And there is no way to end user discover that.

**Comment by gbehrmann** [comment]
The client sees the file size it set itself. The client can tell the upload failed by looking at the error that was generated as part of the failing upload.

I agree that it is bad that there is no way for clients to subsequently detect that a file is corrupted in dCache, but that's independent of what happens upon upload (given that a file may become corrupted at any point). Paul recently added support in WebDAV to report broken files, but it is inactive as Chimera lacks the ability to represent this information. If Chimera had such a flag, the mover could indicate that the file is broken in dCache.

**Comment by paulmillar** [comment]
FWIW, the WebDAV provides this information in two ways: as a machine-queryable property (via PROPFIND) and visually in the HTML rendering of the directory.

The same information (whether a file is broken) is also available via SRM.
