### ISSUE TITLE
admin shell \s command doesn't seem to preserve empty arguments

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2130]
Hey.

When doing something like:
\c dcap.plain_lcg-lrz-dc55
lb set tags ""
that seems to work.

However,
\s dcap.plain_lcg-lrz-dc55 lb set tags ""
Syntax error: (2) Argument 1 is required
Help : 
lb set tags <tags><...>  # set published tags

fails... it seems as if the empty argument wouldn't be preserved when using \s

Cheers,
Chris

**Comment by gbehrmann** [comment]
Thanks.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/9716/
