### ISSUE TITLE
NFS: ctime gets modified on file read access 

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#2278]
read access to a file results in update to both atime and ctime. Only atime should be updated:

example:

[root@fnisd1 tape]# stat fstab 
  File: `fstab'
  Size: 993             Blocks: 2          IO Block: 1048576 regular file
Device: 15h/21d Inode: 2300        Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 8637/litvinse)   Gid: ( 9767/ UNKNOWN)
Access: 2016-03-15 18:24:55.173000000 -0500
Modify: 2012-09-26 18:39:49.000000000 -0500
Change: 2016-03-15 18:24:55.578000000 -0500

[root@fnisd1 tape]# cp fstab /tmp

[root@fnisd1 tape]# stat fstab 
  File: `fstab'
  Size: 993             Blocks: 2          IO Block: 1048576 regular file
Device: 15h/21d Inode: 2300        Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 8637/litvinse)   Gid: ( 9767/ UNKNOWN)
Access: 2016-03-16 16:52:42.904000000 -0500
Modify: 2012-09-26 18:39:49.000000000 -0500
Change: 2016-03-16 16:52:42.904000000 -0500

Observe ctime changed. 

This leads to tar producing errors (like file being modified).

**Comment by kofemann** [comment]
Ok. The issues is that atime update triggers ctime update as well.

**Comment by kofemann** [comment]
https://rb.dcache.org/r/9139/

looks like there is no clear document which the behavior.
If you google for the topic,  and read some hits, then
most fs have the following semantic of time changes:

      - atime: only when file content is read
      - mtime: only when file content is changed
      - ctime: when file attributes are change or mtime is changed.

**Comment by gbehrmann** [comment]
atime update should update ctime when atime is updated explicitly. I.e. touch -a will update ctime too. It is only when atime gets updated by opening a file that ctime isn't updated. This makes sense because if a user changes an attribute (and atime is an attribute too), then the attribute change time should be updated.

**Comment by gbehrmann** [comment]
To test I used

```
#include <fcntl.h> /* Definition of AT_* constants */
#include <sys/stat.h>
int main(int argc, char *argv[])
{
  struct timespec times[] = { { 0, UTIME_NOW }, { 0, UTIME_OMIT } };
  utimensat(0, argv[1], times, 0);
}
```

to make sure that only access time is modified. Yet ctime gets updated:

```
behrmann@piggy:/tmp$ ls -l foo
-rw-rw-r-- 1 behrmann behrmann 0 Mar 17 08:22 foo
behrmann@piggy:/tmp$ ls -lc foo
-rw-rw-r-- 1 behrmann behrmann 0 Mar 17 08:24 foo
behrmann@piggy:/tmp$ ls -lu foo
-rw-rw-r-- 1 behrmann behrmann 0 Mar 17 08:24 foo
behrmann@piggy:/tmp$ ./test /tmp/foo
behrmann@piggy:/tmp$ ls -l foo
-rw-rw-r-- 1 behrmann behrmann 0 Mar 17 08:22 foo
behrmann@piggy:/tmp$ ls -lu foo
-rw-rw-r-- 1 behrmann behrmann 0 Mar 17 08:37 foo
behrmann@piggy:/tmp$ ls -lc foo
-rw-rw-r-- 1 behrmann behrmann 0 Mar 17 08:37 foo
```

**Comment by DmitryLitvintsev** [comment]
Hi Tigran, 

sorry. I forgot to mention that a utime call on a file that updates atime should still have ctime modified. 
Gerd explicitly asked me to mention it but I somehow blanked that out, apparently I was more pre-occupied with incorrect behavior, rather than correct one. 

So this patch will not be sufficient. We must distinguish atime changed due to read access and explicit atime change by e.g. touch command.
