### ISSUE TITLE
dcache.authn.gsi.crl.cache.lifetime has no UNIT property

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2318]
Apparently dcache.authn.gsi.crl.cache.lifetime has no corresponding .unit property so it's completely unclear what the default of

**Comment by calestyo** [comment]
60k actually means

**Comment by gbehrmann** [comment]
We know - it's because JGlobus doesn't accept units. As you know we are in the process of killing JGlobus and when done, this problem is solved.

**Comment by calestyo** [comment]
Ah, I see.. perhaps one can add a comment which just tells what it is? :)
Unless of course this will go away soon, then it's not worth it.

**Comment by gbehrmann** [comment]
It will go away in 2.16 (it's not used anymore in current master, but I forgot to actually remove the property).

**Comment by gbehrmann** [comment]
Fixed by 28b010baa4fec191db9179e2b0f1f71cebfc2c80.
