### ISSUE TITLE
enhancement: dcache.authn.hostcert.refresh default seems overly low

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2319]
Hey.

The new default for dcache.authn.hostcert.refresh, 60s, seems pretty low.
I understand that it makes sense to have dcache.authn.capath.refresh at a low value (as this is even security relevant, in a away)... but having such low default for the hostcert refresh is probably only reasonable for two cases:
a) the hostcert got compromised and should be exchanged
=> but here, a quick re-load neither helps the clients nor the server (in terms of security) as it's only up to the revocation mechanisms to provide that
b) if people would exchange their expiring host cert very close to the end of the validity time (or only after it has expired)
=> sorry...but there are plenty of mechanisms to have ones certs monitored for soon expiration, and if people don't do their homework it's there problem.

I think an expiration time of something between 30min and 4 hours would be perfectly fine as well.

Chris.

**Comment by gbehrmann** [comment]
What's the problem with having a file stat'ed every 60 seconds? If your host isn't able to keep up with that load, then I think this is going to be the least of your problems.

When sites replace a host cert and then check if the file was reloaded, they don't want to wait an hour to see if the reload worked. Instead, if it doesn't appear to be reloaded quickly, they restart and create a support ticket with us about the reload not working and we have to explain that it actually does, but that somebody demanded we don't stat the hostcert too often.

**Comment by calestyo** [comment]
Well there's no real problem,... of course most hosts are likely able to keep up with that... was just a minor improvement idea.

Have no real strong opinion here,... if you feel it reduces support burden, than leave it as is and just close that ticket. =)
