### ISSUE TITLE
please don't make webdav.authn.basic-for-http* immutable

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2322]
Hi.

Please don't make webdav.authn.basic-for-http* options immutable... it makes it overly complex to change the default behaviour per protocol flavour, e.g. to not allow basic auth for https.

Cheers,
Chris.

**Comment by gbehrmann** [comment]
I disagree. These are internal properties that can be removed without notice. If we keep getting these we will have to drop having immutable properties and instead hard-code these things in Java instead. Makes it more complex for development, but eases the support burden.

Disabling basic auth is as simple as setting webdav.authn.basic to false (you should never use basic auth for plain HTTP anyway as it is insecure). It's only value is over HTTPS.

**Comment by calestyo** [comment]
Then there's no point in allowing basic auth for http anyway... and it can be secure, if e.g. tunneled via IPsec, VPN, or when it's just done over a securely switched network.

OTOH, right now, one can only disable basic auth for https, when one does that also globally for all flavours (i.e. also for http) or per door instance (which then however makes the whole nice automatism of per flavour settings a bit moot).

The only other way would be to introduce site custom per flavour options and set the default of webdav.authn.basic to use these instead of the immutable ones... however,.. the whole site custom options + per protocol-flavour options thingy is basically unusable, at least for any options whose defaults use ($any-of), as dCache doesn't resolve the variable before checking and then complains that an illegal value (i.e. ${site-custom-option}) is used.

**Comment by gbehrmann** [comment]
> OTOH, right now, one can only disable basic auth for https, when one does that also globally for all flavours (i.e. also for http) or per door instance (which then however makes the whole nice automatism of per flavour settings a bit moot).

Doing this per service is exactly how one does this. I do not understand your point. There is no automatism here. There is a default setting which happens to be enabled for https and disabled otherwise. If it makes you happy we can hide this in the Java code instead and remove these immutable properties entirely.

If you want to have global settings that magically apply to all doors that have a particular setting (e.g. all doors that have a particular authentication scheme), then that's not something we support in dCache - you have to implement that yourself.

There is no property for controlling basic auth separately for http and https.

**Comment by calestyo** [comment]
> Doing this per service is exactly how one does this. I do not understand your point. There is no automatism here. There is a default setting which happens to be enabled for https and disabled otherwise.

Having per flavour options, is rather pointless if one ends up again having to set stuff per service instance.
I always thought their whole idea was to allow setting up global per flavour defaults that are automatically picked up by the respective instances (also in order to make configuring the cluster less error prone)... e.g. specifying a default mover queue for webdav.tls and one for webdav.plain.
Or similarly here, disabling basic auth for a specific flavour globally.

> If it makes you happy we can hide this in the Java code instead and remove these immutable properties entirely.

Well I simply see no reason to make something immutable which isn't actually immutable (it's not some hardcoded setting that breaks dCache if it would be changed).
And your argument that this doesn't allow upstream to remove/change options... this happens *soo* often anyway with lots of effort put into all the backwards-compatbility assignments (which clutter up the default quite a lot, and are IMHO anyway rather a waste of the developer's time, cause sooner or later the legacy options go away and sites must do their homework anway)... so I don't quite understand what would be the disadvantage for you developers if this wasn't immutable.

>If you want to have global settings that magically apply to all doors that have a particular setting (e.g. all doors that have a particular authentication scheme), then that's not something we support in dCache - you have to implement that yourself.

Uhm I'm pretty certain, that when the per flavour settings for mover queues, ports, etc. were removed it was advertised that this can be rebuild with custom settings, for those cases where you don't provide per-flavour settings upstreams.
Actually I think you said that, and we had a discussion at some workshop, where I told you that it doesn't effectively work due to the (?any-of) thing described above.

Now we have the situation that the thing with th site custom options doesn't really work for many of these cases and that where per-flavour options actually exist, they cannot be changed.

It's not a big deal for basic auth, because most people will likely just disable it for both flavours (unless they want to leave it on for TLS)... but I just saw no reason of artificially restricting the full range of possibilities... e.g. for setups as mentioned above, where non-TLS traffic is secured somehow else already.

But all other places, where we used to have per-flavour-options, and where this no longer works, it's actually more of an obstacle... :(

**Comment by gbehrmann** [comment]
> Having per flavour options, is rather pointless if one ends up again having to set stuff per service instance.

We do not have per flavour options in dCache.

> I always thought their whole idea was to allow setting up global per flavour defaults that are automatically picked up by the respective instances (also in order to make configuring the cluster less error prone)... e.g. specifying a default mover queue for webdav.tls and one for webdav.plain.

If by "flavour defaults" you mean values you set (as opposed to the actual defaults we set), then that's not something we support. We have never implemented such a feature. There are ways to do this in site local configuration, but no provision in dCache for such a thing. 

All we got is that in some cases we have different default values for some properties based on values of other properties. We implement these with hidden (aka immutable) properties that for all intend and purposes you should consider as not existing. They are internal to dCache.

What you are asking for sound rather like profiles, e.g. to define an http profile and an https profile, each profile setting a whole bunch of different properties and then the ability to select a profile for a particular door instance. That's not something we support, but it's an interesting feature that you are welcome to create a feature request for here on github. In the meantime there are ways to achieve the effect of such profiles in site local configuration. This is entirely unrelated to the use of immutable properties though. Immutable properties are not used for profiles - immutable properties are merely internal properties acting as intermediaries and often used to set defaults that depend on other properties (for various reasons).

> And your argument that this doesn't allow upstream to remove/change options... this happens soo often anyway with lots of effort put into all the backwards-compatbility assignments (which clutter up the default quite a lot, and are IMHO anyway rather a waste of the developer's time, cause sooner or later the legacy options go away and sites must do their homework anway)... so I don't quite understand what would be the disadvantage for you developers if this wasn't immutable.

It is precisely because then we have to provide backwards compatibility for those too and have to document changes to those too. And would have to listen to complaints the day we removed them because we no longer wish to set different defaults depending on other properties (because that's the only reason we got the intermediary properties - the day we decide we no longer want different default values, the property goes away - too bad for anybody who relied on it existing).

And as for wasting developers time, having to argue about immutable properties is a bigger burden at the moment that marking an old name deprecated... Given that you don't fund any developers time, I think you shouldn't be concerned about how we spend our time.


> Uhm I'm pretty certain, that when the per flavour settings for mover queues, ports, etc. were removed it was advertised that this can be rebuild with custom settings, for those cases where you don't provide per-flavour settings upstreams.

Yes, you can create such things in YOUR custom configuration. We don't support profiles like that in dCache out of the box.

 > Now we have the situation that the thing with th site custom options doesn't really work for many of these cases and that where per-flavour options actually exist, they cannot be changed.

For all intend and purposes, they do not exist. When there is an immutable property, then stop reading - its not for you.

If there is something with site custom options that doesn't work, we would like to hear about it.

> but I just saw no reason of artificially restricting the full range of possibilities...

We don't. As you point out yourself, you can create profile like schemas in custom configurations. Nothing we do prevents you from doing that. We just don't want you to rely on our internal properties that we only introduced to have defaults that depend on other properties - properties we would remove the day we decided to alter the defaults.

> But all other places, where we used to have per-flavour-options, and where this no longer works, it's actually more of an obstacle... :(

See, you are already complaining that we removed them. That's exactly why we mark them immutable so that nobody can rely on being able to modify them.

Per service settings are easy enough to do, and if you really have so many instances of a particular type of door that all share settings that you do not want to repeat this per instance, then you can for the time being introduce your own custom profile mechanism the way we have discussed before. As I said above, an actual profile mechanism for services would be quite nice to have and something I would very much welcome. Relying on a few random properties having defaults defined through indirection via some internal properties is an ugly kludge.

**Comment by calestyo** [comment]
>We do not have per flavour options in dCache.

Uhmm?? Just a few that I caught with my regexp:

```
/usr/share/dcache/defaults# grep -Ri "\(\.plain\|\.gsi\|\.kerberos\|\.auth\|[^ ]http\|[^ ]https\)\(=\| \)"
webdav.properties:(immutable)webdav.loginbroker.family-http=http
webdav.properties:(immutable)webdav.loginbroker.family-https=https
webdav.properties:(immutable)webdav.authn.profile-for-http = http
webdav.properties:(immutable)webdav.authn.profile-for-https = https
webdav.properties:(immutable)webdav.authn.basic-for-http = false
webdav.properties:(immutable)webdav.authn.basic-for-https = true
dcap.properties:dcap.cell.name.plain=DCap-${host.name}
dcap.properties:dcap.cell.name.auth=DCap-auth-${host.name}
dcap.properties:dcap.cell.name.gsi=DCap-gsi-${host.name}
dcap.properties:dcap.cell.name.kerberos=DCap-Kerberos-${host.name}
dcap.properties:dcap.net.port.plain=22125
dcap.properties:dcap.net.port.gsi=22128
dcap.properties:dcap.net.port.auth=22129
dcap.properties:dcap.net.port.kerberos=22725
dcap.properties:dcap.loginbroker.family.plain=dcap
dcap.properties:dcap.loginbroker.family.auth=dcap
dcap.properties:dcap.loginbroker.family.gsi=gsidcap
dcap.properties:dcap.loginbroker.family.kerberos=dcap
ftp.properties:ftp.cell.name.plain=FTP-${host.name}
ftp.properties:ftp.cell.name.gsi=GFTP-${host.name}
ftp.properties:ftp.cell.name.kerberos=KFTP-${host.name}
ftp.properties:(one-of?true|false)ftp.authz.readonly.plain=true
ftp.properties:(one-of?true|false)ftp.authz.readonly.gsi=false
ftp.properties:(one-of?true|false)ftp.authz.readonly.kerberos=false
ftp.properties:ftp.net.port.plain = 22126
ftp.properties:ftp.net.port.kerberos = 22127
ftp.properties:ftp.net.port.gsi = 2811
ftp.properties:ftp.loginbroker.family.plain=ftp
ftp.properties:ftp.loginbroker.version.plain=1.0.0
ftp.properties:ftp.loginbroker.family.gsi=gsiftp
ftp.properties:ftp.loginbroker.version.gsi=1.0.0
ftp.properties:ftp.loginbroker.family.kerberos=gkftp
ftp.properties:ftp.loginbroker.version.kerberos=1.0.0
ftp.properties:(immutable)ftp.implementation.plain=org.dcache.ftp.door.WeakFtpInterpreterFactory
ftp.properties:(immutable)ftp.implementation.gsi=org.dcache.ftp.door.GsiFtpInterpreterFactory
ftp.properties:(immutable)ftp.implementation.kerberos=org.dcache.ftp.door.KerberosFtpInterpreterFactory

```

> If by "flavour defaults" you mean values you set (as opposed to the actual defaults we set), then that's not something we support. We have never implemented such a feature. There are ways to do this in site local configuration, but no provision in dCache for such a thing. 

Well than this is new to me =) ... I always thought that was meant to be possible as a replacement for all the per flavour options that were removed, when the different per-flavour services were collapsed into one main service that has a .protocol option to specify which one is meant.
And as I said... it doesn't really work in many cases with the site local config.

> What you are asking for sound rather like profiles, e.g. to define an http profile and an https profile, each profile setting a whole bunch of different properties and then the ability to select a profile for a particular door instance.

Pretty much, yes... I don't think a new framework needs to be introduced for that, though.
As I've said, it would already work pretty much with what we have now, the only obstacle is the problem wit (?any-of) and, when there are already per flavour options, when these are unreadable.
I can show you how I handle such "profiles" locally with a site local config, in case you're interested,... but my solution always require me to override a certain set of options in the defaults file :-/
Perhaps when you see how I do it, it would also get more clear, why I think it's an unnecessary restriction to have that options immutable.
Perhaps a small excerpt of our config, taking what I do with webdav/dcap as an example:

in dcache.conf
```
#*******************************************************************************
#*** webdav                                                                  ***
#*******************************************************************************
#Inter-Process Communication / Message Passing
webdav.cell.name=${lmu.webdav.cell.name.${webdav.authn.protocol}}
lmu.webdav.cell.name.http=webdav.plain_${host.name}
lmu.webdav.cell.name.https=webdav.tls_${host.name}


#General
webdav.authn.protocol=https


#Networking
webdav.net.port=${lmu.webdav.net.port.${webdav.authn.protocol}}
lmu.webdav.net.port.http=80
lmu.webdav.net.port.https=443


#Access Control
webdav.authn.basic=false
webdav.authn.require-client-cert=${lmu.webdav.authn.require-client-cert.${webdav.authn.protocol}}
lmu.webdav.authn.require-client-cert.http=false
lmu.webdav.authn.require-client-cert.https=true
#TODO: “/robots.txt” shouldn’t be writable (and thus not added to the value of the option “lmu.access-control.accepted-paths”), but as of now this can’t be configured for WebDAV doors withou
webdav.authz.allowed-paths=${lmu.access-control.accepted-paths}:${webdav.authz.upload-directory}:/robots.txt
webdav.authz.readonly=${lmu.webdav.authz.readonly.${webdav.authn.protocol}}
lmu.webdav.authz.readonly.http=true
lmu.webdav.authz.readonly.https=false
webdav.authz.anonymous-operations=${lmu.webdav.authz.anonymous-operations.${webdav.authn.protocol}}
lmu.webdav.authz.anonymous-operations.http=READONLY
lmu.webdav.authz.anonymous-operations.https=NONE
webdav.authz.anonymous-listing=${lmu.webdav.authz.anonymous-listing.${webdav.authn.protocol}}
lmu.webdav.authz.anonymous-listing.http=true
lmu.webdav.authz.anonymous-listing.https=false


#Miscellaneous
webdav.enable.owncloud=false


#Movers
webdav.mover.queue=${lmu.webdav.mover.queue.${webdav.authn.protocol}}
lmu.webdav.mover.queue.http=webdav.plain
lmu.webdav.mover.queue.https=webdav.tls



#*******************************************************************************
#*** dcap                                                                    ***
#*******************************************************************************
#Inter-Process Communication / Message Passing
dcap.cell.name.plain=dcap.plain_${host.name}
dcap.cell.name.auth=dcap.auth_${host.name}
dcap.cell.name.kerberos=dcap.kerberos_${host.name}
dcap.cell.name.gsi=dcap.gsi_${host.name}


#General
dcap.authn.protocol=gsi


#Access Control
dcap.authz.readonly=${lmu.dcap.authz.readonly.${dcap.authn.protocol}}
lmu.dcap.authz.readonly.plain=true
lmu.dcap.authz.readonly.auth=true
lmu.dcap.authz.readonly.kerberos=false
lmu.dcap.authz.readonly.gsi=false
dcap.authz.anonymous-operations=${lmu.dcap.authz.anonymous-operations.${dcap.authn.protocol}}
lmu.dcap.authz.anonymous-operations.plain=READONLY
lmu.dcap.authz.anonymous-operations.auth=NONE
lmu.dcap.authz.anonymous-operations.kerberos=NONE
lmu.dcap.authz.anonymous-operations.gsi=NONE

dcap.authn.passwd=${dcache.paths.etc}/access-control/dcap.auth-passwd


#Movers
dcap.mover.queue=${lmu.dcap.mover.queue.${dcap.authn.protocol}}
lmu.dcap.mover.queue.plain=dcap.plain
lmu.dcap.mover.queue.auth=dcap
lmu.dcap.mover.queue.kerberos=dcap
lmu.dcap.mover.queue.gsi=dcap.gsi

```
So I basically say: per default webdav will yield in a https door... and for both http and https I set different options for auth/movers/etc., that will be picked up automatically by an instance of the door in the layouts, just by setting it's protocol flavour.
For some of the options I use existing per-flavour options (e.g. with dcap I use dcap.cell.name.* to set the name as I like it).
For those where there are no upstream per-flavour options (that I can set or none at all), I used sit custom option I've placed in the lmu. namespace.
The according properties files is that:

```

#Note:
#This is a dCache “.properties”-file, containing locally defined options (for
#example common canonical options for other options or protocol-flavour-specific
#versions of other options).
#It’s main purpose is to document these options, set annotations and basic safe
#defaults for them as well as to make them known to the dCache configuration
#system, so that they are properly recognised (for example by
#“dcache check-config”).




#*******************************************************************************
#*** Addresses                                                               ***
#*******************************************************************************
#This is the address of the host running the main instance of the “httpd”
#service.
#
#It may be used for options that specify the address (for example a domain
#name or IP address literal) of a host that runs an instance of the service
#“httpd”.
#
#The default value is “example.invalid”, trying to prevent any usage by
#specifying a (hopefully) non-existent address.
lmu.addresses.host.httpd=example.invalid




#*******************************************************************************
#*** Access Control                                                          ***
#*******************************************************************************
#This is a “:” separated list of pathnames for which both reading and writing
#should be in principle (that is when all other access control systems permit)
#accepted.
#
#It may be used for options that control either only the accepted read paths,
#only the accepted write paths or both the accepted read and write paths.
#Therefore it MUST NOT contain more than the intersection of accepted read and
#accepted write paths.
#Beware and see also the other options from the
#“lmu.access-control.accepted-paths[.*]”-family and how they are used in the
#local dCache configuration.
#
#The default value is “/nonexistent”, trying to prevent any access by
#specifying a (hopefully) non-existent pathname.
lmu.access-control.accepted-paths=/nonexistent


#This is a “:” separated list of pathnames for which reading should be in
#principle (that is when all other access control systems permit) accepted.
#
#It may be used for options that control ONLY the accepted read paths.
#It MUST NOT be used for options that control either only the accepted write
#paths or both the accepted read and write paths.
#Beware and see also the other options from the
#“lmu.access-control.accepted-paths[.*]”-family and how they are used in the
#local dCache configuration.
#
#The default value is that of the option “lmu.access-control.accepted-paths”,
#which tries to prevent any access.
lmu.access-control.accepted-paths.read=${lmu.access-control.accepted-paths}


#This is a “:” separated list of pathnames for which writing should be in
#principle (that is when all other access control systems permit) accepted.
#
#It may be used for options that control ONLY the accepted write paths.
#It MUST NOT be used for options that control either only the accepted read
#paths or both the accepted read and write paths.
#Beware and see also the other options from the
#“lmu.access-control.accepted-paths[.*]”-family and how they are used in the
#local dCache configuration.
#
#The default value is that of the option “lmu.access-control.accepted-paths”,
#which tries to prevent any access.
lmu.access-control.accepted-paths.write=${lmu.access-control.accepted-paths}




#*******************************************************************************
#*** Miscellaneous                                                           ***
#*******************************************************************************
#This is a format string for a date.
#
#It may be used for options that interpret date/time format strings following
#the syntax used with the class “SimpleDateFormat” from the “Java Text” package.
#Beware and see also the options “lmu.miscellaneous.time-format” and
#“lmu.miscellaneous.date-time-format” and how they and this option are used in
#the local dCache configuration. Using characters that may be used as escape
#symbols within the values of other options (especially “$” and “\”) can lead to
#errors and should be avoided.
#
#The default value is a format for a date following ISO 8601.
lmu.miscellaneous.date-format=yyyy-MM-dd


#This is a format string for a time.
#
#It may be used for options that interpret date/time format strings following
#the syntax used with the class “SimpleDateFormat” from the “Java Text” package.
#Beware and see also the options “lmu.miscellaneous.date-format” and
#“lmu.miscellaneous.date-time-format” and how they and this option are used in
#the local dCache configuration. Using characters that may be used as escape
#symbols within the values of other options (especially “$” and “\”) can lead to
#errors and should be avoided.
#
#The default value is a format for a time following ISO 8601.
lmu.miscellaneous.time-format=HH:mm:ssXXX


#This is a format string for both date and time.
#
#It may be used for options that interpret date/time format strings following
#the syntax used with the class “SimpleDateFormat” from the “Java Text” package.
#Beware and see also the options “lmu.miscellaneous.date-format” and
#“lmu.miscellaneous.time-format” and how they and this option are used in the
#local dCache configuration. Using characters that may be used as escape symbols
#within the values of other options (especially “$” and “\”) can lead to errors
#and should be avoided.
#
#The default value is a format for both date and time following ISO 8601.
lmu.miscellaneous.date-time-format=${lmu.miscellaneous.date-format}'T'${lmu.miscellaneous.time-format}




#*******************************************************************************
#*** Protocol-Flavour-Specific Versions Of Non-Local Options                 ***
#*******************************************************************************
#These are protocol-flavour-specific versions of non-local options (these are
#dCache’s native options or such from external plug-ins, et cetera), each of the
#form “lmu.<option>.<protocol-flavour>”.
#
#
#They are used in a tricky manner, so that the corresponding option is selected
#based on the chosen protocol-flavour, for example:
# Given these settings:
#  service.option=${lmu.service.option.${service.protocol-flavour}}
#  lmu.service.option.flavour-a=value-a
#  lmu.service.option.flavour-b=value-b
# 
# When “flavour-a” is chosen via the following setting:
#  (one-of?flavour-a|flavour-b)service.protocol-flavour=flavour-a
# then the effective value of the option “service.option” will be “value-a”.
# However, when “flavour-b” is chosen via the following setting:
#  (one-of?flavour-a|flavour-b)service.protocol-flavour=flavour-a
# then the effective value of the option “service.option” will be “value-b”.
#
#
#The semantics and possible values for each option are defined and described by
#the respectively corresponding option of the name “<option>”.
#
#The default value for each option has been chosen to be appropriate and
#(hopefully) secure.
lmu.webdav.cell.name.http=WebDAV-${host.name}
lmu.webdav.cell.name.https=WebDAV-${host.name}
lmu.webdav.net.port.http=80
lmu.webdav.net.port.https=443
(one-of?true|false)lmu.webdav.authn.require-client-cert.http=true
(one-of?true|false)lmu.webdav.authn.require-client-cert.https=true
(one-of?true|false)lmu.webdav.authz.readonly.http=true
(one-of?true|false)lmu.webdav.authz.readonly.https=true
(one-of?NONE|READONLY|FULL)lmu.webdav.authz.anonymous-operations.http=NONE
(one-of?NONE|READONLY|FULL)lmu.webdav.authz.anonymous-operations.https=NONE
(one-of?true|false)lmu.webdav.authz.anonymous-listing.http=false
(one-of?true|false)lmu.webdav.authz.anonymous-listing.https=false
lmu.webdav.mover.queue.http=
lmu.webdav.mover.queue.https=
lmu.ftp.mover.queue.plain=
lmu.ftp.mover.queue.kerberos=
lmu.ftp.mover.queue.gsi=
(one-of?true|false)lmu.dcap.authz.readonly.plain=true
(one-of?true|false)lmu.dcap.authz.readonly.auth=true
(one-of?true|false)lmu.dcap.authz.readonly.kerberos=true
(one-of?true|false)lmu.dcap.authz.readonly.gsi=true
(one-of?NONE|READONLY|FULL)lmu.dcap.authz.anonymous-operations.plain=NONE
(one-of?NONE|READONLY|FULL)lmu.dcap.authz.anonymous-operations.auth=NONE
(one-of?NONE|READONLY|FULL)lmu.dcap.authz.anonymous-operations.kerberos=NONE
(one-of?NONE|READONLY|FULL)lmu.dcap.authz.anonymous-operations.gsi=NONE
lmu.dcap.mover.queue.plain=
lmu.dcap.mover.queue.auth=
lmu.dcap.mover.queue.kerberos=
lmu.dcap.mover.queue.gsi=
```



> It is precisely because then we have to provide backwards compatibility for those too and have to document changes to those too. And would have to listen to complaints the day we removed them because we no longer wish to set different defaults depending on other properties (because that's the only reason we got the intermediary properties - the day we decide we no longer want different default values, the property goes away - too bad for anybody who relied on it existing).

Don't get me wrong... apart from that it clutters up the defaults files, I don't have any strong opinion against it.... I just think that people will have to do it sooner or later... and when they didn't complain the first major release where you introduced the new options, they will complain 2 major releases later when you mark them forbidden.
Actually I thought to remember that this very question was brought up in the fish bowl in Amsterdam (or was it even Zeuthen earlier) and then either you or Paul said that you just do it as a convenience because sites complain otherwise... and when the people form the attending sites were then asked who needs that... the only one who answered was Xavier, and he said he wouldn't need it.

But as I said... that's up to you guys =)


>Yes, you can create such things in YOUR custom configuration. We don't support profiles like that in dCache out of the box.

As I've mentioned several times, that doesn't really work at least not for any options that use .. oh it's "(one-of?)"...
Consider e.g.

`dcap.authz.anonymous-operations=${lmu.dcap.authz.anonymous-operations.${dcap.authn.protocol}}`

dCache won't start with that, because ${lmu.dcap.authz.anonymous-operations.${dcap.authn.protocol}} isn't a legal value as per the default file... it doesn't resolve the var before it checks.

Apart from that, I fully agree, these profiles or per-flavour options as I called them, SHOULD be defined only on a local basis... BUT... if there is already one like webdav.authn.basic-for-http* which does the very same job as one that I'd define manually, e.g. lmu.webdav.authn.basic.http/s it seems a bit tedious not being able to use that directly.

That's the whole background behind this ticket... it's not a "I know it better and you do wrong"... it's not a "I want to waste your time",... neither is it a "this is a showstopper"...
It's just a there is this nice usecase with the "profiles" as you called it... and for that it seems just an obstacle to have it immutable.

>If there is something with site custom options that doesn't work, we would like to hear about it.

I'm pretty sure btw. I had the problem with the syntax checking reported in detail in a ticket... seems you and me discussed that whole thing about "profiles" and why it doesn't work in https://github.com/dCache/dcache/pull/624

> See, you are already complaining that we removed them. That's exactly why we mark them immutable so that nobody can rely on being able to modify them.
No I'm not complaining about the removal itself... it was a good decision to get rid of all the dcapPort gsiDcapPort and all that stuff and it made the whole system a lot cleaner.
What I "complain" about is that one cannot easily get back the previous behaviour.


> And as for wasting developers time, having to argue about immutable properties is a bigger burden at the moment that marking an old name deprecated... Given that you don't fund any developers time, I think you shouldn't be concerned about how we spend our time.

Speaking of which,.. it's probably best to end that discussion now at this point, the ticket is closed already and as I've said, I just reported it because I felt it was an improvement, not because it would be a showstopper.

**Comment by gbehrmann** [comment]
> Uhmm?? Just a few that I caught with my regexp:

Thanks. I see there are several bugs here as these should all have been marked immutable. I guess the reason they were not was because some of these were individually configurable in the old config system and we wanted to make the transition easier. Since you don't care much about making the transition to new versions easier, we may just as well mark them immutable now.

> Well than this is new to me =) ... I always thought that was meant to be possible as a replacement for all the per flavour options that were removed, when the different per-flavour services were collapsed into one main service that has a .protocol option to specify which one is meant.

No, the main purpose is to have dependent defaults and immutable properties are immutable exactly because they are not intended for you.

> Pretty much, yes... I don't think a new framework needs to be introduced for that, though.
As I've said, it would already work pretty much with what we have now.

No it doesn't. It works in some very extremely limited cases in which you want different settings based on authentication protocol. How can I create a generic definition for an Alice door vs an Atlas door? How can I create a generic definition for LAN doors vs WAN doors? Those are use cases we have at NDGF, and simply marking a few properties as mutable does not in any way resolve those use cases. We can do this in site local config by creating local indirections, but so can you for other "profiles".

> The according properties files is that:

Yeah, it does look like you are making life quite difficult for yourself by insisting on not setting these properties in the layout file. But it's pretty cool you can do stuff like this.


> dCache won't start with that, because ${lmu.dcap.authz.anonymous-operations.${dcap.authn.protocol}} isn't a legal value as per the default file... it doesn't resolve the var before it checks.

Yeah, that's a known bug and there is a patch in review board for a long time to resolve it: https://rb.dcache.org/r/7856/ We just need Paul to have time to actually finish it.

> It's just a there is this nice usecase with the "profiles" as you called it... and for that it seems just an obstacle to have it immutable.

Yes, and I like the idea of profiles, but they should be actual profiles, not something coupled to just a single property (authentication scheme). Linking it to authentication scheme may work for you if you only support a single VO, but for others that's not enough. If we support this we should do it right and not some half solution piggybacking on something done for other reasons. It's too late for 2.16 now, but I would love this for a later release.
