### ISSUE TITLE
chimera.db.password.file does not work for chimera in 2.10

### ISSUE THREAD

**Issue by IATkachenko** [dCache/dcache#2352]
dCache is ignoring chimera.db.password.file property in configuration file for namespace domain.
We should use chimera.db.password for authorization in database.

dCache version is 2.10.41-2

**Comment by jstarek** [comment]
I came across this ticket while reviewing older entries. Is the issue solved by pull request #2528  listed above? If so, can we close this ticket?

**Comment by gbehrmann** [comment]
Yes, I guess github doesn't auto close the ticket when the commit is merged as a PR or if it only goes to a branch.
