### ISSUE TITLE
srm permanently locks up during startup in the aftermath of bug #2353

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2354]
Hey.

As discussed/solved with Gerd, after the issue in #2353 hit us, our SRM wasn't starting up anymore due to some transfers being in a state that prevent that and which needed to be manually resolved by changing their state in the DB.

This should get properly fixed that dCache can handle this automatically again.

Chris.

**Comment by gbehrmann** [comment]
https://rb.dcache.org/r/9198/

**Comment by calestyo** [comment]
That took really long to fix ;-)

Thanks!
