### ISSUE TITLE
ugly formattet commit messages

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2364]
Not sure if this hasn't been noticed so far, but a rising number of git commit messages have some very bad formatting... either they're extremely indented, or the summary lines goes over multiple lines, "breaking" many 3rd party git tools.

e.g. 69def457b3181ec1c20cd8e3adc2594c372b5444 or 9417720fdef9aa19e257e95271295d61e2b40adc

**Comment by gbehrmann** [comment]
@DmitryLitvintsev could you please stop using squash merges and instead cherry pick from your development branches? I believe the squash merges are the primary source for the bad indentation.

**Comment by DmitryLitvintsev** [comment]
Ok
