### ISSUE TITLE
HTTP basic auth broken in 2.15

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#2398]
A WebDAV door before 2.15 would trigger the browser login prompt when basic authentication is enabled and access to a resource is rejected. In 2.15 this now simply results in the browsers authorization denied default page. A related regression is that before 2.15 a nicely rendered HTML page with the authorization error was shown - now it's the browsers default error.

Steps to reproduce:

Configure a dCache door webdav door with:

    webdav.authn.basic=true
    webdav.authn.protocol=https
    webdav.authn.accept-client-cert = false

In 2.14 this triggers a login prompt in the browser when navigating to the door. In 2.15 one gets an error message.

The regression is introduced in commit a8edc2642417aee14ae7944956d5fdedc2cfee1b.

**Comment by anupash** [comment]
I can't reproduce it. 

1. I checkout 2.15 fresh, completely deleted the system-test target folder, ran maven clean and then compiled it. 
2. I changed the cache layouts file to

[dCacheDomain/webdav]
webdav.cell.name=WebDAV-${host.name}
webdav.net.port=2880
webdav.authz.anonymous-operations=READONLY
webdav.authn.basic=true
webdav.authn.protocol=http

[dCacheDomain/webdav]
webdav.cell.name=WebDAV-S-${host.name}
webdav.net.port=2881
webdav.authz.anonymous-operations=READONLY
webdav.authn.protocol=https
webdav.authn.basic=true
webdav.authn.accept-client-cert=false
webdav.redirect.on-read=false
webdav.redirect.on-write=false
webdav.net.internal=127.0.0.1

I checked that the basic authentication is working fine with both http and https. 

Also tried with curl

curl --capath /home/username/.globus/certificates -u username:password -L -T /tmp/random.img  https://localhost:2881/private/random.img -vvv
