### ISSUE TITLE
billing database in 2.16 is not downgradable

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#2454]
Commit a7730edd2c55fe4aac231c26941238b9ef7975d9 lacks a rollback statement in change 8. This prevents downgrade to an earlier version.

**Comment by DmitryLitvintsev** [comment]
How do fix that - I modify "8" w/ empty rollbacks or create "8.1" which is equivalent of "8" with empty rollback statement?

Also, could you verify that the patch 

https://rb.dcache.org/r/9313/

has correct rollback handling.

**Comment by gbehrmann** [comment]
If the new triggers work with the old schema, then an empty rollback is an option. Otherwise the rollback has to restore the old triggers.

Yes, replacing the changeset with an 8.1 changeset is the way to go.

**Comment by gbehrmann** [comment]
I commented on patch 9313.

**Comment by DmitryLitvintsev** [comment]
https://rb.dcache.org/r/9332/diff/1#index_header

**Comment by DmitryLitvintsev** [comment]
https://rb.dcache.org/r/9332
