### ISSUE TITLE
billing lacks fallback for non-postgresql databases

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#2500]
Observed on master/2.16:

    01 jun. 2016 10:31:05 (billing) [] Unexpected error occurred in scheduled task.javax.jdo.JDODataStoreException: Error executing SQL query "SELECT f_billing_daily_summary()".

**Comment by DmitryLitvintsev** [comment]
Ouch.... I can't get this right can I?
Working on fixing it.

**Comment by DmitryLitvintsev** [comment]
https://rb.dcache.org/r/9367
