### ISSUE TITLE
queue activate commands renamed to queue setIncluded

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#2518]
The two `queue activate` commands in the pool got renamed to `queue setIncluded` in 69cc5b9224282eabadc842fe5c930049373770d6.

**Comment by alrossi** [comment]
Oh crap.  I'm still not comfortable with the IntelliJ refactoring.  Eclipse was so much more sane.  This was obviously because I had applied a renaming to the resilience command 'pool activate' to pool setIncluded', and it did in on the pool too.   I'll take care of this in a bit.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/9384/
