### ISSUE TITLE
download files from frontend service needs to respect webdav authentication setting

### ISSUE THREAD

**Issue by ahaupt** [dCache/dcache#2519]
When downloading a file via the frontend service (dCache 2.16.0), the redirect to WebDAV implicitly uses the http protocol.

If WebDAV is configured to be secured via the dcache.conf setting "webdav.authn.protocol" this attempt fails for obvious reasons. The client will receive a "connection reset" error message in this case.

**Comment by femiadeyemi** [comment]
This issue is resolved. Thanks.
