### ISSUE TITLE
DSA type SSH keys shouldn't be used

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2576]
Hey.

IMHO, DSA SSH keys shouldn't be used/accepted for security reasons. Their use is generally discouraged.

Instead it would be nice to have curve25519 support…

Similarly, though I haven't checked this in the code:
Common vulnerabilities are acceptance of either too short keys,… or DH groups.
ECRYPT II recommendations (https://www.keylength.com/en/3/) severe as a reasonable guideline.

Cheers,
Chris.

**Comment by calestyo** [comment]
I think it wasn't a problem with DSA per se (i.e. the algorithm),… while that has some design deficiencies, RSA is said to have such as well…

The main reason for e.g. OpenSSH deprecating them, was probably the restriction to 1024bit as per the protocol…

**Comment by gbehrmann** [comment]
Right - and there was a discussion on openstack about that and that this restriction only existed in an initial version of the standard. It was subsequently removed - or so it was said. I haven't verified myself.

2.17 already removed the DSA keys from dCache (as you probably noticed from the commits last week). I don't see a reason why we should add extra code to prevent the use of a DSA key though.

**Comment by calestyo** [comment]
Mhh… I do remember that this was the case for e.g. OpenPGP keys, where DSA2 was introduced,... but I don't think to remember, that this was ever standardised for SSH.
The way to go is anyway curve25519.

Well past has always shown, that just no doing things per default, still leave open quite some holes (e.g. ssh1).

**Comment by jstarek** [comment]
I'm just revisiting long-standing open tickets. This looks like it's been resolved since 2.17, and I'll close it for now. Feel free to re-open.
