### ISSUE TITLE
admin door not starting

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#2577]
21 Jun 2016 09:49:08 (System) [] URL [file:/usr/share/dcache/services/admin.batch]: line 33: Command failed ((3) EL1005E:(pos 0): Type cannot be found 'org.dcache.commons.util.Strings'; caused by: EL1005E:(pos 0): Type cannot be found 'org.dcache.commons.util.Strings')

must be from Spring.  Checking ... will post a patch

@2ef6d44

**Comment by alrossi** [comment]
see https://rb.dcache.org/r/9448/

**Comment by kofemann** [comment]
thanks
