### ISSUE TITLE
chimera-cleaner loads full content of trash table into memory 

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2645]
To get list of files and locations to be removed, chimera cleaner selects and stores in an internal list the full content of a trash table for a particular location type. This list can exceed the available memory and kill the corresponding domain with OOM.

**Comment by lemora** [comment]
Fixed by https://github.com/dCache/dcache/commit/136f3b29d17c91e5176a7d1958a5e91225bcf2ba which was tracked in and closed issue #2529 and will be included in 7.0.

**Comment by kofemann** [comment]
Unfortunately, I have to re-open this issue as we observe the same behavior with DiskCleaner. though it tries to iterate with fixes chunks, the postgres driver tries to load all entries at once.

**Comment by lemora** [comment]
https://rb.dcache.org/r/12757/
