### ISSUE TITLE
release notes incomplete

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2709]
Hey.

All the release notes of the more recent versions seem to have lost the entries for some minor versions, e.g.:
2.15.13
2.14.26
2.13.37

Cheers.

**Comment by calestyo** [comment]
and 2.16.7

**Comment by jstarek** [comment]
Thanks for pointing this out. I had not commited some necessary files. The changelogs are now online, showing the (single and small) change to those releases.

**Comment by mksahakyan** [comment]
I uploaded file on Desy cloud.
