### ISSUE TITLE
dcache-view: Error on upload

### ISSUE THREAD

**Issue by anupash** [dCache/dcache#3011]
Steps to reproduce the error

1. Navigate to [Prometheus](https://prometheus.desy.de:3880)
2. Login and browse to your home directory (e.g. /Users/anupam)
3. Upload a file
4. Delete the uploaded file
5. Upload the same or another file (fails to upload without giving any error)

![screen shot 2017-01-24 at 4 33 46 pm](https://cloud.githubusercontent.com/assets/662685/22289668/19e21bd4-e2fd-11e6-8455-f336be45bcc9.png)

Logout and Login, and it works again.

**Comment by jstarek** [comment]
Is this still an issue or can we close the ticket?
