### ISSUE TITLE
A non-repeatable failure of RemoteTransferManager

### ISSUE THREAD

**Issue by jstarek** [dCache/dcache#3012]
During the building of 2.16.24, RemoteTransferManager died and caused problems with SRM file deletion. Details in the console output of build [396](https://ci.dcache.org/view/dCache%202.16/job/2.16%20post%20testing/396/), for context see the dCacheDomain.log file.

**Comment by paulmillar** [comment]
Problem triggered by S2 Basic test-suite's StatusOfCopyRequest test:

https://ci.dcache.org/view/Test%20Suite/job/Parallel-S2/22557/Instance=3,S2%20machines=s2%20&&%20!user-root/testReport/%28root%29/basic/SHA2_StatusOfCopyRequest/

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10022/
