### ISSUE TITLE
improvie file permissions

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3298]
Hey.

I think the file permission bits for several directories in dCache should be improved (i.e. set in the package already *and* updated for existing installations, not sure if RPM would do that... DEB does).

Basically everything below /var/lib/dcache, should probably not be world-readable, and if it's just for privacy reasons (billing e.g. contains likely user related data).

Probably /etc/dcache shouldn't be world-readable either, as it may contains passphrases?

Cheers,
Chris

**Comment by paulmillar** [comment]
One issue here is that `/var/lib/dcache/config` needs to be readable by any dCache script; for example, `dcache-info-provider` is run by BDII, as with uid ldap and gid ldap.  This means this directory must be world-readable.

Likewise the `/var/lib/dcache/star` directory needs to be writeable by the dcache-star script.

That said, I believe the other directories can (and should) have tighter permissions, with billing being an obvious choice.

You're correct that /etc/dcache can, in theory, contain secrets.  However, the policy there is that the file containing those secrets should be protected.  This is consistent with X.509 credentials: `/etc/grid-security` is world-readable but the file `/etc/grid-security/hostkey.pem` has restricted permissions.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10317/

**Comment by calestyo** [comment]
Don't we have cases where dcache.conf or layouts could contain any secrets or at least information that shouldn't necessarily be shared?

As for dcache-info-provider and perhaps also dcache-star, a better approach would be anyway to not have them run as root, but their own user (created by the package), and perhaps simply giving that user group membership to dcache?


Anyway your patch seems an improvement already. Any reason why doing 0700 on so many? I mean dcache group should be safe, shouldn't it? :)

**Comment by calestyo** [comment]
btw: I'd bet many admins just miss the point of some files being at least sensitive wrt privacy, just noted that even I myself, while having a:
```
# tree /etc/dcache/access-control//etc/dcache/access-control/
├── authzdb
├── gplazma.conf -> ../gplazma.conf
├── spacemanager-linkgroup-authorization
└── vorolemap
```
where everything access control related, packed together, used world-readable permissions ^^

Perhaps it would make sense to ship something like these as skeleton files, with proper permissions already set up.
Additionally this could have the benefit to establish standard locations for files that many dCache sites will have (like the gplazma plugin configs above or spacemanager-linkgroup-authorization).

Similarly I have a:```

/etc/dcache/pki# l
lrwxrwxrwx 1 root root     31 Feb 19  2015 client.crt.d -> /etc/grid-security/certificates
lrwxrwxrwx 1 root root     26 Feb 19  2015 client.voms.d -> /etc/grid-security/vomsdir
lrwxrwxrwx 1 root root     31 Feb 19  2015 server.crt -> /etc/grid-security/hostcert.pem
lrwxrwxrwx 1 root root     30 Feb 19  2015 server.key -> /etc/grid-security/hostkey.pem
```
which "contains" all the dCache related PKI files, i.e. it's cert/key + it's trusted CAs/VOMSes.

**Comment by paulmillar** [comment]
Yes, potentially there are secrets in dcache.conf and layout files; however (repeating what I said) the correct behaviour is to have a separate file that is protected.

For dcache-info-provider, feel free to open a ticket against BDII to have them change their info-provider python script run as group-member of group 'dcache'.

For 700, the idea is that 'dcache' user is used by only the dCache server.  Other scripts could run as a different user that is a member of 'dcache' group, so those directories are not 700 but something more relaxed.  Only when supporting scripts that we (dCache.org) don't have direct control over (so run as potentially an arbitrary user), are the directories world-readable.
