### ISSUE TITLE
improve documentation on the new class of config options (.subscrube/.consume/.cell.name/.cell.export/etc.)

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3299]
Hey.

With the "new" dCache version (2.16), a whole class of similar options came along...
cell.service/.subscrube/.consume/.cell.name/.cell.export and so on... and also some global dcache. options that have to do with them, e.g. dcache.service. and dcache.queue. ...

I feel a bit, that the current documentation lacks some central points:
a) There is no where a description of the big picture... i.e. which option one should change for which purpose (e.g. something like "change the global option, if you just want to rename the service to ChimeraManager"... but "you'd change the per service option for this and that purpose".

b) Especially all the .consume and .subscribe messages.. their whole documentation is just what subscribing and consuming means... not which effect it has for this particular service and why one would want to change it.
It's a bit as if one would have a property that takes an integer and describes what numbers are and which valid values they can have... instead of how these numbers affect the system.

c) The replicable option already mentions that the config must by synced, but they should IMO also tell  what that actually is.. e.g. gplazma's replicable option could say, that gplazma.conf must be synced, as well as all the configs and data sources (e.g. ldap server) for plugins... and so on
pinmanager's option could tell *which* DB is talked about (the pinmanager db).

Cheers,
Chris.

**Comment by paulmillar** [comment]
Thanks for the patch that addresses some of these issues.  I've accepted the pull request and created back-ports back to 2.16.  

I agree this "big picture" is missing, but should be part of the dCache book.  This is now available as mark-down here:

https://github.com/dCache/dcache-book2

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10318/

**Comment by paulmillar** [comment]
The documentation should be updated to use the consistent nomenclature for consume queues as of dCache v3.1.12, v3.0.24 and v2.16.43.

The exact meaning of consume and subscribe is somewhat involved and only really makes sense for people developing their own plugins for dCache.  It should certainly be documented, but the configuration property defaults file is not really a reasonable place to do this.

The idea of logging which files must be synced in each of the service's replicable is good; see:

https://rb.dcache.org/r/10357/
