### ISSUE TITLE
billing: cellName a misnomer

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3301]
Hey.

In 2.16, the type of cellName was changed from:
`#   cellName    String      Name of cell submitting the message`

to:
`#   cellName    CellAddress Address of cell submitting the message`
with:
```
# Type: CellAddress
# ------------
#
#   Field          Type         Description
#   -----          ----         -----------
#   cell           String       Name of the dCache cell
#   domain         String       Name of the dCache domain
#   isQualified    Boolean      True when the address has a domain name, false otherwise

```

a) It's not clear from the documentation what happens, when one still just uses cellName (which seems to be done in the default format strings.

b) Still using cellName, seems to be a misnomer, since it's not the field for the cell name, isn't it? Having things like cellName.cell is also pretty ugly.
Would it be much better to have a "cell" field, with:
.name
.domain
.isQualified
and also:
.type
obsoleting: 
`#   cellType    String      Type of cell submitting the message`

Cheers,
Chris.

**Comment by paulmillar** [comment]
Quick answers:

Question a) it's backwards compatible with previous behaviour -- if you don't update the format string then there's no change.

Question b) I suppose we can add an additional field that would allow people to switch.  If so, 'cell' wouldn't be my first choice: there are many different kinds of cells in dCache that this isn't very clear.  Perhaps 'source' or 'submitter' would be clearer.

**Comment by paulmillar** [comment]
patch: https://rb.dcache.org/r/10319/

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10320/

**Comment by calestyo** [comment]
as for a) thanks

as for b) Well sorry, but this is just how things piled up with the old config system, or with the new one, when once nearly all names were removed again, because they became inconsistent.

I think if something like this is changed, and the name (be it option or field name) doesn't fit anymore, then it should be changed as well, for the sake of cleanness.
And if the old one is then anyway rubbish, it should go away with the next major version. :-)

Most people will have anyway not touched their format strings (and you could just change the defaults to the new names, with still old behaviour), and for those that do, if a proper release notes entry is made and they do as they should (reading the notes), it's a matter of 5 mins.

I think keeping that "compatibility layer", which in many cases goes anyway away sooner or later and still requires the admin to do some work, just cause unnecessary work on you devs... and confusion on the admins.
One recent example are the *.cell.export values... it they go away... just drop them, and tell people properly how they can do it with the new system... :-)

**Comment by calestyo** [comment]
Speaking of which: dcache.root, seems IMO also a bit unfortunate... root of what? root CAs? root dir? root user? (x)root(d)? ;-)

Something like I don't know... dcache.doors.default-namespace-root-path would have been better (well perhaps not my particular example) :-D

**Comment by calestyo** [comment]
btw: The commits you've made still don't seem to explain that one can use `$cellName$` alone, and that this then seems to be equivalent to `$cellName.cell$`, AFAICS.

Cheers,
Chris.

**Comment by paulmillar** [comment]
From billing.properties

```
#   If a CellAddress 'addr' is qualified then $addr.isQualified$
#   expands to true, $addr.domain$ provides the domain name of this
#   cell, and $addr$ expands to $addr.cell$@$addr.domain$.
#
#   If a CellAddress 'addr' is not qualified then $addr.isQualified$
#   expands to false, $addr.domain$ expands to 'local' and $addr$
#   expands to $addr.cell$.
```

This describes how `$cellName$` behaves.  It is not equivalent to `$cellName.cell$` in all circumstances.

**Comment by calestyo** [comment]
Ah... sorry... I missed the part where you wrote "$addr$ expands to $addr.cell$@$addr.domain$" O:-)
