### ISSUE TITLE
is srm.loginbroker.root = ${dcache.root} correct?

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3302]
Hi.

AFAIU the *.loginbroker.root are should be set to the exported root-path of the respective door, right?
The file srm.properties has:
srm.loginbroker.root = ${dcache.root}

But for SRM, isn't that rather what's set in:
srmmanager.root = ${dcache.root}

Shouldn't either that be taken or some copied value e.g.:
srm.root = ${srmmanager.root}
srm.loginbroker.root = ${srm.root}

Cheers,
Chris.

**Comment by paulmillar** [comment]
You're quite right that the two properties are related and that this relationship is not well documented.  This should be fixed.

This linkage can be made explicit by introducing an extra layer of default (`dcache.srm-root`) to avoid having configuration loops and making sure it is clear which properties affect which services.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10321/
Patch: https://rb.dcache.org/r/10322/

**Comment by calestyo** [comment]
+1
