### ISSUE TITLE
possible srm|srmmanager.ping-extra-info mixup in srm.properties

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3303]
Hi.

In srm.properties there is:
```
#  Sites can provide additional information by configuring properties
#  with a name that starts 'srmmanager.ping-extra-info!'.  The ExtraInfo key
#  is the property name without this prefix and the ExtraInfo value is
#  the property's value.
#
(prefix)srmmanager.ping-extra-info = The ExtraInfo items in an srmPing response.
srm.ping-extra-info!backend_type = dCache
srm.ping-extra-info!backend_version = ${dcache.version}
```

Just guessing, but shouldn't that be either all srm or all srmmanager? And if it's the later, shouldn't the whole section go to srmmanager.properties?

Cheers,
Chris.

**Comment by paulmillar** [comment]
Good catch.
Although it seems to work fine as-is, the `srmmanager.ping-extra-info` is wrong.
Patch: https://rb.dcache.org/r/10323/
