### ISSUE TITLE
undocumented change of default values

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3304]
Hi.

Apparently in some 2.16 version the defaults values of these:
```
(deprecated)srm.cell.limits.message.threads.max = 10
(deprecated)srm.cell.limits.message.queue.max = 100

```changed to:
```
(deprecated)srm.cell.limits.message.threads.max = 1
(deprecated)srm.cell.limits.message.queue.max = 1000

```

Even though deprecated, this should go to the release notes of 2.16 (in the next patch version, as people probably don't read the older)... and also for 3.x (if these options still exist there.

Cheers,
Chris.

**Comment by paulmillar** [comment]
Updated

**Comment by calestyo** [comment]
Hey.

While probably no one has changed these values anyway, I don't think the patch you've made is in principle enough.

Anyone who is already after 2.16, will no longer read the release notes for it, and still miss the changed default.
As will anyone who is already after 2.16.0 (where you've added the forgotten change).

Generally:
If such things are forgotten, then IMO a not should be given in the *next* patch version release note section, of all >= major versions, to make sure everyone catches up.
And if it's just a pointer to the commits where one updates the old release notes entries.

Cheers,
Chris.
