### ISSUE TITLE
several options dropped, without being marked as such

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3305]
Hi.

As previously already, at least again in 2.16,.. several options seem to have been dropped from the default files, without being marked as such, e.g. at least:

poolmanager.plugins.selection-unit
chimera.db.jar.*
dcache.service.broadcast
broadcast.cell.name
billing.db.inserts.max-before-commit
billing.db.inserts.timeout-before-commit
billing.db.inserts.timeout-before-commit.unit
srm.ping-extra-info
srm.net.host
srm.net.local-hosts
srm.root

and likely more.
Contrary, many which were anyway immutable, have been marked as obsolete/etc. which IMO doesn't make much sense, does it?

Can't the process of finding options that are gone be automated somehow? Or at least made some test in your testing framework, that finds out about options that are gone (and not marked as such) and lists effectively changed values (which one can cross check whether they've been named in the release notes)?

:-(

Cheers,
Chris.

**Comment by calestyo** [comment]
And another issue with respect to marking obsolete/etc. options:

Nearly all those that have been marked as obsolete between 2.15 and 2.16 contain no info about what happens to them... (in the (obsolete)srm.foo=someText stanza)... however, they should actually contain, that the option is now just in srmmanager, with the same (sub)name.

**Comment by calestyo** [comment]
Oh and not that the above (srm.* foo options obsolete hint text missing) does not apply to all of the gone srm.* options, e.g.:
srm.service.copymanager=${dcache.service.copymanager}

# Timeout for copymanager requests
srm.service.copymanager.timeout
srm.service.copymanager.timeout.unit
seem to be really gone and don't have an srmmanager.* counterpart.

**Comment by paulmillar** [comment]
We'll try and add a layer of automation to catch these problems earlier.

**Comment by paulmillar** [comment]
The problems should be fixed with the next releases of dCache (v2.16.43, v3.0.24, v3.1.12).

Our continuous integration system has been updated to catch dropped properties.
