### ISSUE TITLE
srm(|manager).net.[ssl.]port ambiguity

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3307]
Hey.

srm.properties has:
```
#  ---- TCP Port
#
#  The port SRM will listen on for GSI-based communication.  GSI is an
#  encrypted transport commonly used in grid communication.  It is
#  similar to SSL but incompatible.
#
srm.net.port = 8443

#
#  The port SRM will listen on for SSL-based communication.  SSL is an
#  industry standard encryption transport.
#
srm.net.ssl-port = 8445

```

while srmmanager.properties has:
```
#  ---- TCP Port
#
#  The port SRM frontends listen on for GSI-based communication.  GSI is an
#  encrypted transport commonly used in grid communication.  It is
#  similar to SSL but incompatible.
#
srmmanager.net.port = 8443
#
#  The port SRM frontends listen on for SSL-based communication.  SSL is an
#  industry standard encryption transport.
#
srmmanager.net.ssl-port = 8445
```

Not sure, but something seems to be fishy here:
I thought srm was the front-end doing the listening... so why has srmmanager ports at all? And even if he needs them (not for listening), then it should probably be a copy of the srm.* value.

And if really both listen, then this naturally can't work on the same host, so there should be documentation about that.

Cheers,
Chris.

**Comment by paulmillar** [comment]
The srmmanager needs to know the port number to establish whether a SURL is local or not.

For now, I suggest we can update the documentation to make this clearer

**Comment by calestyo** [comment]
Mhh, docs update would be a first point.
Many other config options used a schema like that, when they just needed some value from another service:
*.service.*.option, e.g. when httpd needs the info service it has: httpd.service.info
or when srm configures it's timeout for communication with gplazma it uses srm.service.gplazma.timeout .

So wouldn't it have been better to name it like that, and not copy over it's value but do something like:
`srmmanager.service.srm.net.port = ${srm.net.port}`

**Comment by paulmillar** [comment]
No.  as I've already explained, a service cannot refer to another service's properties.

Doing this would make it impossible to know the effect of modifying a property.  In your example: modifying `srm.net.port` would also effect the srmmanager service.

**Comment by paulmillar** [comment]
With dCache v3.2, the 'srmmanager.net.port' and 'srmmanager.net.local-hosts' properties are no longer needed.
