### ISSUE TITLE
implicitly add :${dcache.zookeeper.net.port} to elements in dcache.zookeeper.connection

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3367]
Hey.

Just some minor enhancement idea.
It would be nice, if `:${dcache.zookeeper.net.port}` was added implicitly to any element in the list `dcache.zookeeper.connection` that doesn't end in `:[:digits:]`, so that one could write e.g.:
`dcache.zookeeper.connection=host1.example.org, host2.example.org, host3.example.org`
instead of having to write either:
`dcache.zookeeper.connection=host1.example.org:2181, host2.example.org:2181, host3.example.org:2181`
or
`dcache.zookeeper.connection=host1.example.org:${dcache.zookeeper.net.port}, host2.example.org:${dcache.zookeeper.net.port}, host3.example.org:${dcache.zookeeper.net.port}`

Oh and if that was added, it should obviously be documented in the .properties file ;-)

Cheers,
Chris.

**Comment by paulmillar** [comment]
[... and I thought you were complaining that the properties in defaults file were no longer obvious!  Here you're proposing to make the value even more convoluted by adding extra (non-visible) post-processing!]

Yes, sure, I guess it would possible to add something like this.  We could also add support for the ZooKeeper chroot that some sites are (or "are planning on") using.

However, bear in mind that this configuration property is passed to ZooKeeper client directly.

This decouples us for all changes that ZooKeeper makes in the connection string format: if they add a new feature, it's (trivially) automatically supported in dCache.  If we start to form the connection string then we would need to take care that we don't prevent additional metadata from going into that string.

Take as an example, your automagically adding the port number to the hostnames.  Adding support for ZooKeeper's chroot would require changes in dCache before sites could take advantage of it.

So, currently, I personally don't see the benefit of not repeating the port number as outweighing the benefits of simplicity (it's just the connection string) and decoupling (for dCache, it's an unstructured string; so any changes in format are automatically support by dCache).

**Comment by calestyo** [comment]
Hey.

First, it's not "complaining"... it's (always) just well meant ideas for improvement, and in the case of me suggesting not to provide backwards-compatibility layers,... it's: me trying to give you devs solid ground that there are sites who don't care about these temporary layers... so you don't have to do them (if you don't want to).

Well, given your argument with the ZK connection string properties, and also that sites want to chroot... I think we can really close that...

Hasn't `dcache.zookeeper.net.port` been anyway removed again already? I only saw that afterwards... and just found it ugly to either write:
`dcache.zookeeper.connection=host1.example.org:${dcache.zookeeper.net.port}, host2.example.org:${dcache.zookeeper.net.port}, host3.example.org:${dcache.zookeeper.net.port}`
or not use the property `dcache.zookeeper.net.port` at all if it's already there ;-)

Thus closing.

**Comment by paulmillar** [comment]
Hiya,

Yes, sorry, I should have put "complaining" in quote marks!  That part in square brackets was meant as a humerus aside :-)  Your comments are always welcome .. feedback is useful, if for no other reason that it provides another point-of-view, which helps us double-check our thinking within the team.  We try to avoid "groupthink", but it's always there as a trap.

You're right: `dcache.zookeeper.net.port` is gone with dCache v3.0 -- there's only `dcache.zookeeper.connection`.

**Comment by calestyo** [comment]
> Yes, sorry, I should have put "complaining" in quote marks! That part in square brackets was meant as a humerus aside :-)

No worries :-) All fine.
I just thought it's a good idea, since I'm actually opening tickets from time to time which are either cosmetic, or contain rather "general" things as wlel, which aren't necessarily bugs.

Cheers =)
