### ISSUE TITLE
resilience.plugins.storage-info-extractor refers to non-existant ${dcache.plugins.storage-info-extractor}

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3377]
In latest 2.16, there is:
`resilience.plugins.storage-info-extractor=${dcache.plugins.storage-info-extractor}`
however, `dcache.plugins.storage-info-extractor` doesn't exist.

Chris.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/10399/

**Comment by paulmillar** [comment]
Should be fixed with the next release of dCache 2.16 (2.16.45)

**Comment by calestyo** [comment]
thx =)
