### ISSUE TITLE
wiki: "further options in the ZKconnection string"

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3378]
Hey.

This is absolutely minor, but perhaps someone can clarify/improve.

The wiki page at:
https://github.com/dCache/dcache/wiki/ZooKeeper
says:

> See the ZooKeeper admin guide for details on further configuration options that can be specified in the connection string.

However, I couldn't find any such information in the ZK admin guide,... so perhaps this is either to be removed because just confusing, or someone who knows where these further options for the connection string can be found, could directly link from the wiki page to it? :-)

Cheers,
Chris.

**Comment by paulmillar** [comment]
You're quite right -- please feel free to open a ticket with ZooKeeper!

In the mean time, I've updated the page with a link to what little documentation is available.

**Comment by calestyo** [comment]
thanks :-)

And as for ZK upstream... well... not sure if that's not rather like fighting windmills ;-) .... I did however open quite a number of bugs against the Debian packaging.
