### ISSUE TITLE
bogus text in release notes

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3379]
Hey.

The release notes entry for 3.0.25 **and** 3.1.13 contains:
H: 9132256 240fa42 e914aad R: 3.1.13 3.0.25 2.16.44

Maybe the usual links to the commits are somehow messed up here.

Cheers,
Chris.

**Comment by mksahakyan** [comment]
This is now fixed.

**Comment by calestyo** [comment]
thx :-)
