### ISSUE TITLE
pnfsmanager.enable.move-to-directory-with-different-tags vs. pnfsmanager.enable.move-to-directory-with-different-storageclass

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3409]
pnfsmanager.properties has `pnfsmanager.enable.move-to-directory-with-different-storageclass`, while nfs.properites mentiones:

> Currently this option makes sense only if
> pnfsmanager.enable.move-to-directory-with-different-tags
> is set to false. See pnfsmanager properties file for description

of which `pnfsmanager.enable.move-to-directory-with-different-tags` doesn't exist.

So either the documentation is wrong, or the options shall be renamed or both.
(I think the later would be better, as, AFAIU, the check is not only about the storageclass, but also the cache class, and thus the current option name is kind of a misnomer).

Cheers,
Chris.

**Comment by paulmillar** [comment]
Thanks for reporting this

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10633/

**Comment by calestyo** [comment]
I think it's still wrong... either the option name is a misnomer, or the documentation is wrong, which claims that BOTH storage AND cache class are looked at. :-(

**Comment by paulmillar** [comment]
I took this issue to be an inconsistency between documentation and reality: the documentation described a property that simply didn't exist.

This problem has been fixed -- the document that describes this behaviour uses the property name that dCache will react against.

If you disagree with the choice of property name then please open a fresh ticket as that's a separate issue.

**Comment by calestyo** [comment]
Well no worries… it's not really an issue for me,... I just thought it could be unclean and that such things might pile up again.

Cheers =)

**Comment by paulmillar** [comment]
I'm not saying you don't have a valid point -- the choice of names is important and what we decide upon isn't always optimal.

I'm merely saying that (IMHO) that discussion belongs as a separate issue, and shouldn't necrobump this one.
