### ISSUE TITLE
httpd behind reverse proxy

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3428]
Hey

I was reading in the changelogs for 3.0, that most links should be now relative so operation behind a reverse proxy (like I do with Apache) should work better now.

In fact, most links are relative now, but there are still several things that don't work and I'm not sure whether it's my fault or other issues.

Currently it looks e.g. like this:
![screenshot from 2017-08-08 15-05-17](https://user-images.githubusercontent.com/919933/29073247-3e98ab04-7c4b-11e7-85b1-32ea1f52ac20.png)

So it doesn't seem to find the icons, nor any stylesheets (which is, I guess, why the space usage bars are not seen).

Looking at the HTML source, these are links like:
```
<link href="./cFsk1W3JyoqczQMKLMevgVaDk9KyjJWlXc-dk2TsSIWgQqam0sOsDoRV8qdEJHLKLSjbbQNDWYkuSyApU1jUIhVIGmUp5A9GFsRa68VsGpHmFE3HLz8AnqIL4OeWlLK8E7WWBFKJoN_u-735Bfn8fcq-4qBDcxpO/cFsbf/WBF4a/V8qfe" rel="stylesheet" type="text/css"/>
<link rel="shortcut icon" type="image/x-icon" href="./cFsk1W3JyoqczQMKLMevgVaDk9KyjJWlXc-dk2TsSIWgQqam0sOsDoRV8qdEJHLKLSjbbQNDWYkuSyApU1jUIqGt5dJA3KU-M31J3jtUgSctsNAqgCYo_gYJKAZoTJMWY4OVVLw6Tp9ksQr9tpG0G1LgYGPJMkrE/cFsbf/VVL5b/8qd8a"/>    
<link href="./cFsk1W3JyoqczQMKLMevgVaDk9KyjJWlXc-dk2TsSIWgQqam0sOsDoRV8qdEJHLKjqmEH7k6mcFtRNj211xD9wzBxm2jRZbJh1QigxzR_HZDJH-eywOOh_HvN7Dohs9EJ5foBvQGdrADKPmi25HrS9zdQw_1lJg2/cFsbf/oBv92/EJH72" rel="stylesheet" type="text/css"/>
<link href="./cFsk1W3JyoqczQMKLMevgVaDk9KyjJWlXc-dk2TsSIWgQqam0sOsDoRV8qdEJHLKu95pNXVAxwZ-s-k9-KgGGuDUMJ9DLV4ClAqOegIJORDpzrtI8dhUAcQAXRsLrKO7H7ZriHNnkBMfMuEeMHUZRnGmpPWzfKTtUJJJfeGUmkshxe7YYDLbCGJa_RNXZrUC/cFsbf/pNX49/am063" rel="stylesheet" type="text/css"/>
```

Accessing these directly, gives me an Jetty error message ("Not Found").

Any ideas? :-)

Cheers,
Chris.

**Comment by paulmillar** [comment]
When you say "accessing these directly..." is that accessing these URLs through the proxy  but using a client like curl, or accessing the equivalent URL that targets dCache directly?

Also, if you view the dCache web pages directly (not through the proxy) do you see the same problem?

**Comment by paulmillar** [comment]
Any update on this issue?

**Comment by alrossi** [comment]
HTTPD no longer supported.

**Comment by calestyo** [comment]
You are aware that many (most?) sites still use and depend on httpd?!

Let's not repeat the still unsolved info-provider debacle.
