### ISSUE TITLE
Add posgresql port property to dcache-star  

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#3570]
If the chimera database is host on a server with a port different as default 5432 (ie dcache.db.host=ccpgsqlxx.in2p3.fr:6551) , the command will fail with the error : dcache-star: Problem detected: could not translate host name "ccpgsqlxx.in2p3.fr:6551" to address: Name or service not known

Can you implement this in the dcache-star code please?
```
    db_name = properties.get('chimera.db.name')
    db_host = properties.get('chimera.db.host')
    db_user = properties.get('chimera.db.user')
    db_pw = properties.get('chimera.db.password')
    conn = psycopg2.connect(database=db_name, user=db_user, host=db_host, password=db_pw)
```

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10629/
