### ISSUE TITLE
dcache.service missing from debian packages

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3658]
Hi.

Seems the new dcache.service file is missing from 3.2.5… o.O

Cheers,
Chris.

**Comment by calestyo** [comment]
I'd guess that packages/fhs/src/main/assembly/deb.xml may need to be adapted somehow... but I have no idea about the Maven black magic and <avada kedavra>please simply add all files</avada kedavra> didn't work ;-)

**Comment by vingar** [comment]
suggested file: packages/fhs/pom.xml. correct  ? which files should be added there ?

**Comment by paulmillar** [comment]
The file `dcache.service` is not included because the pull-request failed to update the file `packages/fhs/src/main/assembly/deb.xml`.

**Comment by calestyo** [comment]
Well I did mention in the PR already, that I have no clue about maven or other Java-ish build systems... and that I don't know whether the build system needs to be told about the new file:
https://github.com/dCache/dcache/pull/3628#issuecomment-339438940

So could someone just write another commit which does the required changes to the build system?

**Comment by calestyo** [comment]
Seems like #3668 (and #3669 for the 3.2 backport) would do the job (but someone should double check).

btw: I was just shocked to see that the build system downloads gazillions of code and binary from some locations and executes them on the system... a security nightmare o.O

**Comment by calestyo** [comment]
fixed by the merged PRs
