### ISSUE TITLE
history.service.pools.storage-dir

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3733]
Just a blind guess, the default of:
`history.service.pools.storage-dir=/var/lib/dcache/pool-history`
which is:
`drwxr-xr-x 1 root   root     0 Oct 17 11:50 pool-history`
is likely not writeable by the dcache user.

**Comment by paulmillar** [comment]
Hi Chris,

Thanks for reporting this; we'll fix it as soon as possible.

Cheers,

Paul.

**Comment by paulmillar** [comment]
We should also check whether this broken deployment results in error messages being logged.

**Comment by calestyo** [comment]
I couldn't check this, since I haven't been using the history service so far… I just noticed this possible issue, when I went through the changes in the properties files.

**Comment by alrossi** [comment]
Fixed.
