### ISSUE TITLE
Please allow WebDAV redirects to HTTPS

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#3736]
Currently, the WebDAV door after authentication redirects to a HTTP door for the transfer. For security & privacy reasons, we'd like to have the possibility to have the door redirect to HTTPS.

I'm aware that switching off redirects will allow all traffic to go over HTTPS, but it's nice to have redirects for load balancing.

Thanks!

**Comment by paulmillar** [comment]
Hi Onno,

Just out of interest, is there a particular user community requesting this?  It's just nice to know who's using dCache.

Some other thoughts:

Currently the WebDAV door issues the client a secret when redirecting: the `dcache-http-uuid` query parameter.  In effect, this secret is a bearer authorisation token; it allows whoever presents it access to a single file and for a single use.  The token is used in lieu of the client re-authenticating when making the request to the door, which makes sense given the client's request to the pool is (currently) always unencrypted.

However, this authorisation token is not bound to the client in any way.  If some third-party somehow acquires this token (and they are faster than the client) then they can read that file's content.  Note that this attack is independent of whether pool communication is encrypted.  The authz token is protected from network attacks by TLS; however, TLS is the only protection and is not without its failures in the past.  The client could leak the authz token (e.g., logging redirection URL), which is especially true for web-browsers.

There are two obvious solutions here: 1. bind the authz token to the client and 2. require client authentication when connecting to the pool.  The former is relatively easy to bind to the client's IP address, but this risks breaking some exotic setups; the latter might not be too hard, but would require some thinking to plan out what make sense.

So, here's my question: is any of this necessary, or would simply enabling TLS be sufficient for your users?

Cheers,

Paul.

**Comment by onnozweers** [comment]
Hi Paul, 

Beside HEP users we also have life science users with data sets of DNA sequences and with MRI scans. Because of the privacy concerns we'd like to encrypt their traffic. Just a layer of TLS would do. For now, we'll add extra WebDAV doors that don't do redirects to cover their needs. So this request is not urgent. 

I have to say I was a bit surprised that HTTPS connections were redirected to HTTP; I wasn't aware of that before. Hence the pull request to add a warning to the webdav.properties file about this, which has already been approved by Tigran. 

You're right that TLS is not always safe. We consider it good practice to test with for instance the Qualys SSL test or with OpenVAS regularly and trying to make the TLS more robust. 

Kind regards 
Onno 

Van: "Paul Millar" <notifications@github.com> 
Aan: "dCache/dcache" <dcache@noreply.github.com> 
Cc: "onno zweers" <onno.zweers@surfsara.nl>, "Author" <author@noreply.github.com> 
Verzonden: Dinsdag 28 november 2017 12:13:01 
Onderwerp: Re: [dCache/dcache] Please allow WebDAV redirects to HTTPS (#3736) 



Hi Onno, 

Just out of interest, is there a particular user community requesting this? It's just nice to know who's using dCache. 

Some other thoughts: 

Currently the WebDAV door issues the client a secret when redirecting: the dcache-http-uuid query parameter. In effect, this secret is a bearer authorisation token; it allows whoever presents it access to a single file and for a single use. The token is used in lieu of the client re-authenticating when making the request to the door, which makes sense given the client's request to the pool is (currently) always unencrypted. 

However, this authorisation token is not bound to the client in any way. If some third-party somehow acquires this token (and they are faster than the client) then they can read that file's content. Note that this attack is independent of whether pool communication is encrypted. The authz token is protected from network attacks by TLS; however, TLS is the only protection and is not without its failures in the past. The client could leak the authz token (e.g., logging redirection URL), which is especially true for web-browsers. 

There are two obvious solutions here: 1. bind the authz token to the client and 2. require client authentication when connecting to the pool. The former is relatively easy to bind to the client's IP address, but this risks breaking some exotic setups; the latter might not be too hard, but would require some thinking to plan out what make sense. 

So, here's my question: is any of this necessary, or would simply enabling TLS be sufficient for your users? 

Cheers, 

Paul.

**Comment by onnozweers** [comment]
This functionality has been added with the settings `webdav.redirect.allow-https` and `pool.enable.encrypted-transfers`.

Thanks!
