### ISSUE TITLE
Linkgroup authorization by GID may fail if user is in multiple groups

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#3755]
Dear dCache people,

We have users who are mapped onto multiple groups in storage-authzdb. If we add the GID of one of those groups to the LinkgroupAuthorization.conf to allow writing into a link/poolgroup, and not the other group GIDs, then sometimes the user will have a successful transfer, and sometimes the transfer will fail because not valid link was found. If we then add all of those groups to the links, the link error disappears.

We can work around this by adding all involved group GIDs to the LinkgroupAuthorization.conf or by adding individual users. But it would be nice if the behaviour was a bit more deterministic. My suggestion would be, that _all_ groups that a user is mapped to, would be checked against the LinkgroupAuthorization.conf, and not only one group. If that is not possible for some reason, it would be nice if the _first_ group were checked, so that it's kind of predictable.

Kind regards,
Onno

**Comment by paulmillar** [comment]
Hi Onno,

The LinkgroupAuthz file should work the way you describe.  All gids should be used to test whether that user is allowed to reserve space: if any gid matches then the reservation is allowed to go ahead, and the upload should succeed.

Could you provide some more details on what is going wrong?

Cheers,

Paul.

**Comment by onnozweers** [comment]
We've not observed this again and we don't have time to investigate it.
