### ISSUE TITLE
Missing services.sh in dcache 3.2 (RPM)

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3788]
Reported by: "Jens Larsson" <jens___ nsc.liu.se> 

Due to a "feature" of rpm and the %post installation
script in dcache, the /usr/share/dcache/lib/services.sh script is
missing after the upgrade.
```
# dcache version
3.1.26
# rpm -U dcache-3.2.11-1.noarch.rpm
# dcache version
3.2.11
# dcache status
/usr/bin/dcache: line 426: /usr/share/dcache/lib/services.sh: No such
file or directory
```

And this is why:

The %post install script in 3.2 does:

```
# generate admin door ssh2 server key
if [ ! -f /etc/dcache/admin/ssh_host_rsa_key ]; then
    ssh-keygen -q -t rsa -f /etc/dcache/admin/ssh_host_rsa_key -N ""
    chmod 640 /etc/dcache/admin/ssh_host_rsa_key
    chgrp dcache /etc/dcache/admin/ssh_host_rsa_key
fi

# fix file /var/lib/dcache directory ownership
chown dcache:dcache /var/lib/dcache

if [ ! -f /usr/share/dcache/lib/services.sh ]; then
    ln -s /usr/share/dcache/lib/services-daemon.sh
/usr/share/dcache/lib/services.sh
fi
```

This looks OK? Right? If the services.sh script doesn't exist, link
services-daemon.sh to it. But. The execution order in an RPM upgrade of
dcache-3.1 to dcache-3.2 is:

```
Run %pre from "dcache-3.2"
Place files from "dcache-3.2"
Run %post from "dcache-3.2"
Run %preun from "dcache-3.1"
Delete files unique to "dcache-3.1"
Run %postun from "dcache-3.1"
```

So when the %post script from dcache-3.2 is running there is already a
services.sh. But then it's removed. So "yum remove dcache; yum install
dcache" works and "yum update dcache" doesn't.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10743/
