### ISSUE TITLE
Use Charset constant instead of dynamicaly discover at the runtime

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3812]
To be platform encoding independent, dcache uses in many places utf8 encoding when converting strings to bytes. To achieve this an encoding type is explicitly provided when possible, like

```
   byte[] bytes = "foo".getBytes("UTF-8");
```

Starting java7, java.nio.charset.StandardCharsets provides a set of constants for various charsets, which are initialized during jvm initialization, which makes it more efficient.

**Comment by paulmillar** [comment]
Another benefit is that it avoids dead-code.  The Charset-arg version of `getBytes` throws no (checked) exceptions.  Given the JVM must support UTF-8, the call to `getBytes("UTF-8")` will never actually throw the declared  `UnsupportedEncodingException`.  However, the checked exception must be caught and handled, bloating the code and obfuscating it.
