### ISSUE TITLE
please implement chimera command to recursively set tags on a dir and/or file structure

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3920]
Hi.

This has popped up several times on the user-forum and I know that at least I myself asked several times for support with it (but think without a reply).

It happens that sites need to recursively set pnfs tags on an existing file structure (I'd guess most of the time it will just be required for directories).

Most prominent examples are:
- one wants to set WriteToken
- one wants to change the name of OSMTemplate or sGroup

Especially the former may happen much later, when a large directory hierarchy already exists (e.g. in the case of ATLAS, where writes have been mostly done via space managed SRM only, and since some time now there are requests that xrootd or webdav writes would be enabled).

If one now sets e.g. WriteToken on an existing directory structure with perhaps millions of dirs, a huge number of such tags will be added to the DB, AFAIU.
In contras, AFAIU, if this would have been set in the beginning, directories created below the top dir, would have inherited the very same tag "object" in the DB.

I think what we need is the following:
- a command for chimera to recursively set tags on at least a directory structure (I can't think of a case right now where setting tags on regular files would be useful?).
- a kind of a fsck/cleanup command which looks in the DB for tags with equal key/vale and unifies them
(in order for sites to clean up, which have previously and accidentally created many clones.

Thanks,
Chris.

**Comment by XMol** [comment]
Once upon a time, together with Tigran we came up with the following pSQL function to push the value of a tag down to all subdirectories in the namespace branch (by referencing to the tag-id of the starting directory):

```sql
CREATE OR REPLACE FUNCTION push_tag(varchar, varchar) RETURNS void AS $$
DECLARE
  root varchar := $1;
  tag varchar := $2;
  subdirs RECORD;
  tagid varchar;
BEGIN

SELECT INTO tagid itagid FROM t_tags WHERE ipnfsid = root AND itagname = tag;

FOR subdirs IN
  SELECT t_inodes.ipnfsid, t_dirs.iname
  FROM t_inodes, t_dirs
  WHERE t_inodes.itype=16384
    AND t_dirs.iparent=root
    AND t_inodes.ipnfsid=t_dirs.ipnfsid
    AND t_dirs.iname NOT IN ('.', '..')
LOOP
  BEGIN
    DELETE FROM t_tags WHERE ipnfsid = subdirs.ipnfsid AND itagname = tag;
    INSERT INTO t_tags VALUES (subdirs.ipnfsid, tag, tagid, 0);
    PERFORM push_tag(subdirs.ipnfsid, tag);
  END;
END LOOP;

END;
$$
LANGUAGE 'plpgsql';
```

Problem is, this was developed for dCache version 2.13 and therefore is in need of some changes in order to adapt to current dCache versions. In particular, the PNFS-ID is no longer the defining attribute of a file/directory in Chimera, since it has been replaced by a simple integer (inumber).

**Comment by calestyo** [comment]
Thanks for posting this... but I think this should still become just a normal command:
It's not really healthy if such magic code snippets float more or less unmanaged around (people make changes to it, try to adapt it to new versions etc.) and in the worst case on ends up with some version of it that rather breaks things.

Also, at least adding the function changes the schema (and kinda breaks the idea of liquibase)... and I think we have already enough troubles with sites having subtly different schemas for historical reasons...

:)

**Comment by XMol** [comment]
I mainly intended to save the devs some time so they don't have to start over from scratch... Adding the function to your database as administrator should be a last resort, given that it is broken in its current state, I fully understand that.

**Comment by calestyo** [comment]
Intention was clear :-) That's why I've said "Thanks" :-) ... just wanted to give motivation that we get such functionality despite of it being "manually" doable :-)

**Comment by ageorget** [comment]
Any updates about this request?
As you may know, the Globus toolkit are no more supported since 2017 [1] and WLCG VOs are discussing about using xrootd/webdav in replacement of GridFTP for third party copy.
It becomes important for us to have this chimera command to set writetoken tags in order to enable write with xrootd/webdav protocols.
[1] https://indico.cern.ch/event/743996/contributions/3073681/attachments/1693378/2725079/WLCGStorageProposal-2.pdf

**Comment by onnozweers** [comment]
Any news about this request?

In the near future we will have to change ACLs for 6M files. A recursive option would really help. Without this, the chimera command takes 2.4 seconds per operation (last time I checked). So this large ACL change would take 167 days. In a previous version, the command took 1/6 seconds; that would take 11 days, that was workable. We could try a database query, but that's scary.

**Comment by calestyo** [comment]
@paulmillar @kofemann Could you have a look at this issue? I brought this up several times over the years (even before this ticket) and during the workshops.

It seems at least ATLAS now pushes towards being able to write to space tokens without using SRM, so many sites wille need a proper way to set the WriteToken tag (kinda soonish).

Taking LMU as an example we have already +2,3 million directories in the space managed areas. Setting a fresh (and not inherited) instance of the PNFS tag on each of them is probably not a good idea, is it?

Thanks :-)

**Comment by DmitryLitvintsev** [comment]
Chris , 

In principle we have a patch on RB (for many years):

https://rb.dcache.org/r/7739/

It was OK'd at first but then Gets had some reservations. 

We are happily running with this patch applied. 

NB: setting tags on really deep directory structure is quite consuming .


IMHO handling of tags had been screwed up when we switched from pnfs to chimera.

Dmitry 
_______________________________________

**Comment by calestyo** [comment]
> We are happily running with this patch applied.

Well I wouldn't want to play guinea pig with such an important thing... neither would want to apply a changeset to the DB which then only some sites have and which future dCache upgrades may not expect.
And also I'd guess these changesets are for the 4 year old version of Chimera... haven't many things changed now like PNFSID no longer being the primary key and so on?

There really needs to be a proper/official solution for this... not some manual hacks :-)

**Comment by DmitryLitvintsev** [comment]
Chris:

I am not implying that you should be running this patch (or otherwise be a guinea pig).
I am simply informing you that we have a patch that does what you want and that we have
been running it @ Fermilab for years (in lieu of testing the patch).
Patch was OK'd initially but Gerd had objections.
May be dCache team needs to re-visit this patch.

Thanks,
Dmitry

________________________________________

**Comment by calestyo** [comment]
Hey.

Yeah that was clear... and I absolutely didn't mean it negatively :-D Just wanted to point out that in the current form it's not usable in a production system :-)

RIght now it seems that ATLAS pushes a bit more towards this direction, and given that this needs some time to be implemented and sites to actually run that version of dCache, it's something that should IMO really be revisited.

Otherwise sites might be forced to set a tag manually on each directory (which is probably not what one wants)... or try alternative means like recreating the whole directory hierarchy of their chimera (with proper tag inheritance) and moving regular files from the old to the new one - doesn't sound very compelling either ;-)

Thanks,
Chris

**Comment by afortiorama** [comment]
> It seems at least ATLAS now pushes towards being able to write to space tokens without using SRM, so many sites wille need a proper way to set the WriteToken tag (kinda soonish).

is this a showstopper or an inconvenience? We need to decide deadlines at some point and I don't want to put sites in an impossible position.

**Comment by kofemann** [comment]
I can accept, that is required for some operations (though I don't
understand how experiments can require SRM functionality with non SRM
protocol),
but I don't see how it connected to third-party-copy operations.


-kofemann
/** caffeinated mutations of the core personality */

**Comment by afortiorama** [comment]
TPC is SRM-less. I'm trying to understand how important it is to have this functionality for sites to switch off SRM. I'm not a dcache admin, so I have no  feeling of how necessary this might be if the main protocol is something else than SRM (eventually http or xrootd and right now gridftp).

**Comment by calestyo** [comment]
@kofemann It seems (though this is only my understanding) ATLAS wants to fully move away from SRM.


@afortiorama The actual impact is hard to say unless someone plays guinea pig and tries it out, and even then the actual problems may arise only years later.
We at LMU for example have 2.329.445 directories in the space managed areas, which is quite a lot. Not sure why rucio has a layout where it creates these enormous amounts (and never again deletes them even if empty), but that's it.

If we'd now want to enable writing inside space reservations without an aware protocol (i.e. not SRM) we'd need to set the WriteToken tag on each of thise +2 mio dirs.
Which would create a distinct tab object (and associated records) for each of them in the DB.
Not something one should want.

Also see Onno's comment above on how long such operations took on their system (though I haven't checked the same with WriteTag).

**Comment by calestyo** [comment]
Maybe one thing to add to the ticket:

I vaguely remember, that once a tag was created in the DB it used to never be deleted again (een if the directory/file that links to it got delete or the tag overwritten.
Not sure if this actually was and/or still is the case... perhaps one of the developers could confirm.

This - if true - would of course mean, that the problem isn't reduced by saying that directories will sooner or later be removed (and thus things cleaned up).

**Comment by kofemann** [comment]
Yes, that's true if you still use dcache version 2.12.

-kofemann
/** caffeinated mutations of the core personality */

**Comment by calestyo** [comment]
> Yes, that's true if you still use dcache version 2.12.

Okay so that (objects never being deleted) is **no** problem for any recent site. :-)

**Comment by calestyo** [comment]
Great to see that implemented :-) Thanks

Would it be easy to backport to older dCache versions (4.2?)... though this is really not necessary if it's an effort, cause sooner or later we'll upgrade :-)

**Comment by kofemann** [comment]
No backports into earlier releases. dCache-5.2 is the first release that is required from WLCG to operate in SRM-less world.
