### ISSUE TITLE
dcache code base uses JDO, which is not supported by spring framework

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3927]
As dCache heavily uses Spring we have to move away from JDO in favor of JPA to make migration to Spring 5 possible, as JDO is no longer supported by spring framework:

https://jira.spring.io/browse/SPR-14130

**Comment by alrossi** [comment]
What precisely needs to be changed?

For instance, Alarms and Billing do not use native Spring orm.jdo.  

The only thing that is exposed in Spring is the injection of a single class from DataNucleus: 
 
org.datanucleus.api.jdo.JDOPersistenceManagerFactory

Surely this will still be possible?

So I am not sure why we would be constrained to rewrite the underlying JDO layer until DataNucleus decides to abandon JDO as well.

**Comment by kofemann** [comment]
PinManager uses JDO. DataNucleus themselfs recommend to use JPA2.1 if backend is RDBMS.
Unfortunately, DataNucleus does not specify a migration path :(. I don't think we need to jump right away, but we should be aware of our weak points.

**Comment by alrossi** [comment]
I know DataNucleus has been recommending JPA over JDO for a while now, true.  But the model is rather different and it would entail more than trivial changes, as you note.

I had forgotten about PinManager.

**Comment by alrossi** [comment]
The only spring JDO dependency in dcache has been removed

https://rb.dcache.org/r/11078/
