### ISSUE TITLE
PnfsManager doesn't understand "md5"

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4064]
Dear dCache devs,

When you specify `md5`, it's not (always) understood:

```
[dcmain] (local) admin > \s PnfsManager get file checksum 0000D1B4A9DEA4F848CA99A28B527CF26C58 MD5
Syntax error: (2) No enum constant org.dcache.util.ChecksumType.MD5
Help : 
get file checksum <pnfsid> <type>  # returns file checksum
```

Specifying `md5_type` seems to work:

```
[dcmain] (local) admin > \s PnfsManager get file checksum 0000D1B4A9DEA4F848CA99A28B527CF26C58 MD5_TYPE
[dcmain] (local) admin > 
```

But in the help:

```
[dcmain] (local) admin > \s PnfsManager help get file checksum
...
       <type>
              The checksums type of the file. These following checksums
              are supported: adler32, md5 and md4.
```

It clearly says `md5`, not `md5_type`.

In this particular case there is no md5 sum available, that's probably why there's no output. An error message explaining this would be nice ;-)

Thanks!
Onno

**Comment by kofemann** [comment]
Hi Onno,

this is a clear bug on our side. Thanks for reporting!

Tigran.
