### ISSUE TITLE
kafka: Issue with DESY doors

### ISSUE THREAD

**Issue by mksahakyan** [dCache/dcache#4199]
After the server is  down after a while some of the doors (mainly ftp door) was  shout down.

Without server, Kafka messages appear as open pipes
to accumulate on the Doors [1] - what a massive, ~ gradual
Increase in CPU load leads (~~ the gridftp domain processes).

  the problem is :

 _kafkaProducer = _settings.createKafkaProducer(_settings.getKafkaBootstrapServer(),
                                                           _cellAddress.toString(),
                                                           _settings.getKafkaMaxBlockMs(),
                                                           _settings.getKafkaRetries());
                                                           _settings.getKafkaBatchSize();
                                                           _settings.getKafkaBufferMemoryKafka();
                                                           _settings.getKafkaLingerMsKafka();

It looks like we are ending up by  first reaching  the limit of open files for the server. The default setting of 1024 for the maximum number of open files on most Unix-like systems is insufficient.

java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at kafka.network.Acceptor.accept(SocketServer.scala:452)
        at kafka.network.Acceptor.run(SocketServer.scala:395)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kofemann** [comment]
Fixed by: 9071d4d9f511c1917246a658a2ad7f2ddfdf5d72
