### ISSUE TITLE
context/transfers.json

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#4297]
the path is not being set in this (httpd observer).

the path is correct through RESTful API, though, appearing in Swagger and in dcache-view

**Comment by alrossi** [comment]
http://<host>:2288/context/transfers.json

not the RESTful interface, but the httpd collector.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11262/

**Comment by jstarek** [comment]
Can we close this as resolved as soon as the patch is released later today?

**Comment by alrossi** [comment]
We can close it now, thanks.
