### ISSUE TITLE
5.1.0-snapshot Build failure (java 10)

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4504]
Dear dCache developers,

I have built dCache from the master (4.3.0 and 5.0.0) snapshot several times. I use this command:

    mvn clean package -am -pl packages/fhs -P rpm

Since a few weeks, I can no longer get it to work. This is what I get:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cells: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException: org.ietf.jgss.GSSException -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :cells

With `-e` I get this:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cells: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException: org.ietf.jgss.GSSException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cells: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException

Any ideas what could be wrong?

Kind regards,
Onno

**Comment by kofemann** [comment]
Hi Onno,

which version of JDK and maven do you use?

**Comment by onnozweers** [comment]
Hi Tigran, 

Thanks for your rapid reply. I see now I have installed Oracle Java 10, is that the problem?

    [root@dolphin12 ~/dcache-5.1.0/dcache]# mvn --version
    Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
    Maven home: /usr/local/src/apache-maven
    Java version: 10.0.2, vendor: Oracle Corporation
    Java home: /usr/java/jdk-10.0.2
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "3.10.0-957.1.3.el7.x86_64", arch: "amd64", family: "unix"

    [root@dolphin12 ~/dcache-5.1.0/dcache]# java --version
    java 10.0.2 2018-07-17
    Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by kofemann** [comment]
Up-to-now we test that cache run with java11, but compiling still can be an issue.

**Comment by onnozweers** [comment]
Thanks, that is good to know. I've removed JDK 10 and now it works:

    [INFO] BUILD SUCCESS

So, dCache now runs on Java 11? Which versions of dCache?

**Comment by kofemann** [comment]
The current master and 5.0 should run with java11. The corresponding set of changes are prepared for 4.2 as well, but we are delaying that changes until, first production experience with 5.0.
