### ISSUE TITLE
`dcache ports` does not list 8445

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4512]
Dear dCache devs,

The `dcache ports` command does not list port 8445 (SRM over TLS) while the port does seem to be open:

    [root@dolphin12 ~]# netstat -nap | grep 8445
    tcp6       0      0 :::8445                 :::*                    LISTEN      66653/java          

I tested this on 3.2.x and on 5.1 snapshot.

Kind regards,
Onno

**Comment by paulmillar** [comment]
Hi Onno,

Thanks for reporting this, we will fix this shortly.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/11489/

**Comment by onnozweers** [comment]
That was impressively fast! 🥇

Thanks, Paul!
