### ISSUE TITLE
Update Pgpass class to use file system  API to check file permissions 

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#4670]
Pgpass file uses `stat` binary check file permission. This is not required as java7 have introdiced new API that allows to discover posix file attributes.

Additionally, URI class can be used to identify is string a url or not.

**Comment by tomdittrich** [comment]
I will give it a try.

**Comment by tomdittrich** [comment]
@kofemann 
> Additionally, URI class can be used to identify is string a url or not.

Do you mean something like this? https://stackoverflow.com/a/5719282/8041403
Or is there a extra URI class within the project?

**Comment by kofemann** [comment]
@tomdittrich I was mo thinking about  [URI#create](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html#create-java.lang.String-), But feel free to have an alternative solution.

**Comment by tomdittrich** [comment]
`URI.create` have little problems to parse `-jdbcUrl=jdbc:postgresql:database` correctly. So you can check for yourself if this kind of uri schema is neccesary.

I have some suggestions for future education issues:
- replace all the System.out.prints with a logger for better debugging
- a proper error handling with exceptions (maybe you have to touch the classes, which call the pgpass methos)
- check file permission for non-posix systems
- a refactoring of the whole class  (avoid class members, more JavaDoc ...)

**Comment by paulmillar** [comment]
@tomdittrich `URI.create` should be parsing `jdbc:postgresql:database`, not `-jdbcUrl=jdbc:postgresql:database`.  The latter is an option, which are (usually) parsed using the `Args` class.

**Comment by tomdittrich** [comment]
@paulmillar 
I know. My post is not correct but I used it in the right way within the code. For `URI.create` you have to eliminate the `jdbc:` part with `substring(5)`

I talked about it with @kofemann 
He said it's okay if we leave it how it is for now.

**Comment by tomdittrich** [comment]
@kofemann 
From my point of view, everything should be ready. There are no merge conflicts within the pull request too.
