### ISSUE TITLE
Billing to Kafka: what unit is meanReadBandwidth?

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4926]
Dear dCache devs,

While feeding billing events into Kafka, I noticed the `meanReadBandwidth` in the JSON below:

```
{
  "date": "2019-06-04T17:37:30.95+02:00",
  "msgType": "transfer",
  "transferTime": 24149,
  "cellName": "dolphin12_dteamrwtape",
  "session": "pool:dolphin12_dteamrwtape@dolphin12_dteamrwtapeDomain:1559662650950-2",
  "subject": [
    "GidPrincipal[31040]",
    "/DC=org/DC=terena/DC=tcs/C=NL/O=SURFsara B.V./CN=Onno Zweers onno.zweers@surfsara.nl",
    "EmailAddressPrincipal[onno.zweers@surfsara.nl]",
    "Origin[145.100.5.194]",
    "GidPrincipal[41385]",
    "UidPrincipal[36490]",
    "FQANPrincipal[/dteam/NGI_NL]",
    "GidPrincipal[31631,primary]",
    "GidPrincipal[40304]",
    "EntityDefinitionPrincipal[Person]",
    "GroupNamePrincipal[onno]",
    "GidPrincipal[44436]",
    "UserNamePrincipal[dteam]",
    "GroupNamePrincipal[dteam,primary]",
    "FQANPrincipal[/dteam,primary]",
    "LoAPrincipal[IGTF-AP:Classic]",
    "GidPrincipal[30013]"
  ],
  "initiator": "door:webdav2884-dolphin12@webdav2884-dolphin12Domain:AAWKgUDWYVg:1559662626774000",
  "transferPath": "/groups/dteam/readwritetest/onnotest100",
  "meanReadBandwidth": 2268359424.9688354,
  "version": "1.0",
  "storageInfo": "dteam:rwtape@osm",
  "readIdle": "PT23.522818388S",
  "transferSize": 1073741824,
  "protocolInfo": {
    "protocol": "Http",
    "port": 0,
    "host": "145.100.33.46",
    "versionMajor": 1,
    "versionMinor": 1
  },
  "cellType": "pool",
  "readActive": "PT0.614832398S",
  "fileSize": 1073741824,
  "queuingTime": 0,
  "cellDomain": "dolphin12_dteamrwtapeDomain",
  "isP2p": false,
  "pnfsid": "000024F63F9F49504EED96124906A2F4499C",
  "billingPath": "/groups/dteam/readwritetest/onnotest100",
  "isWrite": "read",
  "status": {
    "msg": "",
    "code": 0
  }
}
```

I copied a 1GB file in ~24 seconds. How can this have a bandwidth of 2268359424.9688354? In the billing.properties (https://github.com/dCache/dcache/blob/master/skel/share/defaults/billing.properties), it says the unit is MiB/s. But even if it were bytes/s, this would mean 2.2 GB/s, which would be way faster than it happened. The number could be somewhat accurate if it were bytes/minute, but that would be highly unusual.

So, what unit is it?

Cheers,
Onno

**Comment by paulmillar** [comment]
The units for meanReadBandwidth (and similarly for meanWriteBandwidth, if the transfer was an upload) is bytes per second (or "B/s").  The billing cell applies a scaling factor, so the billing files record these values in MiB/s.

To explain what is happening, each time the pool makes an IO request (for HTTP these are 8 KiB requests, by default), it checks how long the filesystem took to deliver the data.  Therefore, it can calculate an average (effective) bandwidth for that individual IO operation.  Over the course of the transfer, the pool keeps track of these instantaneous bandwidth measurements.  Once the transfer is complete, the pool calculates statistics for how the filesystem behaved, using these bandwidth measurements.  Once statistic is the average measured bandwidth, which is reported as `meanReadBandwidth`.

For single-threaded transfers (like HTTP) there is only a single IO request at a time, so this should give a reasonable measure of what performance the pool is getting from the filesystem, albeit one that includes the filesystem cache and that is only valid up to the precision of the Linux clock.

The other two numbers worth noting are `readIdle` and `readActive`.  These provide the time during the transfer where there are no on-going (no "in flight") IO requests and when there is at least one IO request, respectively.  Together, they should add up to the `transferTime` (sadly with the usual units confusion).

    0.614832398 s + 23.522818388 s = 24.137650786 s = 24138 ms

So the two measurements are only about 11ms out, which is accurate to some .05% of the transfer time, which isn't too bad :smile: 

This tells us that your transfer took some 24 seconds, but almost all of that time (~ 97%) was spend delivering data to the client; i.e., slow network, slow client or a combination of both.  The pool's filesystem was not the bottleneck, and could have delivered the data much faster.

**Comment by onnozweers** [comment]
Hi Paul,

Thanks for your very clear explanation! I hadn't realized `meanReadBandwidth` is about filesystem IO performance.

So, to get the mean transfer bandwidth, I would have to divide the `transferSize` by `transferTime`, is that correct?

I see there's also a `queuingTime` in there, is that the time that the mover has been in the queue? So, to get the bandwidth from the user point of view, perhaps I should use `transferSize / (transferTime + queuingTime)` ?

Cheers,
Onno

**Comment by paulmillar** [comment]
Yes. `transferSize / transferTime` should give a good estimate of the average bandwidth that the client sees.

As it happens, `queuingTime` is always zero for any direct transfer (probably should fix that).  The value is only non-zero for records sent by TransferManager (which kafka doesn't see) or for tape flush operations.

So you can calculate `transferSize / (transferTime + queuingTime)`, but (currently) the result will always be the same as just `transferSize / transferTime`.

`transferTime` is the time between the mover starting and the transfer completing.  It does not include the time the mover spend queued but it does include the time spent waiting for the client to connect.

**Comment by onnozweers** [comment]
Thanks Paul!
