### ISSUE TITLE
csm check * bug

### ISSUE THREAD

**Issue by cristinamanzano** [dCache/dcache#4927]
Hi,

when I am trying to cms check * a pool I get the following message:

Command 'csm check *' triggered a bug (java.lang.IllegalStateException: Still active); the service log file contains additional information. Please contact support@dcache.org.

In the pool log I see the following:

[pool.stacktrace.log](https://github.com/dCache/dcache/files/3256021/pool.stacktrace.log)

Could you please take a look here? I am running dCache 3.2.53

Thank you!

Cristina

**Comment by paulmillar** [comment]
Hi Cristina,

Thanks for reporting this.

The problem stems from attempting to start a full scan while an existing full scan is still active.  We'll update dCache so it doesn't log an exception in this case.

Cheers,
Paul.

**Comment by cristinamanzano** [comment]
Hi Paul,

thanks for the quick reply! I think I was too impatient, I started a scan but then as nothing happened I tried to start a second one and when I got the exception was not sure anymore something was running at all...

Cheers,
Cristina

**Comment by paulmillar** [comment]
You should be able to use the `csm status` command to discover the current status of checksum jobs.

**Comment by cristinamanzano** [comment]
Yes, thank you, I m seeing the status now with the command.
