### ISSUE TITLE
webdav.allowed.client.origins doesn't work

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4986]
Dear dCache devs,

I'm testing dCache View and wrestling with CORS. I've noticed that this configuration option does not seem to work in 6.0.0 snapshot:

```
webdav.allowed.client.origins = https://dolphin12.grid.surfsara.nl:20443
```

When I add this to a webdav door and restart it and use the web console to check the headers, I don't see the Access-Control-Allow-Origin header.

When I configure this:

```
webdav.custom-response-header!Access-Control-Allow-Origin = https://dolphin12.grid.surfsara.nl:20443
```

The header does show up.

Is this a bug?

(I still can't get CORS to work though, but I'll leave that for another time.)

Cheers,
Onno

**Comment by onnozweers** [comment]
I've tried to test this. With yesterday's snapshot, I can now upload and view files in dCache View, supported by a WebDAV door.

However, I still can't see the `Access-Control-Allow-Origin` header in the response headers of the WebDAV door at https://dolphin12.grid.surfsara.nl:443.

Here's my config:

```
[webdav443-${host.name}Domain]
[webdav443-${host.name}Domain/webdav]
webdav.cell.name=webdav443-${host.name}
webdav.redirect.on-read=true
webdav.redirect.on-write=true
webdav.authn.protocol=https
webdav.net.port=443
webdav.authn.basic=true
webdav.authn.accept-client-cert = false
# Allow dCache View to use this door
webdav.allowed.client.origins = https://dolphin12.grid.surfsara.nl:20443
```

When I add `webdav.custom-response-header!Access-Control-Allow-Origin = https://dolphin12.grid.surfsara.nl:20443`, I can see the header in the WebDAV door.

Am I doing something wrong?

Cheers,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno, 

You don't need to set `webdav.custom-response-header!Access-Control-Allow-Origin` this is done once your `webdav.allowed.client.origins` match the origin making the request to webdav.

Out of curiosity, I will like to test this out myself, may you please generate a username and password for me, so that I may have a look at the response header and the request. 

Best regards,
Olufemi

**Comment by onnozweers** [comment]
Hi Olufemi,

Ahhh, thanks for explaining. I checked and I can see these request headers when using the dCache View:

```
Host: dolphin12.grid.surfsara.nl:2881
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.7,nl;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,content-type,suppress-www-authenticate
Referer: https://dolphin12.grid.surfsara.nl:20443/scripts/tasks/download-task.js
Origin: https://dolphin12.grid.surfsara.nl:20443
DNT: 1
Connection: keep-alive
```

And the response:

```
HTTP/1.1 200 OK
Date: Thu, 25 Jul 2019 09:24:22 GMT
Server: dCache/6.0.0-SNAPSHOT
Access-Control-Allow-Origin: https://dolphin12.grid.surfsara.nl:20443
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Suppress-WWW-Authenticate
Access-Control-Allow-Credentials: true
Content-Length: 0
Request headers (561 B)	
Raw headers
Host: dolphin12.grid.surfsara.nl:2881
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.7,nl;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,content-type,suppress-www-authenticate
Referer: https://dolphin12.grid.surfsara.nl:20443/scripts/tasks/download-task.js
Origin: https://dolphin12.grid.surfsara.nl:20443
DNT: 1
Connection: keep-alive
```

I didn't realize the response headers are only used when triggered by certain request headers.

If you'd still like to test, the test account I recently created for you is still valid.

Thanks!
Kind regards,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno,

I'm glad it's all cleared up.

Best,
Olufemi
