### ISSUE TITLE
Document how to configure SRR

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#5041]
Our dCache admin guide ("The Book") does not describe how to configure dCache support for SRR.

The book should be updated to describe the script (`dcache-storage-descriptor`) along with the configuration properties that affect how it behaves.

The requirement on the info service should be document, along with the intention that the admin runs the script from a cron job.

Finally, the documentation should describe the options available to the admin on how the output from this file is uploaded into dCache; e.g., the script writing directly into an NFS mounted dCache, or the file is uploaded using a supported protocol (WebDAV, gridftp, xrootd, ...) and a supported authn scheme  (X.509, username+password, Kerberos, Macaroon, trusted-host, OIDC, ...)

**Comment by ajulia** [comment]
Hello,

Do we have final version which we can point to and progress with the deployment campaign?
Thank you

Julia

**Comment by paulmillar** [comment]
Femi's documentation: https://gist.github.com/femiadeyemi/4db7fc202ac589842c6d3865cfce4512

**Comment by paulmillar** [comment]
Ticket: https://rt.dcache.org/Ticket/Display.html?id=9745
