### ISSUE TITLE
make cleaner service replicable

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#5058]
As `cleaner` reads information form chimera db and removes entries in it, the operation of multiple cleanser in the system must be coordinated to avoid operation on the same set of files. Such coordination can be implemented as a distributed lock or leader election within zookeeper.

**Comment by paulmillar** [comment]
Just to mention, I believe the `cleaner` logic is safe against multiple cells operating on the same file.  Coordination between `cleaner` cells would prevent unnecessary messages being send to pools, requesting it delete replicas that no longer exist.  However, I don't believe there is any risk of dark data running multiple `cleaner` services concurrently.

Coordination is still beneficial, though, as it would allow load-balancing and fail-over without multiple cleaners battling it out over which one is responsible for cleaning up a particular file's replica.

Further, an alternative approach would be to use a rendezvous hash, like we do for staging requests (see `RendezvousPoolManagerHandler`); for example, by hashing the PNFS-ID and fully-qualified cleaner name.  That way, load may be spread over all cleaners and, if a cleaner cell goes down, only those files being handled by the no-longer-running cleaner are reassigned.

**Comment by XMol** [comment]
The linked support ticket in the dCache RT is #9731.

If you deem the implementation of the additional coordination too much of a hassle or too low priority, simply close the issues and we'll run two cleaner instances anyway. 😉 

Ciao,
Xavier.

**Comment by kofemann** [comment]
Solved  by  4ace8e1e16e9a209c4a1e3d878acbb1d24bb2dfa
