### ISSUE TITLE
[storage-descriptor] default URL does not work

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#5120]
The `dcache-storage-descriptor` script should work without the user specifying a URL on the command line.

We've had a report that it doesn't work:

> And one other comment about running the script: not giving a url to the
> script as a command line argument does not work. The default infoUrl is
> not set correctly as the $host and $port variables it replies on are
> only set after infoUrl is set if no url is given on the command line.

**Comment by femiadeyemi** [comment]
Closing this issue, [fix is committed](https://github.com/dCache/dcache/commit/ebe05a1aaa4e3569946f161264fa301e048e2eb5).
