### ISSUE TITLE
SciTokens broken, unexpected content-type

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5145]
Dear dCache devs,

I have tested SciTokens on our test instance two weeks ago and then it worked (on October 17). Now however I can't get it working; I only get 401 errors. In the gPlazma log I see this content-type error:

```
04 Nov 2019 13:24:05 (gPlazma) [webdav443-dolphin12 Login AUTH scitoken] Failed to fetch https://demo.scitokens.org/.well-known/openid-configuration: Unexpected Content-Type: application
04 Nov 2019 13:24:05 (gPlazma) [webdav443-dolphin12 Login AUTH scitoken] configuration does not have jwks_uri
04 Nov 2019 13:24:05 (gPlazma) [webdav443-dolphin12 Login AUTH scitoken] missing keys
04 Nov 2019 13:24:05 (gPlazma) [webdav443-dolphin12 Login] Login attempt failed; detailed explanation follows:
LOGIN FAIL
 |    in: Origin[145.100.5.194]
 |        BearerTokenCredential[bearerToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImtleS1yczI1NiJ9.eyJzY3AiOiJyZWFkOi9ncm91cHMvZHRlYW0vc2NpdG9rZW4tZGVtbyIsImlzcyI6Imh0dHBzOi8vZGVtby5zY2l0b2tlbnMub3JnIiwiZXhwIjoxNTcyODcwODI4LCJpYXQiOjE1NzI4NzAyMjgsIm5iZiI6MTU3Mjg3MDIyOCwianRpIjoiNTZlMDMwNmItOTdiZS00MTFkLWI3ODktNWU3ODQ5MjU2MzNkIn0.nDPiIlZtydMd71vBuKIKTqJwSSk7RbYUDFqksgC9IdbRPEL8GJi2rsMhvfdUaJ5NxifZ_vsMc5cy8pSDJc02soQ-HvPu1NT3Z3w34sVsns0Mnhf64F4hQUWTG3o0k1XVdeqG8S9ZkPecr85Pnkp_v90gbVYvBnCdf1CjBzLGbLi2aDCMSjoBP5i0UxWYGUXv1CTHV01I7vPwDccG9tR2IHtxnObf5UR3ShG-xQitLSCUgrD0y_d_reAotz7cCjufUSWuW0kVf6OCNGuW-8RKg5917i2yMQ8TUXuJN1fdAiQLyvl2ugAdM4WdBB0qHKUIjetIaszsnWb9kFJWjbTtHw]
 |   out: Origin[145.100.5.194]
 |
...
 |   +--scitoken OPTIONAL:FAIL (Unknown kid "key-rs256") => OK
```

I have upgraded dCache on the test server to the latest master last week; that may have something to do with it. It could also be a change in the demo.scitokens.org portal.

Any ideas?

Cheers,
Onno

**Comment by onnozweers** [comment]
I downgraded to the previous build, 6.1.0.5de5570. Then it worked. Then I upgraded to 6.1.0.9d3b029, and it was broken again (the exact same token and config).

**Comment by onnozweers** [comment]
It would be nice if in a case like this, the error would not be 401 (login failed) but something like 501 (internal server error). I don't know if this is easy to do.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/12017/

**Comment by paulmillar** [comment]
Thanks for doing the downgrade!  That helped pinpoint the problem very quickly.

I'm not sure what would cause the 500 Internal Server Error.  That sounds like a different problem.  Could you open a fresh issue for that?  Perhaps there's something logged in the webdav door's log file.

**Comment by onnozweers** [comment]
The 501/500 is a request, not a problem 😊

**Comment by paulmillar** [comment]
Ah, sorry.  I misunderstood :smile: 

Currently it's difficult to do, because we (currently) only consider gPlazma plugins as being successful or having failed.  We don't distinguish why a plugin failed.

I've created an issue for this:
https://github.com/dCache/dcache/issues/5146

**Comment by onnozweers** [comment]
Thanks! I would like to test, but #5149.
