### ISSUE TITLE
xrdcp client with adler32 check got CheckSum error when dual checksum configured on pool

### ISSUE THREAD

**Issue by janeliu-xj** [dCache/dcache#5147]
We found out one bug recently during xrootd tpc smoke testing.  The xrdcp client with adler32 check got CheckSum error when dual checksum was configured on DMZ pool on XROOTD door host.  In the setup for DMZ pool on XROOTD door host, we had this:
csm set checksumtype adler32 md5

We set it to calculate dual checksum because we need that feature.  It seems that this caused the problem. 

bash-4.1$  xrdcp -vvvv  -C adler32 -f /var/spool/dcache/storage-descriptor.json root://dcachetest04.usatlas.bnl.gov:1096//pnfs/usatlas.bnl.gov/data/space_report/storage-descriptor.json.999
[6.999kB/6.999kB][100%][==================================================][6.999kB/s] 
Run: [ERROR] CheckSum error

After we modified the line to only calculate adler32 and restarted the pool, it worked.
csm set checksumtype adler32

bash-4.1$  xrdcp -vvvv  -C adler32 -f /var/spool/dcache/storage-descriptor.json root://dcachetest04.usatlas.bnl.gov:1096//pnfs/usatlas.bnl.gov/data/space_report/storage-descriptor.json.1104.1
[6.999kB/6.999kB][100%][==================================================][6.999kB/s] 

It seems that xrdcp client was confused by dual checksum calculation in dCache.  This need to be fixed if we want both dual checksum feature and xrootd tpc feature.  

Thanks,
Jane

**Comment by alrossi** [comment]
Able to reproduce this easily.   dCache with one pool, set to adler32 md5

```
[arossi@otfrid Desktop]$ xrdcp410 -f -C adler32 /etc/fstab root://fndcatemp1:1094//pnfs/fs/usr/test/arossi/volatile/csmtest1
[574B/574B][100%][==================================================][574B/s]  
Run: [ERROR] CheckSum error
```

**Comment by alrossi** [comment]
And further: 

```
05 Nov 2019 11:32:54 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd0-fndcatemp1Domain:AAWWnNJ8HJg] [id: 0x4b1c66c2, L:/131.225.240.89:1094 - R:/131.225.80.252:40096] READ COMPLETE
05 Nov 2019 11:32:54 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd0-fndcatemp1Domain:AAWWnNJ8HJg] kXR_Qcksum query, got checksums: [2:ab2775cffbe7a3ee7cb29ae7b8843750, 1:f5b0a2dd].
05 Nov 2019 11:32:54 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd0-fndcatemp1Domain:AAWWnNJ8HJg] kXR_Qcksum query, requested type : None
05 Nov 2019 11:32:54 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd0-fndcatemp1Domain:AAWWnNJ8HJg] kXR_Qcksum query, no type requested, getting the first checksum 2:ab2775cffbe7a3ee7cb29ae7b8843750.
```

Looks like (unfortunately) a library parsing error.

**Comment by alrossi** [comment]
Fixes:

xrootd4j:  https://rb.dcache.org/r/12018/  -- will be backported to 3.5, 3.4 and 3.3.

dcache: https://rb.dcache.org/r/12019/ -- all supported stable branches
