### ISSUE TITLE
SciToken: missing scope claim

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5261]
Dear dCache devs,

Happy new year to you all!

I was testing SciTokens again, and now I have a different problem (latest snapshot 6.1.0.170a33f). I get a 401 authentication failure, and the gPlazma log says: "scitoken OPTIONAL:FAIL (missing scope claim)". I didn't see that one before.

My SciToken payload:

```
{
  "scp": "read:/groups/dteam",
  "iss": "https://demo.scitokens.org",
  "exp": 1578478669,
  "iat": 1578478069,
  "nbf": 1578478069,
  "jti": "2c30f701-4041-484e-8e30-0abaf539c011"
}
```

As you can see I have a `scp` statement, so I don't understand where this error message comes from.

This is not urgent for us, we have no short term plans to use SciTokens yet.

Kind regards
Onno

**Comment by paulmillar** [comment]
Hi Onno,

Happy New Year!

I believe the `scp` claim is the old (deprecated) name for the scope claim.  The new name for this claim is `scope`.

Currently dCache only accepts the `scope` claim and ignores the `scp` claim.  This is why it failed for this SciToken.

Do you know where this token came from -- which service generated it?

Cheers,
Paul.

**Comment by onnozweers** [comment]
Hi Paul,

Thanks!

For now I'm using https://demo.scitokens.org/ to generate SciTokens. I see that their docs at https://scitokens.org/technical_docs/Claims have been updated; the demo site has not.

Now that I know, I can update the payload manually. I will contact the site admins to let them know.

Kind regards,
Onno
