### ISSUE TITLE
API/SSE: subscribing to a path ignores the root: caveat from macaroon

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5318]
Dear dCache devs,

While testing events, I noticed that when I subscribe to inotify events for a path, I always have to specify the full path, even when I authenticate with a macaroon with a `root:` caveat.

So, my macaroon contains this:

```
cid home:/users/onno
cid root:/users/onno/
```

When I use the /namespace API call, I can specify `/disk` as a path and it will understand that I want `/users/onno/disk`.

When I use the API to subscribe to inotify events for that directory, specifying `{"path":"/disk"}` or `{"path":"disk"}` will fail with a "400 Bad Request". Instead, I have to specify the whole path: `{"path":"/users/onno/disk"}`.

This appears to be inconsistent. Or is there some logic to it that I overlooked?

Cheers,
Onno

**Comment by paulmillar** [comment]
Good catch!

No, this is definitely a bug, and something we should fix.

**Comment by natalieda** [comment]
Dear dCache team,

While testing the deletion of directories through the dCache API, I encountered the same error as described above. When I use a macaroon with `--chroot` option and I don't specify the full path, the delete operation succeeds but returns 403.  When I use a macaroon without `--chroot` and specify the full path (/pnfs/grid.sara.nl/data/users/...),  the delete operation succeeds without error.

Is there maybe any update on this bug resolution?

Many thanks!

Natalie

**Comment by paulmillar** [comment]
Hi Natalie,

There is a series of three patches to address the inotify issue (as you described when opening this issue).  These patches are currently under review.

In your latest message (2020-04-14), you mentioned an additional problem with deleting directories.  Unfortunately, I have been unable to reproduce this problem and (from looking at the code), any such problem is unrelated to this problem. 

Therefore, could you open a separate issue for the delete problem you describe above?

Cheers,
Paul.

Patch: https://rb.dcache.org/r/12316/
Patch: https://rb.dcache.org/r/12317/
Patch: https://rb.dcache.org/r/12318/

**Comment by natalieda** [comment]
> Hi Natalie,
> 
> There is a series of three patches to address the inotify issue (as you described when opening this issue). These patches are currently under review.
> 
> In your latest message (2020-04-14), you mentioned an additional problem with deleting directories. Unfortunately, I have been unable to reproduce this problem and (from looking at the code), any such problem is unrelated to this problem.
> 
> Therefore, could you open a separate issue for the delete problem you describe above?
> 
> Cheers,
> Paul.
> 
> Patch: https://rb.dcache.org/r/12316/
> Patch: https://rb.dcache.org/r/12317/
> Patch: https://rb.dcache.org/r/12318/

Hi Paul,

Sorry for the delay to my response. Due to some downtime on dCache I checked this late. It looks that I cannot reproduce the delete dir error now. If it occurs again I will open a new issue as you suggest.

Best regards,

Natalie

**Comment by paulmillar** [comment]
Thanks Natalie for checking and letting me know.

The fix for this "macaroon root caveat" problem should be available as part of dCache's next bug-fix release cycle, scheduled for next Tuesday (2020-05-05).  Please double-check the release notes to be sure.  Upgrading the node(s) hosting a frontend door is sufficient to fix this problem.
