### ISSUE TITLE
zookeeper client should recover from network outage

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#5356]
A local network interrupt is (hopefully) a rare occurrence; however, dCache should recover from such an interruption.

A dCache domain is a (single) ZK client.  After a network outage is resolved, the ZK client (a dCache domain) will reconnect to the ZK server(s) and attempts to continue with the same session.

If a domain was disconnected from the ZK server(s) for too long then the ZK server(s) will consider the client dead.  Part of the clean-up process involves removing/expiring that client's session.  Therefore, the domain will receive an error indicating that the session has expired.

Currently the only way to re-establish a valid ZK context is to restart the dCache domain.  This is potentially a high impact solution, since all activity in that domain is stopped and network connections are lost.  This is in contrast with regular dCache messaging, which will recover from a network outage without requiring the domain to be restarted.

dCache should recover from a ZK client session expiry without requiring the domain to be restarted.

**Comment by vokac** [comment]
Two dCache storage endpoints (out of ~ 30 operated by different sites) currently fails to provide macaroon

```bash
[vokac@ui1 ~]$ date
Mon Mar 23 17:21:47 CET 2020
[vokac@ui1 ~]$ curl --silent --cert /tmp/x509up_u$(id -u) --key /tmp/x509up_u$(id -u) --cacert /tmp/x509up_u$(id -u) --capath /etc/grid-security/certificates -X POST -H 'Content-Type: application/macaroon-request' -d '{"caveats": ["activity:DOWNLOAD"], "validity": "PT30M"}' https://dcache-atlas-webdav-job.desy.de:2880/pnfs/desy.de/atlas/dq2/atlasscratchdisk/1M
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Internal error: KeeperErrorCode = Session expired for /dcache/macaroons/secrets/2020-03-23T17:21:51.645Z</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /pnfs/desy.de/atlas/dq2/atlasscratchdisk/1M. Reason:
<pre>    Internal error: KeeperErrorCode = Session expired for /dcache/macaroons/secrets/2020-03-23T17:21:51.645Z</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.18.v20190429</a><hr/>

</body>
</html>
```
```bash
[vokac@ui1 ~]$ curl --silent --cert /tmp/x509up_u$(id -u) --key /tmp/x509up_u$(id -u) --cacert /tmp/x509up_u$(id -u) --capath /etc/grid-security/certificates -X POST -H 'Content-Type: application/macaroon-request' -d '{"caveats": ["activity:DOWNLOAD"], "validity": "PT30M"}' https://atlaswebdav-kit.gridka.de:2880/pnfs/gridka.de/atlas/disk-only/atlasscratchdisk/1M
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Internal error: KeeperErrorCode = Session expired for /dcache/macaroons/secrets/2020-03-23T17:21:58.229Z</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /pnfs/gridka.de/atlas/disk-only/atlasscratchdisk/1M. Reason:
<pre>    Internal error: KeeperErrorCode = Session expired for /dcache/macaroons/secrets/2020-03-23T17:21:58.229Z</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.18.v20190429</a><hr/>

</body>
</html>
[vokac@ui1 ~]$ date
Mon Mar 23 17:22:06 CET 2020
```

**Comment by kofemann** [comment]
it this not fixes by https://github.com/dCache/dcache/commit/7100e62a4c102f4c0a3f1b46da687ba0854e81e6?

**Comment by paulmillar** [comment]
@kofemann Yes, that could be, if dCache services are using the persistent node from curator (which, I believe is the case).

We should try to reproduce the problem with a post 7100e62 dCache.

**Comment by lemora** [comment]
The commit in question was added in version 5.2.14.

**Comment by paulmillar** [comment]
Just for reference, the patch Tigran mentioned was committed and back-ported.
The fix is available in:
**4.2.50** (or later),
**5.0.30** (or later),
**5.1.19** (or later),
**5.2.14** (or later),
**6.0.8** (or later).

dCache versions 6.1 and 6.2 are unaffected by this problem, as the fix was committed before those branches  were created.

So, @vokac if IN2P3-CC were to upgrade their WebDAV door to the latest bug-fix version then this problem could (should?) go away.

**Comment by vokac** [comment]
Thanks, IN2P3-CC already plan to upgrade in September. I was a bit confused by the fact this ticket is still open.

Also this issue was a bit hidden in our production infrastructure, because all our active TPC parties currently support gridsite delegation - transfers works even with failing macaroons. We are planning to include also SE without gridsite support soon (we'll need reliably working macaroons/tokens), so we have to ask 5 dCache sites to upgrade.

**Comment by kofemann** [comment]
I believe, this issue is solved. Closing.
