### ISSUE TITLE
frontend queries all attributes when stat()-ing a file or building directory listing

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#5366]
Currently frontend will query all attributes that dCache knows about.

This is despite the code requiring only a (proper) subset of all the FileAttribute values to build the JSON response.

This is bad for (at least) two reasons:
1. it isn't guaranteed that a NameSpaceProvider supports all FileAttribute.  If the unsupported attribute is ignored then selecting all attributes needlessly breaks frontend (see #5360)
2. In some cases, acquiring FileAttribute information about a file is expensive.  Acquiring information only to throw away that information makes the code needlessly slow.

**Comment by alrossi** [comment]
Actually, I noticed this some time ago and made a mental note to revisit it.   Now's as good a time as any ...

**Comment by alrossi** [comment]
See https://rb.dcache.org/r/12267/
