### ISSUE TITLE
Request: more detailed info about PnfsManager activity

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5462]
Dear dCache devs,

I have a request. We recently had some issues with very large directory listings that pushed other listings in the queue. We partly fixed this by increasing the number of dir listing threads from 2 (default) to 10. However, we still see queueing. 

I can't seem to find a way to find out who is causing this activity. It doesn't come in through the SRM. Dir listings are not logged in the billing files (and I wouldn't want that either). An `info [-a] [-l]` in the PnfsManager does not give any clues who is doing activity, or on which object. I don't want to set logging level to find out because our log partitions might fill up. Besides, log entries might not indicate who is putting a heavy load on the system. I tried querying pg_stat_activity but the results are anonymised.

Is there a way to see which user is currently doing PnfsManager operations like listings, and perhaps on which object? If not, could such an option be provided? With people moving away from SRM, it might be very useful.

Kind regards,
Onno

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/12451/
