### ISSUE TITLE
systemd service units have dependecy on zookeeper

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#5467]
The PR #3404 adds a `After` dependency to zookeeper.service for dcache systemd units. Though this is technically not an issue, however, logical such dependency makes no much sense. Only a small number of hosts will run zookeeper service parallel to dcache. IOW, zookeeper service expected to be almost always on a different host. Thus dependency `After` is confusing.

**Comment by kofemann** [comment]
@calestyo You are welcome to comment :)

**Comment by calestyo** [comment]
Well, I think you're right and one can drop the PR... especially dcache seems nowdays much more quiet when it cannot connect zookeeper, so there's really little to no benefit left... just the potential confusion.
