### ISSUE TITLE
systemd: dCache fails to start after machine reboots

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#5527]
I used `systemctl enable dcache.target`:

```
[root@prometheus ~]# systemctl status dcache.target
● dcache.target - dCache target to start/stop all dcache@*.service instances
   Loaded: loaded (/usr/lib/systemd/system/dcache.target; enabled; vendor preset: disabled)
   Active: active since Thu 2020-08-20 11:40:25 CEST; 1min 17s ago
[root@prometheus ~]# 
```

After rebooting the system, the `dcache.target` status claims it has status `active`, but no domains are running.

This seems to be because systemd doesn't seem to know of any dCache domains any more:

```
[root@prometheus ~]# systemctl status dcache@dCacheDomain
Unit dcache@dCacheDomain.service could not be found.
[root@prometheus ~]# 
```

Manually checking which java processes are running confirms that the dCache domains are really not started.

I guess this problem is because the generated units are store in `/run/systemd/generator` (e.g., `/run/systemd/generator/dcache@dCacheDomain.service`) and after rebooting, this directory is wiped.

The systemd generator should recreate the units on start-up, but apparently this is failing, perhaps because this happens "very early", (apparently) before `/var` is mounted, which might explain the failure.

**Comment by paulmillar** [comment]
A work-around:

```
systemctl daemon-reload
systemctl restart dcache.target
```

**Comment by paulmillar** [comment]
What I believe _might_ be going wrong is that, during the boot, the generator script is not running correctly.

systemd runs the generator scripts early during the boot process, when the system is not fully initialised.  It could be that, at this time, the dCache generator script doesn't work (for example, because the filesystem containing a dependency has not yet been mounted).  Since the script didn't work correctly, no unit files were written and dCache doesn't start.

The problem goes away once the system has fully started and the generator script is then able to generate the correct files.
This is why the work-around works.

**Comment by paulmillar** [comment]
Ah, thanks for the update @ahaupt.

The config cache is a work-around that parsing dCache configuration is slow, therefore, we cache the result.  Without this, we would need to run a java command each time the generator needs to resolve a dCache configuration property.

So, perhaps the quickest way to resolve this issue would be to update the generators so they use a temporary directory (`/tmp` for example) as the cache location, assuming that is available when the generators are run.  This should allow the generators to run with only a very modest increase in the system startup time.

Longer-term, I believe Tigran would like to move configuration of the runtime environment: the arguments to the `java` command (e.g., how much memory the domains have) outside of the regular dCache configuration properties.  Such a change should remove the need to build the cache of the dCache configuration, at least for the generators.

**Comment by thdesy** [comment]
@paulmillar @ahaupt AFAIS the current target of `/usr/lib/systemd/system/dcache.target` is `WantedBy=default.target`

would it work to attach the dcache.target to `WantedBy=multi-user.target` or so (should be pretty much at the end of the chain)

**Comment by thdesy** [comment]
alternatively/additionally, one could fore to run a generator script with `ExecStartPre` (the eactual exec should be started only on success AFAIK)

**Comment by ahaupt** [comment]
> would it work to attach the dcache.target to `WantedBy=multi-user.target` or so (should be pretty much at the end of the chain)

@thdesy @paulmillar No, it does not make any difference. The problem is not that the generator is not invoked (or too early). During boot time it is running in an environment that seems to disallow some statements it executes. Additionally it is virtually impossible to debug the generator at this time.

Therefore again the suggestion: As you need to execute at least ```systemctl daemon-reload``` every time you update the host's layout file, you can also invoke a different command that creates the systemd unit files in /etc/systemd/system. It is much less error-prone and admins who are familiar with Systemd can easily check what's going on.

**Comment by ahaupt** [comment]
@thdesy @paulmillar I found it! I let stdout & stderr get redirected into a log file in /run/systemd. Then I additionally added ```set -x``` to the generator:

```
exec > /run/systemd/dcache-generator.log 2>&1
set -x
```
Then this appears in the log file:

```
[trajan-vm2] /root # tail -n 3 /run/systemd/dcache-generator.log
+ JAVA_LIBRARY_PATH=/usr/lib/dcache
+ cat
/usr/lib/systemd/system-generators/dcache-generator: line 49: cannot create temp file for here-document: Read-only file system
```
The error comes from this line in the generator:
```
    cat <<-EOF > "$1/dcache@$domain.service"
```

**Comment by kofemann** [comment]
Please test this fix: https://rb.dcache.org/r/12984/

**Comment by ahaupt** [comment]
> Please test this fix: https://rb.dcache.org/r/12984/

Looks much better now! dCache services are started during boot now!
