### ISSUE TITLE
Pool fails to start if certificate path is not present 

### ISSUE THREAD

**Issue by lemora** [dCache/dcache#5605]
When attempting to run a dCache instance of version 6.2.7, pools fail to start and get caught in a retry-loop if the directory `/etc/grid-security/certificates/` does not exist. This was not previously required and seems to be related to the XRootD TPC component. Furthermore, this problem is communicated via a not very descriptive error message/stack trace:

`
dcache@os-dcache-head03_poolDomain[39422]: 28 Oct 2020 16:49:13 (pool03) [] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pool' defined in class path resource [org/dcache/pool/classic/pool.xml]: Cannot resolve reference to bean 'transfer-services' while setting bean property 'transferServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transfer-services' defined in class path resource [org/dcache/pool/classic/pool.xml]: Cannot resolve reference to bean 'xrootd-transfer-service' while setting bean property 'factories' with key [TypedStringValue: value [Xrootd-2], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xrootd-transfer-service' defined in class path resource [org/dcache/pool/classic/pool.xml]: Cannot create inner bean 'org.dcache.xrootd.spring.ChannelHandlerFactoryFactoryBean#6b55e9a5' of type [org.dcache.xrootd.spring.ChannelHandlerFactoryFactoryBean] while setting bean property 'tpcClientPlugins'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dcache.xrootd.spring.ChannelHandlerFactoryFactoryBean#6b55e9a5': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
`

Because not every dCache deployment can be expected to run on machines with host certificates, it would be nice if this problem could be avoided. It seems like the existence of such an empty directory already has the desired affect.

**Comment by alrossi** [comment]
Aha.  This is a consequence of https://rb.dcache.org/r/12605/

Before, gsi was not a default setting, so I guess we assumed that whoever was going to run the TPC client using X509 would know that the certificates directory had to be there.

We can certainly do what we did for the door.  I'll take care of it.

**Comment by alrossi** [comment]
Actually, no, it doesn't make sense for use to make gsi default and not require the certificates directory.

**Comment by paulmillar** [comment]
Maybe we should just revert that patch: at least, the part that adds the "gsi" as a default value.

This was intended to solve the problem where sites are unaware that they need to add `gsi` as a plugin.

However, it seems that making this the default is the wrong approach, and breaks sites that would otherwise be working.

An alternative approach would be to ship dCache without `gsi` as the default plugin, but to make sure that xroot-TPC transfers fail with a meaningful error message, pointing out that the `gsi` plugin isn't enabled on the pool.

**Comment by alrossi** [comment]
Whatever we do, we definitely need to keep unix in there as the default.  A number of tickets recently have encountered problems with TPC to EOS because it was not set.

I can provide a patch for the GSI change when I get back.

**Comment by kofemann** [comment]
@alrossi what about other way around - enable gsi if `/etc/grid-security/certificatesis` directory exist?

**Comment by calestyo** [comment]
Having my admin's hat on:
I think making a security related option (like gsi or not) dependent on something external is rather dangerous... it can easily trick into people believing they'd be "secure" while by accident they're not.

And - obviously not speaking for other sites - I personally don't mind if you make incompatible changes (in terms of options or so)... **as long** as they're properly mentioned in the release notes.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/12656/ 

Evidently this was not enough.

**Comment by svemeyer** [comment]
I discovered stacktraces today with version 7.2.2 that looks somehow similiar in webdav and frontend while the error message I got from pool was clearer. Maybe I should add, that I don't want to use GSI. Also it's not mentioned in installation chapter of the book that this directory is needed. Please tell me if I should add the whole stacktrace or send it to someone.


Error message from poolDomain:
```
Failure at startup: (666) URL [file:/usr/share/dcache/services/pool.batch]: line 133: (3) Failed to create bean 'pool' : /etc/grid-security/certificates is missing: GSI requires the X509 certificate authority CRLs
```

Error message from WebDav (looks similiar in Frontend):
```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jetty' defined in class path resource [org/dcache/webdav/webdav.xml]: Cannot resolve reference to bean 'server-connector' while setting bean property 'connectors' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server-connector': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
```

**Comment by alrossi** [comment]
Here is the situation.  Looking at Frontend.

The spring.xml injects a ConnectorFactoryBean:

```
<bean id="server-connector" class="org.dcache.util.jetty.ConnectorFactoryBean">
        <description>HTTPS connector supporting grid certificates</description>

        <property name="server" ref="jetty"/>

        <property name="host" value="#{ T(com.google.common.base.Strings).emptyToNull('${frontend.net.listen}') }"/>
        <property name="port" value="${frontend.net.port}"/>
        <property name="backlog" value="${frontend.limits.backlog}"/>
        <property name="idleTimeout" value="${frontend.limits.idle-time}"/>
        <property name="idleTimeoutUnit" value="${frontend.limits.idle-time.unit}"/>
        <property name="acceptors" value="${frontend.limits.acceptors}"/>

        <property name="protocol" value="${frontend.authn.connector}"/>

        <property name="wantClientAuth" value="${frontend.authn.accept-client-cert}"/>
        <property name="needClientAuth" value="${frontend.authn.require-client-cert}"/>
        <property name="excludedCipherSuites" ref="banned-ciphers"/>

        <property name="caPath" value="${frontend.authn.capath}"/>
        <property name="caPathTimeout" value="${frontend.authn.capath.refresh}"/>
        <property name="caPathTimeoutUnit" value="${frontend.authn.capath.refresh.unit}"/>

        <property name="serverCertificatePath" value="${frontend.authn.hostcert.cert}"/>
        <property name="serverKeyPath" value="${frontend.authn.hostcert.key}"/>
        <property name="serverCertificateTimeout" value="${frontend.authn.hostcert.refresh}"/>
        <property name="serverCertificateTimeoutUnit" value="${frontend.authn.hostcert.refresh.unit}"/>

        <property name="namespaceMode" value="${frontend.authn.namespace-mode}"/>
        <property name="crlCheckingMode" value="${frontend.authn.crl-mode}"/>
        <property name="ocspCheckingMode" value="${frontend.authn.ocsp-mode}"/>

        <property name="proxyConnectionEnabled" value="${frontend.enable.proxy-protocol}"/>
    </bean>
```

It is used by the Jetty Server.  I believe this needs to be there for SSL (host certificates).   I don't think you can support https without a location for the CAs.   

So the only thing I see to do is throw a FileNotFoundException the way the pool does.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/13253

**Comment by paulmillar** [comment]
Hi @svemeyer,

If you've discovered a problem with Frontend or WebDAV, please create a new issue.

I believe this issue is about pools not starting.

Cheers,
Paul.
