### ISSUE TITLE
Stack traces on pool startup

### ISSUE THREAD

**Issue by lemora** [dCache/dcache#5606]
When running pools of version 6.2.7, several stack traces are logged. They do not seem to affect the pool coming or staying up.

The stack traces are documented in the appended file:
[pool-startup-stacktraces.txt](https://github.com/dCache/dcache/files/5465185/pool-startup-stacktraces.txt)

**Comment by alrossi** [comment]
Looks like the second stack trace is benign but annoying.

https://stackoverflow.com/questions/57885828/netty-cannot-access-class-jdk-internal-misc-unsafe

maybe we need to add documentation to set the java options suggested there in the domain:

```
--add-opens java.base/jdk.internal.misc=ALL-UNNAMED
-Dio.netty.tryReflectionSetAccessible=true
```

??

**Comment by lemora** [comment]
Sounds reasonable to me, I have not found anything indicating that this option would negatively impact dCache. Or one could mention their occurrence somewhere along with the FST illegal reflective access warnings that were introduced at the same time?
