### ISSUE TITLE
WebDAV errors observed when executing several simultaneous PUT requests

### ISSUE THREAD

**Issue by airnandez** [dCache/dcache#5618]
Hello,

I would like to report some errors we are observing when uploading files to dCache using the WebDAV protocol. The problem occurs specifically when:

* the WebDAV door redirects the requests to the pools (when the client specifies the `Expect: 100-continue` header), and
* the number of simultaneous `PUT` requests goes beyond a threshold that in our configuration is about 30 requests

These are the versions we are running in our installation:

* dCache webDAV door: `dCache/5.2.33`
* dCache pools: `dCache/5.2.24`

The issue is easily reproducible using `curl` and here is an excerpt of the error messages we observe:

```
curl: (35) Encountered end of file
curl: (56) SSL peer reports incorrect Message Authentication Code.
curl: (35) Peer's certificate has an invalid signature.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) Encountered end of file
curl: (35) Encountered end of file
curl: (56) SSL peer reports incorrect Message Authentication Code.
curl: (35) SSL received a malformed Alert record.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL received a malformed Alert record.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) Encountered end of file
curl: (56) SSL peer reports incorrect Message Authentication Code.
curl: (35) Encountered end of file
curl: (56) SSL peer reports incorrect Message Authentication Code.
curl: (35) Encountered end of file
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL received a malformed Alert record.
curl: (35) SSL received a malformed Alert record.
curl: (56) SSL peer reports incorrecct Mesusarge Authentication Code.
```

You can find a shell script to reproduce the issue [here](https://gist.github.com/airnandez/ee641fb0fafc0b473d2fad9ff5d3e17b) together with the indications on how to run it.

In case it matters, we are using grid certificates (as opposed to bearer tokens) for authenticating to both the dCache WebDAV door and the pools.

@ageorget administers our dCache instance and could provide relevant details of our specific configuration, if needed.

cc: @bgounon

**Comment by airnandez** [comment]
Supplemental information. We also observe errors using simultaneous `GET` requests beyond a threshold. Here is an excerpt of the errors we observe when using 64 simultaneous requests:

```
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) Peer's certificate has an invalid signature.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) Encountered end of file
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) Encountered end of file
curl: (35) SSL peer was not expecting a handshake message it received.
curl: (35) SSL peer was not expecting a handshake message it received.
^C
```

The threshold for the errors appearing using `GET` seems to be higher than when using `PUT`.

We have looked at the configuration of our dCache instance for possible causes of this unexpected behavior without finding something obvious. Any guidance on where to look or how to debug this issue would be really appreciated.

**Comment by airnandez** [comment]
Today we performed the same tests after modifying the configuration of WebDAV door to be:

```
webdav.redirect.allow-https=false
```

and the configuration of all the pools to be

```
pool.enable.encrypted-transfers=false
```

and **we don't observe the issue** when using up to 64 simultaneous `PUT` or `GET` requests. 

We hope this helps.

**Comment by paulmillar** [comment]
Thanks for the update!

**Comment by paulmillar** [comment]
Could you try adding the `--tlsv1.2` option to curl and rerun the tests?

**Comment by paulmillar** [comment]
Could I give you an updated RPM to test?

**Comment by ageorget** [comment]
Hi @paulmillar ,
Yes sure, does it concern an update for the webdav door or pools?

**Comment by paulmillar** [comment]
You'll need to update the pools only.

Here's the RPM:

https://dcache-demo.desy.de:2443/Users/paul/Software/dcache-5.2.35.3ef68d6-1.noarch.rpm

For integrity, here's the MD5 checksum:
```
paul@sprocket:~$ md5sum dcache-5.2.35.3ef68d6-1.noarch.rpm 
b9b1661aa3057b6955ccf3f0fad3feb4  dcache-5.2.35.3ef68d6-1.noarch.rpm
paul@sprocket:~$ 
```

**IMPORTANT**: this package does NOT contain the fixes for the vulnerabilities announced yesterday.  Don't install on nodes running a dcap or ftp door, nor on a node running a PnfsManager.

**Comment by ageorget** [comment]
@paulmillar I'm not allowed to download the RPM, even if I use my GRID certificate (asking for a login/passwd).

BTW, we don't use dcap anymore at CCIN2P3. Only ftp doors are concerned (upgrade scheduled for the next site downtime on December 8th).

**Comment by paulmillar** [comment]
@ageorget The problem is your browser is presenting an X.509 cerificate, which does not correspond to an account on the system.

Just try with wget and it should work.

**Comment by ageorget** [comment]
Hmm a wget from our servers doesn't work (pending until timeout) but it works from my laptop.
Ok nevermind, I got it. Thanks!

**Comment by paulmillar** [comment]
@ageorget Thanks -- I'll look into these problems with downloading the file.  In the meantime, when do you think you might be able to install the updated RPM?

**Comment by ageorget** [comment]
@paulmillar I'm doing the upgrade right now.

**Comment by airnandez** [comment]
Hi @paulmillar,

thanks for this patch. After applying it to the pools we don't observe the reported errors, neither with `PUT` nor `GET` requests. We performed several tests with an increasing number of simultaneous requests (up to 96) without observing errors.

The bad news is that we observed that the upload throughput decreased substantially. We perform our tests using the same dedicated client host and the same set of 45k files. The plots below show the observed network throughput of the client host before applying the patch (i.e. the webDAV door redirects the `PUT` requests to the pools running `v5.2.24` using HTTP):

<img width="1348" alt="2020-11-22-BeforePatch" src="https://user-images.githubusercontent.com/813479/99966915-57b93800-2d97-11eb-8f36-ed13b7b9dded.png">

The figure below shows the observed throughput after applying the patch (the webDAV door redirects the `PUT` requests to the pools using **HTTPS**):

<img width="1348" alt="2020-11-23-AfterPatch-RedirectionHTTPS" src="https://user-images.githubusercontent.com/813479/99966982-7c151480-2d97-11eb-812a-693c3df5493f.png">

And finally, the figure below shows the observed throughput after applying the patch (the webDAV door redirects the `PUT` requests to the pools using **HTTP**):

<img width="1348" alt="2020-11-23-AfterPatch-RedirectionHTTP" src="https://user-images.githubusercontent.com/813479/99967028-8d5e2100-2d97-11eb-91ca-93614b452888.png">

As you can see, the difference in throughput is substantial and we cannot correlate it to other event, so we wonder if the modifications included in the applied patch could explain this behavior.

Please let us know if we can test anything else to help diagnosing this issue.

**Comment by paulmillar** [comment]
Hi @airnandez, @ageorget 

Thanks for the update.  It's certainly good news that the problem with the protocol is fixed.

Right now, I can't say for sure what might have caused the decrease in performance.

If possible, could you rerun the client activity (simultaneous transfers) and monitor the pool nodes to see whether it is the CPU or IO activity that is the limiting the pool's performance.  For example, running a command like `vmstat 2` should give CPU usage statistics.  It would be interesting to learn whether the CPU hits 100% (or perhaps 100% for a single thread) and, if so, whether that is 100% is spent mostly in user activty, system activity, or IO-wait.

**Comment by airnandez** [comment]
We performed another round of tests with the patch applied to the pools and the door configured for redirecting to the pools using HTTPS. Here are our results:

* we did not observe the errors that we reported when opening this issue, neither with `PUT` nor with `GET` requests
* we observed the expected throughput (about 1 GB/s) in all our tests (both `PUT` and `GET`)

For the record, the figure below shows the network throughput observed by the client host:

![2020-11-24-Throughput-Client](https://user-images.githubusercontent.com/813479/100116831-7f320280-2e74-11eb-9264-efbaff345a56.png)

Regarding the low throughput observed in the previous rounds of tests (and reported [here](https://github.com/dCache/dcache/issues/5618#issuecomment-732163159)), we suspect that it is related to some hardware issues appeared with the Postgres platform used by this dCache instance. The fix for those issues will be implemented in the coming days and we will have the opportunity to test again.

So to summarise, your patch seems to have effectively resolved the issue and we would like to thank you for your prompt intervention.

**Comment by paulmillar** [comment]
Hi @airnandez,

Thanks for the good news.

My suspicion would be that something on the pool was slowing down a very small number of transfers, which resulted in the long-tail you saw: perhaps competing IO activity, or some of the uploads hit a pool where the RAID system that was rebuilding, or ...  It could be a database issue, but then I would have expected to see a drop in the throughput and, later, the throughput to increase again.

However, it's fairly clear that the patch does _not_ (significantly) degrade performance, which is good.

I have a question: do you need this fix in a regular dCache release?

We're currently in an embargo period because of the security vulnerability, which makes releasing somewhat harder, but it may still be possible, if needed.

**Comment by airnandez** [comment]
> do you need this fix in a regular dCache release?

We do need this fix in our instance so that we can use dCache for our purposes. Since we already have the fix deployed I would think we could live in the current situation while waiting for the fix to be integrated in a future release, if that helps.

But I let @ageorget provide a definitive answer about the specifics of the deployment.

**Comment by ageorget** [comment]
We can stay in this situation, I only need to upgrade PnfsManager node to 5.2.35 in order to fix the security vulnerability on this instance.
Thank you Paul for you help with this issue!

**Comment by paulmillar** [comment]
OK.  I'll start the code-review process (which I don't anticipate will take long).  Once complete, the changes will then be included in the next bug-fix release.  Unless something urgent comes up, the next bug-fix releases will be after the embargo period has ended (on 2020-12-19).

Cheers,
Paul.
