### ISSUE TITLE
How to create pools in multiple hosts with resilience?

### ISSUE THREAD

**Issue by donggrame** [dCache/dcache#5621]
I created 2 pools in each machine and set up a resilience in one machine.

I put following in each host
[poolsDomain-${host.name}]
[poolsDomain-${host.name}/pool]
 pool.name=pool-${host.name}-1
 pool.path=/srv/dcache/pool-1
 pool.wait-for-files=${pool.path}/data

Error logs in Resilience is
2020/11/25 15:09:47 (00001499E95425BE477090E7EB5170D64267 REPLICA)(COPY ABORTED)(parent none, retried 0) CacheException: Migration task for 00001499E95425BE477090E7EB5170D64267 failed. Transfer to [**pool-ex1-1@local**] failed (org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:22080 [/127.0.0.1] failed: Connection refused (Connection refused)).

I think the resilience treats two pools are in the local which leading to mitigation a failure.
If I run the migration command on each pool it says the same thing.

I could not find any docs related to this.

**Comment by paulmillar** [comment]
So, the destination pool was unable to fetch (download) the data from the source pool.

From the look of the error message, the source pool told the destination pool that the file was available from `127.0.0.1` (the loop-back interface).

This is (clearly) wrong, as the loop-back interface is only accessible from programs running on the same machine (the one running the source pool).  Unless both pools are running on the same machine, this cannot work.

**Comment by donggrame** [comment]
I thought the resilience service is meant to be like managing replicas in pools on different machines if the pools are tagged with its hostname, but are you saying that it is not possible at all?

Or do i need to configure more options in pool/poolmanager/resilience services?

For the references, here are full configurations i have
On machine1
`dcache.enable.space-reservation = false

[centralDomain]
 dcache.broker.scheme = core
[centralDomain/zookeeper]
[centralDomain/admin]
[centralDomain/pnfsmanager]
 pnfsmanager.default-retention-policy = REPLICA
 pnfsmanager.default-access-latency = ONLINE

[centralDomain/cleaner]
[centralDomain/poolmanager]
[centralDomain/billing]
[centralDomain/gplazma]

[resilienceDomain]
[resilienceDomain/resilience]

[doorsDomain]
[doorsDomain/nfs]
 nfs.version = 4.1

[poolsDomain]
[poolsDomain/pool]
 pool.name=pool-${host.name}-1
 pool.path=/srv/dcache/pool-1
 pool.wait-for-files=${pool.path}/data
`

On machine2
`
dcache.zookeeper.connection = ex1.lxd:2181

[poolsDomain-${host.name}]
[poolsDomain-${host.name}/pool]
 pool.name=pool-${host.name}-1
 pool.path=/srv/dcache/pool-1
 pool.wait-for-files=${pool.path}/data `

And here are pool manager output
`

[ex1] (PoolManager@centralDomain) admin > psu ls link -a
default-link
 readPref  : 10
 cachePref : 10
 writePref : 10
 p2pPref   : -1
 section   : None
 linkGroup : None
 UGroups :
   any-protocol  (links=1;units=1)
   any-store  (links=1;units=1)
   world-net  (links=1;units=2)
 poolList  :
   default(links=1; pools=2; resilient=false)
resilient-link
 readPref  : 10
 cachePref : 10
 writePref : 10
 p2pPref   : 10
 section   : None
 linkGroup : None
 UGroups :
   resilient-units  (links=1;units=1)
 poolList  :
   resilient-group(links=1; pools=2; resilient=true)



[ex1] (PoolManager@centralDomain) admin > psu ls ugroup -a
any-protocol
 unitList :
   */*  (type=PROTOCOL;canonical=*/*;uGroups=1)
 linkList :
   default-link  (pref=10/10/-1/10;;ugroups=3;pools=1)
any-store
 unitList :
   *@*  (type=STORE;canonical=*@*;uGroups=1) (required=null; onlyOneCopyPer=[])
 linkList :
   default-link  (pref=10/10/-1/10;;ugroups=3;pools=1)
resilient-units
 unitList :
   test:resilient@osm  (type=STORE;canonical=test:resilient@osm;uGroups=1) (required=2; onlyOneCopyPer=[hostname])
 linkList :
   resilient-link  (pref=10/10/10/10;;ugroups=1;pools=1)
world-net
 unitList :
   0.0.0.0/0.0.0.0  (type=NET;canonical=0.0.0.0/0;uGroups=1)
   ::/0  (type=NET;canonical=::/0;uGroups=1)
 linkList :
   default-link  (pref=10/10/-1/10;;ugroups=3;pools=1)

[ex1] (PoolManager@centralDomain) admin > psu ls pgroup -a
default
 dynamic   = false
 resilient = false
 linkList :
   default-link  (pref=10/10/-1/10;;ugroups=3;pools=1)
 poolList :
   pool-ex1-1  (enabled=true;active=27;rdOnly=false;links=0;pgroups=2;hsm=[];mode=enabled)
   pool-ex2-1  (enabled=true;active=8;rdOnly=false;links=0;pgroups=2;hsm=[];mode=enabled)
resilient-group
 dynamic   = false
 resilient = true
 linkList :
   resilient-link  (pref=10/10/10/10;;ugroups=1;pools=1)
 poolList :
   pool-ex1-1  (enabled=true;active=27;rdOnly=false;links=0;pgroups=2;hsm=[];mode=enabled)
   pool-ex2-1  (enabled=true;active=8;rdOnly=false;links=0;pgroups=2;hsm=[];mode=enabled)
`

**Comment by donggrame** [comment]
This is caused by a file `/etc/hosts`.
If I delete a line containing loopback with its hostname and FQDN it works perfectly fine.
Tough, I do not understand why the source pool told that the file was `127.0.0.1`.
In `/etc/hosts`, there is also a valid external IP address for each host.

Anyway, thanks for the help and grea system!
