### ISSUE TITLE
Print of lifetime plot does not show Y-axis and X-acis labels are garbled

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#5628]
Fermilab user reported Print of lifetime plot does not show Y-axis and X-axis labels are garbled. Reported dCache version 5.2.

![lifetime](https://user-images.githubusercontent.com/2091655/101670633-06f14280-3a19-11eb-8f1b-4e0b4c0760b9.png)

Dmitry

**Comment by alrossi** [comment]
Combination of  
https://rb.dcache.org/r/12682/
and
https://rb.dcache.org/r/12684/

should fix this.

**Comment by alrossi** [comment]
The only solution is to remove this option.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/12708/
