### ISSUE TITLE
Canceled webdav transfers spamming transfermanagers log

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#5697]
Hi,

I found a lot a repetitive log messages in transfermanagers log file caused by canceled webdav TPC transfers. 
The only way to remove these messages is to restart the webdav door.

`01 Feb 2021 09:33:01 (RemoteTransferManager) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAW56IFr54g webdav-ccdcatli310 CancelTransfer] cannot find handler with id=1611783138446000 for CancelTransferMessage
01 Feb 2021 09:33:02 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbLGpg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718230000 for CancelTransferMessage
01 Feb 2021 09:33:02 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbFABg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786717830000 for CancelTransferMessage
01 Feb 2021 09:33:02 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbQqHg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718594000 for CancelTransferMessage
01 Feb 2021 09:33:06 (RemoteTransferManager) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAW56IFr54g webdav-ccdcatli310 CancelTransfer] cannot find handler with id=1611783138446000 for CancelTransferMessage
01 Feb 2021 09:33:07 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbQqHg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718594000 for CancelTransferMessage
01 Feb 2021 09:33:07 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbLGpg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718230000 for CancelTransferMessage
01 Feb 2021 09:33:07 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbFABg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786717830000 for CancelTransferMessage
01 Feb 2021 09:33:11 (RemoteTransferManager) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAW56IFr54g webdav-ccdcatli310 CancelTransfer] cannot find handler with id=1611783138446000 for CancelTransferMessage
01 Feb 2021 09:33:12 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbFABg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786717830000 for CancelTransferMessage
01 Feb 2021 09:33:12 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbLGpg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718230000 for CancelTransferMessage
01 Feb 2021 09:33:12 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbQqHg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718594000 for CancelTransferMessage
01 Feb 2021 09:33:16 (RemoteTransferManager) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAW56IFr54g webdav-ccdcatli310 CancelTransfer] cannot find handler with id=1611783138446000 for CancelTransferMessage
01 Feb 2021 09:33:17 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbFABg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786717830000 for CancelTransferMessage
01 Feb 2021 09:33:17 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbLGpg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718230000 for CancelTransferMessage
01 Feb 2021 09:33:17 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbQqHg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718594000 for CancelTransferMessage
01 Feb 2021 09:33:21 (RemoteTransferManager) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAW56IFr54g webdav-ccdcatli310 CancelTransfer] cannot find handler with id=1611783138446000 for CancelTransferMessage
01 Feb 2021 09:33:22 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbLGpg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718230000 for CancelTransferMessage
01 Feb 2021 09:33:22 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbFABg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786717830000 for CancelTransferMessage
01 Feb 2021 09:33:22 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbQqHg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718594000 for CancelTransferMessage
01 Feb 2021 09:33:26 (RemoteTransferManager) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAW56IFr54g webdav-ccdcatli310 CancelTransfer] cannot find handler with id=1611783138446000 for CancelTransferMessage
01 Feb 2021 09:33:27 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbFABg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786717830000 for CancelTransferMessage
01 Feb 2021 09:33:27 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbQqHg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718594000 for CancelTransferMessage
01 Feb 2021 09:33:27 (RemoteTransferManager) [door:webdav-ccdcatli267@webdav-ccdcatli267Domain:AAW56VbLGpg webdav-ccdcatli267 CancelTransfer] cannot find handler with id=1611786718230000 for CancelTransferMessage
`

Can you check this please?
Cheers,
Adrien

**Comment by paulmillar** [comment]
Hi Adrien,

Could you check which version of dCache is running on the WebDAV door and the transfermanager service?

Cheers,
Paul.

**Comment by paulmillar** [comment]
Do you know when this problem started?  Could that time correspond to a restart of any dCache nodes, or some networking problem?

**Comment by ageorget** [comment]
We're running dCache 5.2.35.
And yes you right, it happened after I restarted srmDomain (srm+srmmanager+transfermanagers)

**Comment by paulmillar** [comment]
Perfect -- that explains it.

The quick fix is to restart the WebDAV door.  That should stop those messages for now.

I'll write a patch so you can restart srmDomain without getting these message loops.

**Comment by ageorget** [comment]
Yes restarting the webdav door fixed it, that's what I tried.
Thanks for fixing this!
