### ISSUE TITLE
frontend/api: readers and writers always zero

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5870]
Hi all,

I'm running something like this to collect pool mover info:

```
curl ... -X GET https://dcacheview.grid.surfsara.nl:22881/api/v1/poolgroups/atlas_writediskpools/queues \
| jq -r '.costDataForPools | .[] | .extendedMoverHash.gridftp_queue'
```
I get something like this:
```
{
  "name": "gridftp_queue",
  "active": 2,
  "maxActive": 24,
  "queued": 0,
  "readers": 0,
  "writers": 0
}
{
  "name": "gridftp_queue",
  "active": 0,
  "maxActive": 24,
  "queued": 0,
  "readers": 0,
  "writers": 0
}
{
  "name": "gridftp_queue",
  "active": 1,
  "maxActive": 24,
  "queued": 0,
  "readers": 0,
  "writers": 0
}
...
```
I would expect that readers + writers = active, but this is clearly not the case. Is my understanding incorrect, or is there a bug that prevents values for readers & writers to be passed on?

Kind regards,
Onno

**Comment by alrossi** [comment]
Hi Onno,

I am wondering too whether this has ever worked.   Investigating and will get back.

Al

**Comment by alrossi** [comment]
Onno,

a quick check from production here at Fermi.  Here is the beginning of read-write pool group data:

```{
  "costDataForPools": {
    "rw-stkendca1801-1": {
      "label": "Pool Cost Info",
      "mover": {
        "active": 14,
        "maxActive": 3730,
        "queued": 0,
        "readers": 0,
        "writers": 0
      },
      "store": {
        "active": 40,
        "maxActive": 0,
        "queued": 69,
        "readers": 0,
        "writers": 109
      },
      "restore": {
        "active": 40,
        "maxActive": 0,
        "queued": 150,
        "readers": 0,
        "writers": 190
      },
```

It looks like readers and writers are both active and queued.

The base code which populates named queues (from the Pool class):

```
private static PoolCostInfo.NamedPoolQueueInfo toNamedPoolQueueInfo(MoverRequestScheduler queue)
    {
        return new PoolCostInfo.NamedPoolQueueInfo(queue.getName(),
                                                   queue.getActiveJobs(),
                                                   queue.getMaxActiveJobs(),
                                                   queue.getQueueSize(),
                                                   queue.getCountByPriority(IoPriority.REGULAR),
                                                   queue.getCountByPriority(IoPriority.HIGH));
    }

```

The last two parameters are readers and writers respectively, which evidently correspond to regular and high priority transfers, respectively.

That being said, it seems that this number is susceptible to a kind of race when there are no queued transfers ... whether it picks up the active or not.   Not sure why exactly this is the case.  So that may be a small bug.

I will continue to investigate.

Al

**Comment by alrossi** [comment]
And, in fact, for the actual extended/named pools in this group:

```
"extendedMoverHash": {
        "DCap": {
          "name": "DCap",
          "active": 0,
          "maxActive": 100,
          "queued": 0,
          "readers": 0,
          "writers": 0
        },
        "FTP": {
          "name": "FTP",
          "active": 0,
          "maxActive": 30,
          "queued": 0,
          "readers": 0,
          "writers": 0
        },
        "XRootD": {
          "name": "XRootD",
          "active": 13,
          "maxActive": 1500,
          "queued": 0,
          "readers": 0,
          "writers": 0
        },
        "NFS": {
          "name": "NFS",
          "active": 0,
          "maxActive": 1000,
          "queued": 0,
          "readers": 0,
          "writers": 0
        },
        "HTTP": {
          "name": "HTTP",
          "active": 1,
          "maxActive": 1000,
          "queued": 0,
          "readers": 0,
          "writers": 0
        },
        "regular": {
          "name": "regular",
          "active": 0,
          "maxActive": 100,
          "queued": 0,
          "readers": 0,
          "writers": 0
        }
      },
```

Something similar.   When queued = 0, the numbers seem to be 0.

**Comment by alrossi** [comment]
There is an inconsistency in what readers and writers means.

For the store and restore queues, it is = active+queued
For named queues, it is only queued.

This explains the mystery of why we see:
```
"store": {
        "active": 40,
        "maxActive": 0,
        "queued": 69,
        "readers": 0,
        "writers": 109
      },
      "restore": {
        "active": 40,
        "maxActive": 0,
        "queued": 150,
        "readers": 0,
        "writers": 190
      },
```

but for movers, and named queues, active > 1 but readers, writers = 0.   In the latter case, there was no queueing.  
Readers+writers for the named queues should add up to queued.  This is not the case for stored/restored.  Also, for stored/restored, readers is always 0.

I don't know why it was decide to report the numbers this way.   It is fairly easy to make the named queue readers and writers also reflect active + queued, though, if that makes it a little more consistent.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/13009/

**Comment by onnozweers** [comment]
Thanks Al! 🎉🎂
