### ISSUE TITLE
CORS doesn't seem to work

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5883]
Dear dCache devs,

I'm trying to get CORS to work in dCache 6.0.37. For this, I am experimenting with webdav.allowed.client.origins.

My config:
```
[webdav2880-${host.name}Domain]
dcache.java.options.extra = -Djdk.tls.ephemeralDHKeySize=2048
[webdav2880-${host.name}Domain/webdav]
webdav.cell.name=webdav2880-${host.name}
webdav.redirect.on-read=true
webdav.redirect.on-write=true
webdav.redirect.allow-https=true
webdav.authn.basic=true
webdav.authn.accept-client-cert = false
webdav.authn.protocol=https
webdav.net.port=2880
webdav.enable.overwrite=true
webdav.allowed.client.origins = https://dcacheview.grid.surfsara.nl:22880
webdav.loginbroker.tags=webdav2880
```
Then from the dCacheView at https://dcacheview.grid.surfsara.nl:22880 I try to download or display a file. In the Chrome console, I can see this fail with twice this error:

`Access to fetch at 'https://dcacheview.grid.surfsara.nl:2880/pnfs/grid.sara.nl/data/users/onno/disk/bloemen.jpg' from origin 'https://dcacheview.grid.surfsara.nl:22880' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

The console seems to show two requests listed in the console:

```
Request URL: https://dcacheview.grid.surfsara.nl:2880/pnfs/grid.sara.nl/data/users/onno/disk/bloemen.jpg
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
authorization: Basic **********************
content-type: image/jpeg
Referer: https://dcacheview.grid.surfsara.nl:22880/
suppress-www-authenticate: Suppress
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
```
I decoded the "authorization: Basic" value and it seems to be correct (username:password).

And the second:
```
OPTIONS /pnfs/grid.sara.nl/data/users/onno/disk/bloemen.jpg HTTP/1.1
Host: dcacheview.grid.surfsara.nl:2880
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,content-type,suppress-www-authenticate
Origin: https://dcacheview.grid.surfsara.nl:22880
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: https://dcacheview.grid.surfsara.nl:22880/
Accept-Encoding: gzip, deflate, br
Accept-Language: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7

HTTP/1.1 401 login failed
Date: Fri, 30 Apr 2021 14:07:15 GMT
Server: dCache/6.0.37
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Allow: GET, PUT, POST, DELETE
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Suppress-WWW-Authenticate
WWW-Authenticate: Basic realm=""
Content-Length: 0
```
What surprises me is the `Access-Control-Allow-Origin: *`; I don't know what it's doing there when I've set webdav.allowed.client.origins. But then, my understanding of CORS is limited.

In Firefox, it doesn't work either. I can't get it to work. Any ideas?

**Comment by paulmillar** [comment]
Thanks for reporting this -- CORS requests are supposed to work without any authentication, so this is a clear bug.

**Comment by paulmillar** [comment]
Thanks for reporting this -- CORS requests are supposed to work without any authentication, so this is a clear bug.

I have a possible solution for this issue -- would you be able to test it?

**Comment by onnozweers** [comment]
Hi Paul, sure, I'll be happy to test. Just tell me how.

**Comment by paulmillar** [comment]
I can build a custom version of dCache that contains the proposed fix.  Which version of dCache would be easiest for you to test?

**Comment by onnozweers** [comment]
If you can provide an RPM that I can replace our current 6.0.37 with, that would be easiest. Otherwise I can take it to our test server and I can build a custom branch there, but I'd need to check first whether I can reproduce the problem there.

**Comment by paulmillar** [comment]
Incidentally, redirection is also (separately) broken -- again it's with CORS, but this time the problem is with the pool's response.

I'm trying to decide how best to fix this.  Without going into the horrible details, I have a hack that allows redirection to work, but isn't the best solution.  Normally, I'd just fix it properly, but it involves JavaScript, so might take a while to get it "right".

**Comment by paulmillar** [comment]
I'm uploaded an updated 6.0.37 here:

https://desycloud.desy.de/index.php/s/SqpLmP82YbTLWcE

The upload is amazingly slow, but should be finished by 17:30 CEST.

The file is `dcache-6.0.38.8d52b37-1.noarch.rpm`.  This is 6.0.37 plus the fix that should allow transfers to work with dCacheView, albeit only if the transfer is proxied.  Redirected transfers are broken for a separate reason (see dcache-view/issues#254).  You should only need to update the node(s) hosting a WebDAV door.

Please be aware that this code hasn't been through code-review -- treat with caution!

**Comment by onnozweers** [comment]
CORS works now in Firefox and Chrome! I had to start a fresh session in a private window. Uploading, downloading and the preview functions work.

![image](https://user-images.githubusercontent.com/781694/116897244-5557e580-ac35-11eb-9ab9-a138a3c61003.png)

**Comment by onnozweers** [comment]
Tested also our X509 dCacheView on https://dcacheview.grid.surfsara.nl:22884/, which uses non-redirecting WebDAV door https://dcacheview.grid.surfsara.nl:2884/ which has also X509 authentication. 
In Firefox that doesn't work.
In Chrome, it works, but at the first view or download, Chrome asks for the user certificate again. Is that supposed to happen?

**Comment by onnozweers** [comment]
I tested also with macaroon authentication; that seems to work properly.

**Comment by paulmillar** [comment]
Onno, could you also open a fresh issue for the X.509-base authentication problems?
