### ISSUE TITLE
GridFTP failing with TLS v1.3

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#5939]
GridCF [recently announced](https://mailman.egi.eu/pipermail/discuss/2021-May/000399.html) that future versions of GCT (Grid Community Toolkit) will support TLS v1.3.

@fscheiner was able to test this with dCache, and found that transfers are failing when TLS v1.3 was used.  This sounds similar to #5213.  Frank reported that (he believes) GCT is linked against OpenSSL (rather than libnss), which points to the problem here being dCache.

I've copied his report here:

<hr>

when checking my credentials, I did a `globus-url-copy -dbg -list [...]` against "prometheus.desy.org" with:

* `MAX_TLS_PROTOCOL=0` in `/etc/grid-security/gsi.conf` which means up to TLS v1.3 can be used and this didn't work for me:

```
[johndoe@gridftp-5 ~]$ globus-url-copy -dbg -list gsiftp://prometheus.desy.de/~/
gsiftp://prometheus.desy.de/~/
debug: starting to feat gsiftp://prometheus.desy.de/~/
debug: connecting to gsiftp://prometheus.desy.de/~/
debug: response from gsiftp://prometheus.desy.de/~/:
220 GSI FTP door ready

debug: authenticating with gsiftp://prometheus.desy.de/~/
debug: fault on connection to gsiftp://prometheus.desy.de/~/: globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed to generate output token

debug: operation complete


error: globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed to generate output token
```

* `MAX_TLS_PROTOCOL=TLS1_2_VERSION` and this worked for me:

```
[johndoe@gridftp-5 ~]$ globus-url-copy -dbg -list gsiftp://prometheus.desy.de/~/
gsiftp://prometheus.desy.de/~/
debug: starting to feat gsiftp://prometheus.desy.de/~/
debug: connecting to gsiftp://prometheus.desy.de/~/
debug: response from gsiftp://prometheus.desy.de/~/:
220 GSI FTP door ready

debug: authenticating with gsiftp://prometheus.desy.de/~/
debug: response from gsiftp://prometheus.desy.de/~/:
200 PASS command successful

debug: sending command to gsiftp://prometheus.desy.de/~/:
SITE HELP

debug: response from gsiftp://prometheus.desy.de/~/:
214-The following site-specific commands are supported:
SITE <SP> HELP - Information about SITE commands
SITE <SP> BUFSIZE <SP> <size> - Set network buffer to <size>
SITE <SP> CHKSUM <SP> <value> - Fail upload if ADLER32 checksum isn't <value>
SITE <SP> CHGRP <SP> <group> <SP> <path> - Change group-owner of <path> to group <group>
SITE <SP> CHMOD <SP> <perm> <SP> <path> - Change permission of <path> to octal value <perm>
SITE <SP> CLIENTINFO <SP> <id> - Provide server with information about the client
SITE <SP> SYMLINK <SP> <dest> <SP> <path> - Register symlink at <path>, pointing to <dest>
SITE <SP> SYMLINKFROM <SP> <path> - Register symlink location; SYMLINKTO must follow
SITE <SP> SYMLINKTO <SP> <path> - Create symlink to <path>; SYMLINKFROM must be earlier command
SITE <SP> TASKID <SP> <id> - Provide server with an identifier
SITE <SP> USAGE <SP> [TOKEN <SP> <token> <SP> ] <path>
214 SITE <SP> WHOAMI - Provides the username or uid of the user

debug: sending command to gsiftp://prometheus.desy.de/~/:
FEAT

debug: response from gsiftp://prometheus.desy.de/~/:
211-OK
 EOF
 PARALLEL
 MODE-E-PERF
 SIZE
 SBUF
 ERET
 ESTO
 GETPUT
 MDTM
 CKSUM ADLER32,MD5,MD4
 MODEX
 TVFS
 MFMT
 MFCT
 MFF Modify;Create;UNIX.mode;
 PASV AllowDelayed
 MLSC
 MLST Size*;Modify*;Create;Type*;Unique*;Perm*;UNIX.owner*;UNIX.group*;UNIX.uid*;UNIX.gid*;UNIX.mode*;UNIX.ctime;UNIX.atime;
211 End

debug: sending command to gsiftp://prometheus.desy.de/~/:
SITE CLIENTINFO scheme=gsiftp;appname="globus-url-copy";appver="10.8 (gcc64, 1607703417-0) [Grid Community Toolkit 6.2]";
debug: response from gsiftp://prometheus.desy.de/~/:
250 OK

debug: operation complete
debug: starting to machine list gsiftp://prometheus.desy.de/~/
debug: sending command to gsiftp://prometheus.desy.de/~/:
TYPE I
debug: response from gsiftp://prometheus.desy.de/~/:
200 Type set to I

debug: sending command to gsiftp://prometheus.desy.de/~/:
PASV

debug: response from gsiftp://prometheus.desy.de/~/:
227 OK (131,169,5,149,80,123)

debug: sending command to gsiftp://prometheus.desy.de/~/:
MLSD ~/

debug: response from gsiftp://prometheus.desy.de/~/:
150 Ready to accept ASCII mode data connection

debug: reading into data buffer 0x7f004691b010, maximum length 262144
debug: data callback, no error, buffer 0x7f004691b010, length 720, offset=0, eof=true
debug: response from gsiftp://prometheus.desy.de/~/:
226 MLSD completed for 4 files

debug: operation complete
    Private/
    Tape/
    public-file
    private-file

```
For both tries `MIN_TLS_PROTOCOL` was always set to `0` which means TLS v1.2 since August 2018.

**Comment by paulmillar** [comment]
Just to add, I was able to reproduce the problem using gct built from the `master` branch.

Here is a demonstration of the problem, using prometheus:
```
paul@sprocket:~$ globus-url-copy -list gsiftp://prometheus.desy.de/
gsiftp://prometheus.desy.de/


error: globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed to generate output token

paul@sprocket:~$ 
```

Here is the work-around, where the TLS is limited to v1.2:
```
paul@sprocket:~$ GLOBUS_GSSAPI_MAX_TLS_PROTOCOL=TLS1_2_VERSION globus-url-copy -list gsiftp://prometheus.desy.de/
gsiftp://prometheus.desy.de/
    lost+found/
    Demos/
    VOs/
    Users/
    UTF-8/
    Music/
    Video/
    upload/
    storage-descriptor.json 

paul@sprocket:~$ 
```

Just for reference, `globus-url-copy` self-identifies itself as v10.8:
```
paul@sprocket:~$ globus-url-copy -version
globus-url-copy: 10.8
paul@sprocket:~$ 
```

**Comment by paulmillar** [comment]
Some analysis has shown that the problem appears to come from some bad interactions at the TLS 1.3 protocol level.

The TLS v1.3 handshake completes successfully.  Once this happens, dCache sends a session ticket:

```
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.516 CEST|SSLEngineInputRecord.java:177|Raw read (
  0000: 17 03 03 00 45 34 0A 5F   2E DE A3 10 A8 32 F7 6A  ....E4._.....2.j
  0010: 0A 47 2F 26 37 DB 34 A4   C9 00 9C F4 CA 1F D7 DF  .G/&7.4.........
  0020: F2 9F 28 6C 26 F6 04 B3   8C 6F 94 B8 98 BB 7C 20  ..(l&....o..... 
  0030: A9 F3 BE 7D 62 AF 55 3C   22 28 AD F3 10 B8 50 BA  ....b.U<"(....P.
  0040: 21 52 BB 80 12 76 66 28   05 99                    !R...vf(..
)
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.516 CEST|SSLEngineInputRecord.java:214|READ: TLSv1.2 application_data, length = 69
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.516 CEST|SSLCipher.java:1931|Plaintext after DECRYPTION (
  0000: 14 00 00 30 6B D2 F7 02   24 CF 46 1F 78 2A 3D 62  ...0k...$.F.x*=b
  0010: 50 B7 AA EF CD 0C 4B D7   3A 2B 3B CA E5 2C 31 CB  P.....K.:+;..,1.
  0020: 9B 18 BB 93 8B FB 99 9B   22 11 08 57 90 B4 80 E8  ........"..W....
  0030: BB 87 2A 7C                                        ..*.
)
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.517 CEST|Finished.java:1032|Consuming client Finished handshake message (
"Finished": {
  "verify data": {
    0000: 6B D2 F7 02 24 CF 46 1F   78 2A 3D 62 50 B7 AA EF  k...$.F.x*=bP...
    0010: CD 0C 4B D7 3A 2B 3B CA   E5 2C 31 CB 9B 18 BB 93  ..K.:+;..,1.....
    0020: 8B FB 99 9B 22 11 08 57   90 B4 80 E8 BB 87 2A 7C  ...."..W......*.
  }'}
)
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.519 CEST|SSLCipher.java:1840|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.520 CEST|Finished.java:1131|Sending new session ticket
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.521 CEST|NewSessionTicket.java:255|Produced NewSessionTicket handshake message (
"NewSessionTicket": {
  "ticket_lifetime"      : "86,400",
  "ticket_age_add"       : "<omitted>",
  "ticket_nonce"         : "01",
  "ticket"               : "73 4D 4F 68 E2 9C 93 C3 35 26 15 C8 8A 0A F8 78 4D CB 8F 80 31 B8 70 87 1D 93 ED F0 A9 AA AB ED",
  "extensions"           : [
    <no extension>
  ]
}
)
javax.net.ssl|ALL|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.521 CEST|SSLSessionImpl.java:242|Session initialized:  Session(1622695023252|TLS_AES_256_GCM_SHA384)
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.521 CEST|SSLEngineOutputRecord.java:505|WRITE: TLS13 handshake, length = 50
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.521 CEST|SSLCipher.java:2036|Plaintext before ENCRYPTION (
  0000: 04 00 00 2E 00 01 51 80   3F 22 13 84 01 01 00 20  ......Q.?"..... 
  0010: 73 4D 4F 68 E2 9C 93 C3   35 26 15 C8 8A 0A F8 78  sMOh....5&.....x
  0020: 4D CB 8F 80 31 B8 70 87   1D 93 ED F0 A9 AA AB ED  M...1.p.........
  0030: 00 00 16 00 00 00 00 00   00 00 00 00 00 00 00 00  ................
  0040: 00 00 00                                           ...
)
javax.net.ssl|DEBUG|02 D3|GFTP-sprocket-0|2021-06-03 06:37:03.522 CEST|SSLEngineOutputRecord.java:523|Raw write (
  0000: 17 03 03 00 53 27 77 A4   9A F8 6A 9D 4B CC 71 5D  ....S'w...j.K.q]
  0010: 5F 00 5C B3 58 BE 23 27   80 DE 40 9D B9 AA 10 7D  _.\.X.#'..@.....
  0020: 17 A1 7C C4 2E 47 1F 48   4E 8E E8 C4 B5 61 83 26  .....G.HN....a.&
  0030: B6 7C CB 6B 43 D8 71 D6   E0 3E 58 2E 17 DD C2 9A  ...kC.q..>X.....
  0040: F5 3A E3 03 AA 8B 30 B3   E2 82 02 1E 4F 2E 62 DD  .:....0.....O.b.
  0050: C9 E7 DE 03 00 8F 14 94                            ........
)
```

The session ticket is (apparently) sent correctly; however, there is no (expected) response from the client.

```
level=INFO ts=2021-06-03T13:25:19.148+0200 event=org.dcache.ftp.hello session=door:GFTP-sprocket-AAXD2tSCQBA@dCacheDomain socket.remote=127.0.0.1:47366 socket.local=127.0.0.1:2811 reply="220 GSI FTP door ready"
level=INFO ts=2021-06-03T13:25:19.151+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2tSCQBA@dCacheDomain command="AUTH GSSAPI" reply="334 ADAT must follow"
level=INFO ts=2021-06-03T13:25:19.191+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2tSCQBA@dCacheDomain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-06-03T13:25:19.212+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2tSCQBA@dCacheDomain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-06-03T13:25:19.221+0200 event=org.dcache.ftp.disconnect host.remote=127.0.0.1:47366 session=door:GFTP-sprocket-AAXD2tSCQBA@dCacheDomain
```

In TLS v1.3, the message is just consumed by the client.

It appears that the error message `gss_init_sec_context failed to generate output token` comes about because the client is expecting that is must reply to each request from the server.

From [gridftp/control/source/globus_ftp_control_client.c:](https://github.com/gridcf/gct/blob/master/gridftp/control/source/globus_ftp_control_client.c#L3037), handing an `ADAT` response:

```
            maj_stat = gss_init_sec_context(
                &min_stat,
    [...]
                &send_tok,
                NULL,
                NULL);
    [...]
            len = send_tok.length;

            if(len != 0)
            {
    [...]
            }
            else
            {
                error_obj = globus_error_construct_string(
                    GLOBUS_FTP_CONTROL_MODULE,
                    GLOBUS_NULL,
                    _FCSL("globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed to generate output token\n"));
                goto return_error;
            }
```

**Comment by paulmillar** [comment]
For comparison, here is how dCache responds when `GLOBUS_GSSAPI_MAX_TLS_PROTOCOL=TLS1_2_VERSION` is used to limit the TLS version to 1.2:

```
level=INFO ts=2021-06-03T13:37:11.192+0200 event=org.dcache.ftp.hello session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain socket.remote=127.0.0.1:47600 socket.local=127.0.0.1:2811 reply="220 GSI FTP door ready"
level=INFO ts=2021-06-03T13:37:11.194+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain command="AUTH GSSAPI" reply="334 ADAT must follow"
level=INFO ts=2021-06-03T13:37:11.235+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-06-03T13:37:11.278+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-06-03T13:37:11.583+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-06-03T13:37:11.608+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain command="ADAT ..." reply="235 OK"
level=INFO ts=2021-06-03T13:37:11.754+0200 event=org.dcache.ftp.response session=door:GFTP-sprocket-AAXD2v7zJiA@dCacheDomain command="ENC{USER :globus-mapping:}" user.dn="/C=DE/O=GermanGrid/OU=DESY/CN=Alexander Paul Millar" user.mapped=1000:1000,0 reply="ENC{200 User :globus-mapping: logged in}"
[...]
```

**Comment by fscheiner** [comment]
CCing to @matyasselmeci, @ellert, @msalle so they are also in the loop.

@paulmillar:
Is the handling of session tickets different between TLS v1.2 and v1.3, assuming that `globus-url-copy` expects to reply to each server request when using TLS v1.2, too?

I'll also test what happens when a TLS v1.3 enabled `globus-url-copy` downloads files from a TLS v1.3 enabled web server and create a packet dump for comparison with existing dumps.

**Comment by paulmillar** [comment]
Thanks @fscheiner for including the others.

Protocol-wise, session tickets are different between TLS v1.2 and v1.3.  I'm not sufficiently informed about 1.3 to be able to say exactly what those differences are.

dCache didn't (and doesn't) do anything special to support session tickets.  The TLS implementation in OpenJDK supports them out-of-the-box, at least, for v1.3, so (during the handshake) it's sending back a session ticket.

GSI extends TLS in order to support delegation.  It does this in a rather horrible way.  To support this, dCache has a custom wrapper around Java's standard TLS engine.  My suspicion is that it's this wrapper that is (somehow) TLSv1.2-specific and causing the problem.

I haven't been able to confirm this, though.

Would it be possible to capture the network traffic between the TLS1.3-capable globus-url-copy and a TLS1.3-capable server?  Looking at a successful TLS v1.3 handshake might give me a hint at what is going wrong.

Broadly speaking, what's happening is dCache sends back what would be (for a normal TLS handshake) the final handshake message: (the server finish message) and a session ticket.  dCache base64-encodes the message and replies with an intermediate response code, indicating it is expecting the client to send more data.  AFAIK, this is correct, as globus-url-copy should send back either a '0' or a 'D' to indicate whether delegation should take place.  This is the GSI extension to support delegation.

In the client, it receives the token and passes it to the GSS engine.  Because dCache replied with an intermediate code, the globus-url-copy code then asks the GSS engine for the token to send to dCache.  However, because the TLS handshake has finished, the client has no further token to send to the server.  This triggers the error message.

For me, this is quite puzzling because I would expect the same behaviour for TLS 1.2.  dCache replies with the Server Done message, encoded using an intermediate  FTP response code; however, in that case, the client replies with either `0` or `D`, depending on whether delegation should take place.

Cheers,
Paul.

**Comment by msalle** [comment]
I don't really know anything about TLS1.3 vs 1.2 but perhaps https://wiki.openssl.org/index.php/TLS1.3 could be of use?
In particular the 4th bullet under [Differences_with_TLS1.2_and_below](https://wiki.openssl.org/index.php/TLS1.3#Differences_with_TLS1.2_and_below):

> Sessions are not established until after the main handshake has been completed. There may be a gap between the end of the handshake and the establishment of a session (or, in theory, a session may not be established at all). This could have impacts on session resumption code.

**Comment by ellert** [comment]
With the following patch:
```patch
diff --git a/gsi/gssapi/source/library/init_sec_context.c b/gsi/gssapi/source/library/init_sec_context.c
index 07ae97f2bb..cb7ed2d08e 100644
--- a/gsi/gssapi/source/library/init_sec_context.c
+++ b/gsi/gssapi/source/library/init_sec_context.c
@@ -202,6 +202,10 @@ GSS_CALLCONV gss_init_sec_context(
             *ret_flags = 0 ;
         }
     }
+    else if (context->gss_state == GSS_CON_ST_TOKEN1 &&
+             input_token->length == 0) {
+        context->gss_state = GSS_CON_ST_FLAGS;
+    }
     else
     {
         /* first time there is no input token, but after that
```
I get something sensible.
```
$ GLOBUS_GSSAPI_MAX_TLS_PROTOCOL=TLS1_3_VERSION GLOBUS_GSSAPI_DEBUG_LEVEL=2 LD_LIBRARY_PATH=./globus_gssapi_gsi-14.14/library/.libs globus-url-copy -list gsiftp://prometheus.desy.de/~/
Disabling SSLv2 and SSLv3.
acquire_cred: MICV2 MECH OID
gsiftp://prometheus.desy.de/~/
Creating context w/ GSS_C_NO_CREDENTIAL.
init_sec_context: no mech_type requested; using MICV2 MECH OID
Disabling SSLv2 and SSLv3.
acquire_cred: MICV2 MECH OID
Ciphers available:
init_sec_context:major_status:00000001:gss_state:0 req_flags=00001013:ret_flags=00000000
SSL handshake finished
Using TLSv1.3.
cred_usage=1
Cipher being used:
TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
X509 subject after proxy : /C=DE/O=GermanGrid/OU=DESY/CN=prometheus.desy.de
Comparing names:
Name 1 is of type GLOBUS_GSS_C_NT_X509:
Name 2 is of type GLOBUS_GSS_C_NT_HOST_IP:
Compared 1 
init_sec_context:major_status:00000001:gss_state:1 req_flags=00001013:ret_flags=000000ff
init_sec_context:major_status:00000001:gss_state:4 req_flags=00001013:ret_flags=000000ff
init_sec_context:major_status:00000000:gss_state:6 req_flags=00001013:ret_flags=000000ff
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
gss_wrap conf_req_flag=0 qop_req=0
    Private/
    Tape/
    private-file 
    public-file 
    DATA/
    SCRATCH/

gss_wrap conf_req_flag=0 qop_req=0
```

**Comment by paulmillar** [comment]
Thanks for the update @ellert ,

If I've understood correctly, `context->gss_state == GSS_CON_ST_TOKEN1` means the client has received enough material that it believes the TLS handshake is complete and is now waiting for the server to send session tokens.

Currently, this code looks kinda dodgy: it currently seems to require the server to send two session tokens.  The RFC is clear that this is optional: the server might not send any session token.  Indeed, the Java code may be configured so it doesn't send any session token after a TLS v1.3 handshake is complete.

It's also odd that it is expecting two session tickets: AFAIK, the Java implementation of TLS v1.3 sends only one session ticket.

Again, if I've understood correctly, the patch allows for the possibility that the server doesn't send any session ticket after the TLS handshake completes.  If so, this is a good idea (more in keeping with my understanding of the RFC)

However, that leaves me further confused.  I'm pretty sure that dCache is sending a (single) session ticket.  So why does the client believe it hasn't received any?

I'm concerned that there is some other problem here and the patch is merely masking it.

**Comment by ellert** [comment]
Comparing a connection to a GCT gridftp server and a dcache gridftp server.

The lists below are from the client's perspective, i.e. output tokens are sent to the server, input tokens are received from the server.

**dcache:**

output token: length = 406
input token: length = 9750
output token: length = 10009
output token: length = 23
input token: length = 843
output token: length = 1088
output token: length = 45

**GCT:**

output token: length = 397
input token: length = 2538              ← This one is smaller than the one above
output token: length = 10009
input token: length = 9854              ← This one is not in the list above
output token: length = 23                ← Request delegation
input token: length = 689                ← Proxy cert request
output token: length = 1089            ← Sign proxy
output token: length = 45                ← Application data "USER :globus-mapping:"

The input token in the GCT case that is missing in the dcache case contains the two session tokens 2 × (5 + 4922) bytes, with 5 bytes for the SSL token headers.

There is an option in openssl to disable the tokens (SSL_OP_NO_TICKET). However this option does not make the server not send any tokens, but it makes the tokens as small as possible while still complying with the protocol and sends 158 bytes instead 2 × (5 + 74). These minimal-size tokens are non-functional and can not be used to re-establish a connection. The implementers of the openssl library interprets the TLSv1.3 protocol as sending 2 session tokens is mandatory, and asking for it to be disabled just makes the tokens smaller (and non-functional).

In the dcache case the first token sent from the server is larger than in the GCT case, though it contains fewer SSL tokens.

**dcache:**
input token: length = 9750
              value  = 
0000 - **16 03 03 00 7a** 02 00 00-76 03 03 c4 e1 7c 9e 4f   ....z...v....|.O
[..]
0070 - 20 a2 51 87 51 10 09 b6-13 00 2b 00 02 03 04 **14**    .Q.Q.....+.....
0080 - **03 03 00 01** 01 **17 03 03-25 8c** 2d e8 12 a9 62 8d   ........%.-...b.
[..]
2610 - e5 a7 a6 39 1c e9                                 ...9..

[dcache-gfs.log](https://github.com/dCache/dcache/files/6662134/dcache-gfs.log)

**GCT:**
input token: length = 2538
              value  = 
0000 - **16 03 03 00 7a** 02 00 00-76 03 03 d6 ef 07 fb c6   ....z...v.......
[..]
0070 - 72 15 a9 13 e4 48 d2 d2-62 45 9d 32 bf 4d 6e **14**   r....H..bE.2.Mn.
0080 - **03 03 00 01** 01 **17 03 03-00 17** e2 23 af be 0b 66   ...........#...f
0090 - 2f 20 65 98 fa d0 4d 88-14 d3 39 45 53 0a 60 a6   / e...M...9ES.`.
00a0 - ff **17 03 03 00 42** 59 ba-e3 dc c7 78 a0 1f 43 81   .....BY....x..C.
[..]
00e0 - fe d0 58 50 c5 4e 46 35-**17 03 03 07 95** 41 0c 65   ..XP.NF5.....A.e
[..]
0880 - 54 82 **17 03 03 01 19** f6-f4 7c 32 46 73 fe c5 ea   T........|2Fs...
[..]
09a0 - **17 03 03 00 45** dc 6c 7e-33 7c 9e 08 15 e5 b8 fe   ....E.l~3|......
[..]
09e0 - a4 6f b3 40 08 d4 67 b7-da 95                     .o.@..g...

[globus-gfs.log](https://github.com/dCache/dcache/files/6662135/globus-gfs.log)

**Comment by fscheiner** [comment]
@paulmillar:
> It's also odd that it is expecting two session tickets: AFAIK, the Java implementation of TLS v1.3 sends only one session ticket.

@ellert:
> The input token in the GCT case that is missing in the dcache case contains the two session tokens 2 × (5 + 4922) bytes, with 5 bytes for the SSL token headers.
> 
> There is an option in openssl to disable the tokens (SSL_OP_NO_TICKET). However this option does not make the server not send any tokens, but it makes the tokens as small as possible while still complying with the protocol and sends 158 bytes instead 2 × (5 + 74). These minimal-size tokens are non-functional and can not be used to re-establish a connection. The implementers of the openssl library interprets the TLSv1.3 protocol as sending 2 session tokens is mandatory, and asking for it to be disabled just makes the tokens smaller (and non-functional).
> 
> In the dcache case the first token sent from the server is larger than in the GCT case, though it contains fewer SSL tokens.

From this, to me it sounds like the TLS v1.3 implementations of OpenSSL (2 mandatory session tokens) and Java (1 session token by default?) are somewhat incompatible in regard to session tokens and that this could be the actual reason for GCT failing against dCache when doing TLS v1.3. So @ellert's [fix](https://github.com/gridcf/gct/pull/155) would actually make the GCT compatible with the Java implementation of TLS v1.3.

It would be interesting to see, how a GridFTP client based on JGlobus behaves against dCache when using TLS v1.3 - if JGlobus can do that. Assuming that both would use the same TLS v1.3 implementation they should just work together.

**Comment by msalle** [comment]
Unless there is some other JGlobus fork that I'm not aware of, I very much doubt it supports anything newer than TLS1.2. See e.g. https://github.com/ellert/JGlobus/blob/master/gss/src/main/java/org/globus/gsi/gssapi/GlobusGSSContextImpl.java#L1295
And I'm pretty sure it's pretty dead.
The [canl-java library](https://github.com/eu-emi/canl-java) - used by e.g. VOMS and CREAM and actually possibly also by dCache itself  - probably has more chance of supporting it, possibly via Java itself.

**Comment by paulmillar** [comment]
@msalle from memory, the COG/JGlobus codebase used their own (embedded) TLS library.  Unless someone updates this dependency, I would strongly suspect it doesn't support TLS 1.3.  (and yes, JGlobus is dead).

One of the design goals of canl-java was to use and "fit in with" Java's built-in crypt frameworks (JCE/JCA, JSSE, etc), rather than using a specific implementation.  IIRC, it has an explicit bouncy castle dependency, but only to access functionality missing from the standard frameworks.

**Comment by paulmillar** [comment]
@fscheiner Would you be able to check whether @ellert 's commit resolves the problem you found?

**Comment by fscheiner** [comment]
@paulmillar 
> @fscheiner Would you be able to check whether @ellert 's commit resolves the problem you found?

Already did that during [my review](https://github.com/gridcf/gct/pull/155#pullrequestreview-710927716) In July (I actually referenced this issue here there, but maybe that doesn't work as expected (1) in a review comment or (2) for a repo out of the gridcf organization): it indeed solves the problem for me. :+1:

**Comment by fscheiner** [comment]
Indeed, also no reference viewable here for [my recent comment](https://github.com/gridcf/gct/pull/155#issuecomment-904028967). :-/

**Comment by paulmillar** [comment]
OK, thanks for the confirmation (and sorry for missing your earlier comments).

I think we can close this issue, now.  If others report a similar problem, we can open a fresh issue and reference this issue (if appropriate).

**Comment by fscheiner** [comment]
> OK, thanks for the confirmation (and sorry for missing your earlier comments).
 No need for sorries, I just assumed those references would work cross-project/organization, but they don't (maybe because of spam hazard). :-)
