### ISSUE TITLE
Feature request: have dcache.net.listen listen to dual stack

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5943]
Dear dCache devs,

I recently set this value, to prevent dCache to hand out TURLs with internal iDrac addresses:
```
dcache.net.listen = ${host.name}.grid.surfsara.nl
```

While this seemed to work at first, now it turns out it makes dCache bind only to IPv4 and not to IPv6, though the DNS name resolves to IPv4 and IPv6:

```
onno$ host shark4.grid.surfsara.nl
shark4.grid.surfsara.nl has address 145.100.33.122
shark4.grid.surfsara.nl has IPv6 address 2001:610:108:203a::1:122
```

So it seems at the moment, we have only two choices: 
* don't use dcache.net.listen, and have dCache listen to all interfaces and all addresses, including weird internal ones that result in broken TURLs;
* use dcache.net.listen, and make a choice between IPv4 and IPv6.

The second option is very limiting, considering WLCG has dual stack as a requirement for storage systems.

IN2P3 has a workaround to have pairs of duplicate doors, one of which listens to IPv4 and the other to IPv6. Though this is very creative, it is hardly elegant.

What we would like is for dcache.net.listen to be a bit more flexible, by any of these:
* bind to all addresses that the hostname resolves to and not just one
* allow more than one address 
  `dcache.net.listen = <hostname_for_turls> <IPv4> <IPv6>`
* bind to an interface instead of an address
  `dcache.net.listen = bond0`

Would this be possible?

If this is not at all possible, then an option to blacklist IPv4/IPv6 address ranges from TURLs would solve our problem too.

https://ggus.eu/index.php?mode=ticket_info&ticket_id=152363
https://ggus.eu/index.php?mode=ticket_info&ticket_id=152211

Kind regards,
Onno

**Comment by maswan** [comment]
When you fix this, could you please consider applying a similar fix for `pp interface` as well? While the impact is smaller, it was not the expected behavior to just have a hostname resolve into a single v4 or v6 address in there. Or only being able to explicitly add one of them.

**Comment by kofemann** [comment]
Unfortunately, this sounds simpler that the reality is. The limitation comes from OS socket implementation, that accepts only a single endpoint: **ANY**, **LOCALHOST** or "IP". Thus, to support multiple IP addresses we need to maintain multiple sockets, binds, listeners and so on. 

The natural solution will be if you could start multiple doors and enforce listen to the desired IP:

```
[doorDomain]

[doorDomain/ftp]
ftp.net.listen=a.b.c.d
ftp.cell.name=gridftp-${ftp.net.listen}

[doorDomain/ftp]
ftp.net.listen=a:b:c:d:e:f:g:h:i:j:k:l:m:n
ftp.cell.name=gridftp-${ftp.net.listen}
```

Eventually, there might be an easier or automatic way of doing this.

**Comment by onnozweers** [comment]
Hi Tigran,

I understand that it's difficult. But how about this?

> If this is not at all possible, then an option to blacklist IPv4/IPv6 address ranges from TURLs would solve our problem too.

If that is possible, we can prevent invalid addresses to be used in TURLs. We would not need dcache.net.listen.

**Comment by paulmillar** [comment]
Hi Onno,

I think you want the `*.loginbroker.address` family of configuration properties (e.g., `webdav.loginbroker.address`, `ftp.loginbroker.address`).  These properties describe what address the door should use to describe itself to clients.  The srmmanager service will use the door's loginbroker.address when building the TURL.  The value is also exposed elsewhere; e.g., frontend's list of available doors.

The default value for these values is the corresponding `net.listen` property; in `defaults/webdav.properties`:

    webdav.loginbroker.address = ${webdav.net.listen}

The `webdav.net.listen` configuration property takes the "gobal" value as a default:

    webdav.net.listen = ${dcache.net.listen}

So, by specifying `dcache.net.listen` you are also (by default) adjusting `webdav.loginbroker.address` (and `ftp.loginbroker.address`, ...).

The `*.net.listen` property is about binding a door to a specific interface.  If you don't want to do this, but a machine has multiple (DNS) names and you want to control which name is exposed to the client then `*.loginbroker.address` is your friend.

HTH,
Paul.

**Comment by onnozweers** [comment]
Hi Paul,

Thanks, that looks very promising. Don't know how I overlooked it. I'll check it out.

Cheers,
Onno

**Comment by onnozweers** [comment]
Thanks Paul,

That was exactly what we needed. We ditched `dcache.net.listen` and set these values:

```
ftp.loginbroker.address = ${host.name}.grid.surfsara.nl
webdav.loginbroker.address = ${host.name}.grid.surfsara.nl
xrootd.loginbroker.address = ${host.name}.grid.surfsara.nl
```

Now the doors listen to all addresses but we get TURLs with (external) hostnames. I'll close this ticket.

Thanks so much!

Cheers,
Onno
