### ISSUE TITLE
debian package suggests obsolete python-psycopg2

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#5956]
Hey.

The Debian `dcache` package suggests `python-psycopg2` which is obsolete in the upcoming (end of this month) new stable Debian.

Python2 is generally EOL and any code depending on it potentially vulnerable (because Python2 itself no longer being security supported) and should therefore be removed or adapted to Python3.

IIRC, there was recently a post on the user-forum where someone provided patches for just that.

Cheers,
Chris.

**Comment by paulmillar** [comment]
Thanks for reporting this @calestyo.  I've created some tickets to manage the transition to supporting Python v3.

**Comment by calestyo** [comment]
At least the 8.2.11-1 version of the Debian package seems to recommend `python3-psycopg2`, so I guess this has been fixed?

Thus closing.
