### ISSUE TITLE
WebDAV door behaves strange with symlinks

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#6032]
Dear dCache devs,

We are setting up an anonymous download WebDAV door for our user group Tropomi (a Dutch & British Copernicus earth observation project). The door is at https://tropomi.grid.surfsara.nl/.

Now, I thought to be smart and created a few symlinks to the directories they want to share, so they wouldn't need to copy or move data around. However, it appears the combination of WebDAV & symlinks behaves a bit strange.

1. There is a symlink `onno` to another dir, but when I click that link (https://tropomi.grid.surfsara.nl/onno?action=show), the images in the target dir can't be viewed, probably because they have a double `action=show` in their URL. When I don't follow that link but go to https://tropomi.grid.surfsara.nl/onno instead, the problem does not exist and I can view the images.
2. In front of the symlink there is an icon indicating "this item is currently not available".
3. The symlinks are appended with a "download" (cloud) icon, which does not make sense, because they point to directories and not to files. Clicking on the download icon will download a listing of the target directory, instead of showing the directory in the browser.

Here's an NFS view to the same directory:

```
[root@db1 ~]# ls -la /pnfs/grid.sara.nl/data/projects.nl/tropomi/public
total 3
drwxr-xr-x 5 tropomi tropomi 512 Aug 24 17:18 .
drwxr-xr-x 9 tropomi tropomi 512 Aug 24 16:14 ..
lrwxrwxrwx 1 root    root     24 Aug 24 17:16 hdo -> ../s5p/output_2/hdo/10/3
lrwxrwxrwx 1 root    root      7 Aug 24 16:19 onno -> ../onno
-rw-r--r-- 1 tropomi tropomi  13 Aug 24 17:18 README.txt
```

Would you consider symlinks implemented and tested well enough in dCache to use for this purpose?

Kind regards,
Onno

**Comment by onnozweers** [comment]
I noticed the patch will be backported to 6.2. We're running 6.0. Can we run a WebDAV v6.2 door in combination with v6.0 on our pools and head nodes?

**Comment by paulmillar** [comment]
Sure, no problem :-)

**Comment by onnozweers** [comment]
Thanks!

**Comment by onnozweers** [comment]
I can't find the fix in last Friday's release notes, and it doesn't seem to be in 6.0.44. When do you expect the fix to be released?

**Comment by paulmillar** [comment]
Sorry, committing and back-porting got held up.  The patch has now been committed and should be part of the next bug-fix release.
