### ISSUE TITLE
chimera: hard-linked directories cannot be deleted

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#6075]
The `JdbcFs` implementation of `FileSystemProvider` supports creating hard links on directories: however, once created, such directories cannot be deleted.

An `rmdir` command fails with `Directory is not empty` error message.

**Comment by kofemann** [comment]
I  think we should make it POSIX compliant and disallow hardlinks on directories

**Comment by paulmillar** [comment]
I agree.

I think there's nothing that forces us to disallow hard links (the `ln` command has a `-d` option).  There is (AFAIK) no compelling reason to support it, and doing so causes trouble (based on existing assumptions in the code-base).  See #6076 for a somewhat similar problem.
