### ISSUE TITLE
Scitoken "user" mapping vs. multimap&omnisession "username"

### ISSUE THREAD

**Issue by vokac** [dCache/dcache#6105]
It seems to me there is a small inconsistency in username configuration between scitoken configuration which use "user"

https://github.com/dCache/dcache/blob/91821cbe4989ec6243af853fcc9dbbb407cc7c1c/skel/share/defaults/gplazma.properties#L507-L517

processed with

https://github.com/dCache/dcache/blob/91821cbe4989ec6243af853fcc9dbbb407cc7c1c/modules/common/src/main/java/org/dcache/auth/Subjects.java#L482-L484

while multimap and omnisession use different string

https://github.com/dCache/dcache/blob/91821cbe4989ec6243af853fcc9dbbb407cc7c1c/modules/gplazma2-omnisession/src/main/java/org/dcache/gplazma/omnisession/PrincipalPredicates.java#L188

https://github.com/dCache/dcache/blob/91821cbe4989ec6243af853fcc9dbbb407cc7c1c/modules/gplazma2-multimap/src/main/java/org/dcache/gplazma/plugins/GplazmaMultiMapFile.java#L116

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/13190/
