### ISSUE TITLE
examples for needrestart

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#6194]
Hey.

Do we have something like Debian's `/usr/share/doc/dcache/` in dcache’s git repo?

In Debian it's typical, that one may have an `examples` subdir in that, and for that I'd propose to add:

`needrestart/conf.d/exclude-dcache.conf`:
`$nrconf{override_rc}{qr(^dcache@.+\.service)} = 0;`

`needrestart/conf.d/exclude-postgresql.conf`:
`$nrconf{override_rc}{qr(^postgresql@.+\.service)} = 0;`

These can be used to cause needrestart ignore dcache/postgresql per default and might therefore be beneficial to anyone who runs dcache with needrestart.
I don't think however, that these files should be automatically installed into `/etc`

Neither do I think that such example should go to the book, because no one will ever find them there ;-)

Cheers,
Chris.

**Comment by kofemann** [comment]
Hi @calestyo ,

A funny tool. I never heard about it. Sounds like a workaround for broken packages. Anyway, if you think it would be a good idea to include examples with the dcache package, we can do that. The /usr/share/doc/dcache sounds good.
