### ISSUE TITLE
rep ls -s command output changed breaking many scripts

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#6214]
The commit 67a8a2673ada08916132f8264a31037be4350955 ( https://rb.dcache.org/r/12057/ )

changed the format of "rep ls -s" command breaking many scripts. 

The change added a header and pretty printing of units. 

I can get back to bytes by running 

rep ls -s=b

but  there is no switch to turn off the header 

Suggest to add "-noheader" switch.

**Comment by DmitryLitvintsev** [comment]
or "-legacy" switch (not only header, the footer is the problem as well)

**Comment by paulmillar** [comment]
I've no problem with us adding a `-noheader` switch to this command.  (I think this would be better than adding a `legacy` switch.)

However, an alternative approach is to fix dCache so clients do not need to run admin commands and parse the output.  An alternative might be to use the REST API instead.

IMHO, the admin output is _not_ meant to be parsed by external clients.  If it were meant to be parsed then we can never change it.

**Comment by DmitryLitvintsev** [comment]
This is how admins manage dCache by interacting with it via admin interface. Else we could just disable admin interface. The issue is not that they should not use it, but care needs to be exercised each time externally visible things get changed. 
And if the option can be provided to fall back to previous behavior - this is always be appreciated.

**Comment by DmitryLitvintsev** [comment]
And logic is circular here. If "output should not be parsed" why we provide the output?
 
Generally, regarding all these seemingly cosmetic changes (ftp ls output being similar). If nobody requested 
it, why we are even doing it? dCache existed for 20 years with the kind of output it had for "rep ls -s" command, I do not recall admin clamoring for change.  Having to fix a bunch of scripts because format has changed for no particular 
reason is not winning us any friends.

**Comment by paulmillar** [comment]
Perhaps I phrased this badly.

I meant that the admin interface is (IMHO) intended for human consumption.  Changing the output format (to fix problems, add more information, etc) should be OK for humans, provided information is reasonably laid out.

However, changes to the output format are almost always a show-stopper for software clients that parse the output from a command.  If we say the admin interface is for external clients to parse then we can never change it.

We have the REST API, now.  We can use this to provide information in a standard way and guarantee that format, even when adding more information.  This is a more "future proof" direction, but it likely requires sites to change how they're working.

So, I was thinking another way forward (with this issue) would be to encourage use of REST API.  This would require us making sure all the required information is available through that API.

(also, this looks like another place where we have insufficient functional testing.)

**Comment by DmitryLitvintsev** [comment]
https://rb.dcache.org/r/13333/
