### ISSUE TITLE
Xroot "Session not found"

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6246]
We have on occasion experienced errors of this sort:

```
level=INFO ts=2021-11-03T03:57:24.584-0500 event=org.dcache.xrootd.connection.start session=door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXP3plDjkA socket.remote=131.225.67.61:33294 socket.local=131.225.69.121:1094
level=INFO ts=2021-11-03T03:57:24.586-0500 event=org.dcache.xrootd.request session=door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXP3plDjkA request=protocol response=ok
level=INFO ts=2021-11-03T03:57:24.587-0500 event=org.dcache.xrootd.request session=door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXP3plDjkA request=login username=bays capver=4 pid=19823 token=?xrd.cc=us&xrd.tz=-6&xrd.appname=make_valid_plots&xrd.info=&xrd.hostname=novagpvm01.fnal.gov&xrd.rn=v4.8.5 response=ok sessionId=82FA764935993ECE33ECC0B0E76875CD sec=&P=gsi,v:10400,c:ssl,ca:f5f0dfc2
level=INFO ts=2021-11-03T03:57:24.599-0500 event=org.dcache.xrootd.request session=door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXP3plDjkA request=auth response=authmore
level=INFO ts=2021-11-03T03:57:24.649-0500 event=org.dcache.xrootd.request session=door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXP3plDjkA request=auth response=ok
level=ERROR ts=2021-11-03T03:57:24.650-0500 event=org.dcache.xrootd.request session=door:Xrootd00-fndca4b@xrootd-fndca4bDomain:AAXP3plDjkA request=endsess sessionId=0E868198451E2BFD08B823BADFD2B7FA response=error error.code=NotFound error.msg="session not found"
```

At first blush this seems like the client using the wrong "channel" (i.e., connection) to end a session.   

From the outset, our implementation of xroot has mapped handler instances to one and only one pipeline.   The handler that is throwing this message is the XrootdAuthenticationHandler, which stores the session in an instance variable.   

Perhaps our assumption that the client will close the session on the connection with which it was opened is incorrect.  

Surprising, if so, that it has taken this long to discover this issue.

This issue, however, does not seem to result from any changes to 7.2 (we were getting it at FNAL prior to rollout).

e.g., they were in October logs as well: 

```
[root@fndca4b dcache-log]# zgrep "session not found" xrootd-*.gz > session-errors.log
[root@fndca4b dcache-log]# grep access session-errors.log | wc -l
2375910
[root@fndca4b dcache-log]# grep "endsess sessionId" session-errors.log | grep 2021-10 | wc -l
2235753
[root@fndca4b dcache-log]# grep "endsess sessionId" session-errors.log | grep 2021-11 | wc -l
140157
```

**Comment by paulmillar** [comment]
My suggestion would be to clarify this within the xroot protocol spec: whether or not sessions bound to a TCP connection.

This will help identify whether this is a bug in the client, or in dCache.

**Comment by alrossi** [comment]
I'll check the protocol, yes.

One more data point.   Many of these errors are also associated with this message:  "Queued transfer cancelled: killed by door: transfer interrupted":

**Comment by paulmillar** [comment]
That sounds like something is triggering the door to cancel the transfer.

Any idea what might be causing that?

**Comment by alrossi** [comment]
Apart from the Queued transfer issue, which I believe is independent of the session problem, here is what my current understanding is.

The XrootdAuthenticationHandler's handling of the session id/object has not changed since 2016.   The code does the following:

1.  at login:

	- the channel/handler creates a new session with sessionId
	- it sets the session on the incoming request, hands it off to the login (gPlazma)
	- when the call returns, the session is added to a sessions map ***

2.  on all other request types, the handler sets the session associated with its channel on the request.

3.  on channel inactive, it removes the session from the map ***

Now the routine for onEndSession checks for the session (set from the channel on the request) in the map.

Up until xrootd 5+ these assumptions were correct.  But the protocol since 5 has extended the use of the session id through kXR_bind in order to be able to bind a separate data connection to the session (this because of TLS encryption).  The client now opens more than one socket, sends the bind query, but even if it doesn't bind, it freely reuses the second socket.  We have seen this in other contexts.   What I believe is happening is that it is sending the end session for one socket on another socket which has actually been closed (channel inactive) and for which the session id has already been removed from the map.

Our implementation actually makes little use currently of the sessionId except for potentially identifying purposes, but this will become important when we actually do implement data channel binding (I think this is an inevitable requirement and will be looking into it soon).

My current thinking, though, is that the solution to this problem (preventing the error message) should be simple:  instead of overwriting the incoming end session message's session, check first for a session id.  If it is there already, check for that session in of the map.

**Comment by alrossi** [comment]
"Our implementation actually makes little use."   This is inaccurate.   On the pool, we do nothing with the session.  But on the door, we do close the channel:

```
session.getChannel().close();
```

**Comment by alrossi** [comment]
It is difficult to produce an end session request under "normal" circumstances.   

I have done iterations of both gfal and xrdcp but the door and pool access log reports no end session.

This I think is because on the pool a close suffices, and on the door the client just disconnects.

**Comment by alrossi** [comment]
... and our TPC client also does not do end session on the original door source, but just disconnects.  It only does end session on the pool.

**Comment by alrossi** [comment]
I hacked our TPC client to send end session to the door on redirect.

```
level=INFO ts=2021-11-11T12:41:35.137-0600 event=org.dcache.xrootd.request session=door:xrootd-1094-fndcatemp2@xrootd-1094-fndcatemp2Domain:AAXQh7EZBrg request=open path=/pnfs/fs/usr/test/arossi/volatile/testfile_1b opaque=org.dcache.xrootd.client=arossi.19150@fndcatemp1.fnal.gov&org.dcache.uuid=f880c90f-84c8-465c-9177-d6bee954d5d7 options=0x410 response=redirect host=dcatest04.fnal.gov port=33144
level=INFO ts=2021-11-11T12:41:35.144-0600 event=org.dcache.xrootd.request session=door:xrootd-1094-fndcatemp2@xrootd-1094-fndcatemp2Domain:AAXQh7EZBrg request=endsess sessionId=2515CF0BD20BAFB4D29D2E6E13B08D09 response=ok
```

so at least we know that making the suggested change does not break the normal operations.

**Comment by alrossi** [comment]
Note:  this issue really belongs in the xrootd4j repository.

**Comment by alrossi** [comment]
I'm wondering, though, whether we should even treat the "Not found" as an error.   If the session is not in the map, that means the channel has gone inactive, or that the id is unknown to dCache altogether.   

I propose we lower this message to the WARN level (incorporating into the patch).

**Comment by alrossi** [comment]
see https://rb.dcache.org/r/13264/

**Comment by paulmillar** [comment]
On whether the server should return kXR_ok or return an error when the client attempts to end a session that doesn't exist, this should be specified in the spec.  Currently the spec just doesn't say.

In effect, you're basically asking whether `kXR_endsess` is idempotent, so that might be one way to phrase the question.

As a "quick-fix" we can just do what xrootd does.

**Comment by alrossi** [comment]
The xrootd server just basically ignores phony session ids.  

On the TPC client in dCache I stuck in some calls to end session with an arbitrary session id.  The server sends back OK.

```
211112 09:57:11 17462 arossi.36147:23@dcatest04 XrootdProtocol: 0004 req=endsess dlen=0
211112 09:57:11 17462 arossi.36147:23@dcatest04 XrootdProtocol: 0004 endsess -603004887:-2055116570.2488605930
211112 09:57:11 17462 arossi.36147:23@dcatest04 XrootdResponse: 0004 sending OK
211112 09:57:11 17462 arossi.36147:23@dcatest04 XrootdProtocol: 0004 req=endsess dlen=0
211112 09:57:11 17462 arossi.36147:23@dcatest04 XrootdProtocol: 0004 endsess 65177986:-473920446.1449711686
211112 09:57:11 17462 arossi.36147:23@dcatest04 XrootdResponse: 0004 sending OK
```

So I will alter our code to do the same.
