### ISSUE TITLE
Please modify xslt/storage-descriptor.xsl tag "lastupdated" to "latestupdate"

### ISSUE THREAD

**Issue by lgroer** [dCache/dcache#6254]
For ATLAS information publishing purposes the datestamp tag produced by SRR should have "latestupdate" rather than "lastupdated".  Several sites are modifying this manually.

**Comment by paulmillar** [comment]
Thanks for reporting this problem.  This looks simple to fix.

Patch: https://rb.dcache.org/r/13268/
