### ISSUE TITLE
Update to 7.2 - GridFTP door doesn't start: java.lang.IllegalArgumentException: Failed to instantiate interpreter factory: diskCacheV111.util.ConfigurationException: Failed to create security context:null

### ISSUE THREAD

**Issue by cristinamanzano** [dCache/dcache#6371]
Hi,

we have updated recently to 7.2 and everything seems fine, except in one of the pool-door servers, where the GridFTP door refuses to start. I have checked all that came to mind and I am not able to find any relevant difference regarding the other servers. Do you have any idea what might we be missing here? Some infos regarding the server where the service doesn’t start:

[root@dcachepool9 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

[root@dcachepool9 ~]# uname -a
Linux dcachepool9.fz-juelich.de 3.10.0-1160.49.1.el7.x86_64 # 1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[root@dcachepool9 ~]# rpm -qa | grep java  
java-11-openjdk-devel-11.0.13.0.8-1.el7_9.x86_64
python-javapackages-3.4.1-11.el7.noarch
java-11-openjdk-headless-11.0.13.0.8-1.el7_9.x86_64
java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64
javapackages-tools-3.4.1-11.el7.noarch
tzdata-java-2021e-1.el7.noarch

[root@dcachepool9 ~]# java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode, sharing)

[root@dcachepool9 ~]# cat /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64/conf/security/java.security | grep "#   jdk.tls.disabledAlgorithms" -A 4
\#   jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048, \
\#       rsa_pkcs1_sha1
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, TLSv1.3, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves

[root@dcachepool9 ~]# rpm -qa | grep dcache
dcache-7.2.5-1.noarch

And here it is the gridftpDomain log: [dcachepool9_gridftpDomain.log](https://github.com/dCache/dcache/files/7711073/dcachepool9_gridftpDomain.log)

Thanks in advance.

Cheers,

Cristina

**Comment by lemora** [comment]
Hi Christina.

I answered your corresponding RT ticket earlier. Would you prefer following it up here instead?

Lea

**Comment by cristinamanzano** [comment]
Sorry for double posting, yes, I prefer this channel, it is easier to browse and search older issues here.

For documentation purposes, your suspicion:

"
I suspect that the reason is that the X.509 certificate that the door attempts to load is password protected, which is not expected. dCache, in turn, does not handle this case correctly and throws a NullPointerException. I will provide a fix that hopefully results in a more helpful error message:
`java.io.IOException: Error decrypting private key: the password is incorrect or the PEM data is corrupted.`
"

And you are right, the problem was in the hostkey.pem which was password protected:

[root@dcachepool9 grid-security]# ssh-keygen -y -f hostkey.pem       
Enter passphrase: 

Thank you! I will use only this channel from now on.

**Comment by lemora** [comment]
In the patch I mentioned the RT ticket number, not the GitHub one. So here is the RB link:
https://rb.dcache.org/r/13337/
