### ISSUE TITLE
View telemetry data that is uploaded

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#6390]
Dear dCache devs,

I've enabled the Telemetry for our dCache production instance. Now I'm kind of curious which information is uploaded. I currently don't see any way to get this information. It appears the Telemetry cell is not accessible through the admin interface. Is there a way to see which data is uploaded?

Cheers,
Onno

**Comment by lemora** [comment]
Hi Onno,

if enabled, the Telemetry cell reports the dCache version as well as total space, and if explicitly provided, also the site name (`telemetry.instance.site-name`) and location (`telemetry.instance.location.latitude`, `telemetry.instance.location.longitude`).
If information is sent, you should see `Information successfully sent to `... once an hour in your log files/the pinboard at info level.

It is not possible to query what information is being sent at the moment, but it should be possible to add.

**Comment by onnozweers** [comment]
Hi Lea,

Thanks for the summary of what is uploaded. I look forward to an option to view it in more detail.

Cheers,
Onno

**Comment by svemeyer** [comment]
Hi Onno,

there will be a command to print the data that is being sent in dCache 8.0, so I'm closing this issue now.

**Comment by onnozweers** [comment]
That's great! Thanks Svenja!
