### ISSUE TITLE
changed host certificate not automatically re-loaded

### ISSUE THREAD

**Issue by thdesy** [dCache/dcache#6424]
Dear Developers,

we noticed on
 - dcache-7.2.5-1.noarch
 - dcache-7.2.6-1.noarch
that updated host certificate seem not to be automatically re-loaded and the previous certificate is kept in use.

E.g., last week transfers failed due to the SSL handshakes breaking because a doors certificate was ostensibly expired.
However, the nominally expired host certificate had already been replaced several days before. 

 - previous certificate
```
notBefore=Dec  9 14:58:00 2020 GMT
notAfter=Jan  8 14:58:00 2022 GMT
```

 - current certificate
```
notBefore=Dec 13 14:53:17 2021 GMT
notAfter=Jan 12 14:53:17 2023 GMT
```

The transfers/handshakes started just with the expiration date of the previous certificate.
We cross-checked and the updated certificate were on place during that time, so that we assume, that a restart/reload of the instance might be necessary for picking up changed certs.

Cheers

**Comment by alrossi** [comment]
Hi,  

not being at DESY, I am unsure what protocol this involves.   That info would be useful I believe.

Thanks, Al

**Comment by thdesy** [comment]
ah, sorry - yes, the issue affected most protocols where the initial SSL handshake failed, i.e., gFTP, gsidcap,...

```
Creating a new control connection to dcache-door-cms07.desy.de.
Activating IO tunnel. Provider: [libgsiTunnel.so].
GSS Minor Status Error Chain:
globus_gsi_gssapi: SSL handshake problems
OpenSSL Error: s3_clnt.c:1264: in library: SSL routines, function ssl3_get_server_certificate: certificate verify failed
globus_gsi_callback_module: Could not verify credential
globus_gsi_callback_module: The certificate has expired: Credential with subject: /C=DE/O=GermanGrid/OU=DESY/CN=dcache-door-cms07.desy.de has expired.
```

```
 > gfal-rm -v gsiftp://dcache-desy-gridftp.desy.de:2811/pnfs/desy.de/desy/SETests/tests/testfile.1642087202_47061
gfal-rm error: 13 (Permission denied) - globus_ftp_control: gss_init_sec_context failed OpenSSL Error: s3_clnt.c:1264: in library: SSL routines, function ssl3_get_server_certificate: certificate verify failed globus_gsi_callback_module: Could not verify credential globus_gsi_callback_module: The certificate has expired: Credential with subject: /C=DE/O=GermanGrid/OU=DESY/CN=dcache-door-desy04.desy.de has expired. 
gsiftp://dcache-desy-gridftp.desy.de:2811/pnfs/desy.de/desy/SETests/tests/testfile.1642087202_47061	FAILED
errc:13
```

**Comment by alrossi** [comment]
OK, thanks.  (Gsidcap and Gsiftp are independent of https and xroot in their security layer, which is why this may help to isolate the issue).

**Comment by alrossi** [comment]
One other question:  did the transfers fail just once, or were all transfers thereafter continuing to fail?

(I'm thinking there might have been a little skew between the expiration time and the computed timeout inside dCache).

**Comment by thdesy** [comment]
as far as I see, the transfers failed from the time on the certificate expired

for one instance our local functionality tests for gsiftp and gsiccap started to fail on Jan.08 from ~16:00 CET on - which corresponds to the door's  previous certificate, that expired at 14:58:00. From that time on the tests continued to fail for that door - until the door got restarted.

**Comment by alrossi** [comment]
Thanks.  That rules out what I said above.   At this point I am not sure what is wrong, because the caching should be looking at certificate expiration and invalidating accordingly.

**Comment by svemeyer** [comment]
Maybe this is related to #6353?

**Comment by thdesy** [comment]
just adding details - the previous certificate expired `notAfter=Jan  8 14:58:00 2022 GMT` and the [failed test transfers](https://sas.desy.de/index.php/s/wWFgc7w5tp4yK9C) started 16:00 CET

for th door the expired certificate got replaced by the new one `Dec 13 20:38`. 

As you mentioned, it seems to affect only gsiftp and gsidcap (no failed transfers for xrootd or dav, which seem to have noticed & picked up the new cert on time)

**Comment by alrossi** [comment]
@svemeyer Thanks, Svenja ... I missed that one (was away from work during that period).   It may indeed be a duplicate, and I see Paul's first question was the same as mine above :-).

It seemed to me that Gsiftp was also using the Canl factory but there may be a couple of different paths through the code involved.   I will try to have a look later.

**Comment by alrossi** [comment]
Are we sure we are not experiencing the same issue on HTTPS and Xroot doors?

**Comment by thdesy** [comment]
as far as I see just gsiFTP and gsiDCAP were affected.

e.g., on door dcache-door-atlas12 domians for ftp, dav and xrootd are running. When on Jan.08 afternoon the previous cert expired, only the gFTP test transfers against the door started to fail while the test transfers over the two other protocols still succeeded into the evening

[protocol errcode(0:OK) epoch](https://sas.desy.de/index.php/s/EJtJD3CxGPo5g2C)

**Comment by kofemann** [comment]
One question, how log you have waited after update? (trying to debug it...)

**Comment by thdesy** [comment]
in the case during Jan.08, the certificate run out during the afternoon and the door got restarted in the late evening

maybe we can use another door for debugging - the door's previous certificate is running out on Sunday and we are planning to drain it and keep it available for investigation.

**Comment by DmitryLitvintsev** [comment]
Tigran. The issue can be reproduced easily by removing  (moving out of /etc/grid-security) of host{cert,key}.pem files. Then running transfers. I verified that all Jetty hosted doors behave correctly (fail on ssl handshake) while GFTP and GSI dCache continue working indicating cached cert in memory. Examining code it looks like yes cert is cached, but supposedly for 1 minute only. But repeated transfers continue to succeed past 1 minute after removing certs.

**Comment by kofemann** [comment]
Exactly, so I am trying to build a unit test. Up to now, indeed test shows that cached certs invalidated after 1 min.

Stil digging... 👷

**Comment by kofemann** [comment]
There is a light.... https://rb.dcache.org/r/13419/

**Comment by kofemann** [comment]
```
04 Feb 2022 18:02:00 (DCap-gsi-nairi) [127.0.0.1:34254] Exception (ITE) in secure protocol: Tunnel verification failed: /home/tigran/eProjects/dcache/packages/system-test/target/dcache/etc/grid-security/hostkey.pem (No such file or directory)
04 Feb 2022 18:02:00 (DCap-gsi-nairi) [127.0.0.1:34256] Exception (ITE) in secure protocol: Tunnel verification failed: /home/tigran/eProjects/dcache/packages/system-test/target/dcache/etc/grid-security/hostkey.pem (No such file or directory)
```

**Comment by onnozweers** [comment]
When will this fix be released in 7.2? We've scheduled an upgrade to 7.2 for Feb 15th (next week); it would be nice if we could have it.

**Comment by kofemann** [comment]
@onnozweers typically, we release once a week. So hopefully by Friday we should have it (no promises :)).

**Comment by kofemann** [comment]
Hi @ageorget ,

I run the test.  The test which I had was passing with 6.2. So, either I am testing something else or the test doesn't cover your usecase. The canal version in 6.2 and 7.2 is the same.

**Comment by ageorget** [comment]
Hi @kofemann 

We're running 6.2.38 version on those pools. 
The LSST usecase affected by this issue : 

Pools with encrypted transfers and a single HTTP mover port : 
```
pool.enable.encrypted-transfers=true
pool.mover.http.port.min=30000
pool.mover.http.port.max=30000
```

LSST only uses Webdav+HTTPS for transfers with HTTPS pool redirection.

**Comment by kofemann** [comment]
Ok. Let me check if pools do something different, though they shouldn't...
