### ISSUE TITLE
No user.oidc field (or similar) in webdav access log

### ISSUE THREAD

**Issue by sfayer** [dCache/dcache#6452]
Hi,

When I access a webdav door using an OIDC/scitoken (on dCache 7.2.8) the access log doesn't seem to contain any details to identifier the original requester. Would it be possible to log a suitable set of field(s) to allow the request to be traceable back to a user by default (i.e. the OIDC subject ID (including OP?) and possibly the token's JTI)? I've not tested out token auth with xrootd but I imagine the same thing is true of the access log there.

Regards,
Simon

**Comment by paulmillar** [comment]
Hi Simon,

Yes, that's true that we currently don't log the OIDC `sub` or the `jti` claim values.  As you suspected, this is true for all doors and not just WebDAV door.

I think both would be reasonable things to include in the access log file.

Cheers,
Paul.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/13418/
