### ISSUE TITLE
Active transfers report lacks third-party-copy records

### ISSUE THREAD

**Issue by XMol** [dCache/dcache#6540]
Hello dCache.org,

I had reported this in the RT already (\#10303) and Albert informed me, that @paulmillar had already submitted a [patch that addresses at least the HTTP TPC transfers](https://rb.dcache.org/r/13162/). Admittedly, xrootd TPCs are not covered yet.

This issue serves as a feature request to continue working on the issue. Our monitoring for current transfer activity simply lacks those class of transfers and therefor is quite misleading. The situation gets worse as the WLCG experiments dispatch TPCs more liberally now.

Thank you for your attention,
Xavier.

/cc @alrossi

**Comment by alrossi** [comment]
@paulmillar I assume that the xrootd-specific solution could then be built on your revised patch?  Should I wait until that is committed to implement?

**Comment by paulmillar** [comment]
Yes, HTTP-TPC is different from xroot-TPC.

xroot-TPC uses the normal copy process, but adds metadata so the pool knows it's actually a third-party transfer.

HTTP-TPC uses the RemoteTransferManager service to do (almost) all the coordination.  In this way, RemoteTransferManager is acting like a door, but doesn't advertise itself as such, so the transfers are unknown to httpd and frontend.

**Comment by XMol** [comment]
>  In this way, RemoteTransferManager is acting like a door, but doesn't advertise itself as such, so the transfers are unknown to httpd and frontend.

Billing even declares a new protocol for these HTTP-TPCs, too.

> 03.30 00:03:12 [pool:f01-152-140-e_D_lhcb@f01-152-140-e_D_lhcbDomain:transfer] [0000DAC4044EF7934434961E1B319225702B,125261724] [/pnfs/gridka.de/lhcb/LHCb-Disk/lhcb/MC/2017/DSTARD02KSKK.HLTFILTER.MDST/00158493/0000/00158493_00000297_1.dstard02kskk.hltfilter.mdst] dc_lhcb:LHCB@osm 125261724 1497 true {RemoteHttpsDataTransfer-1.1:https://xfer-lhcb.cr.cnaf.infn.it:8443/disk/lhcb/MC/2017/DSTARD02KSKK.HLTFILTER.MDST/00158493/0000/00158493_00000297_1.dstard02kskk.hltfilter.mdst} [door:RemoteTransferManager@transferManager-f01-080-113Domain:1648591391028-333472] [p2=false] {0:""}

**Comment by XMol** [comment]
> Thanks for the motivating issue!

And here's a motivating reminder. :wink:

We still cannot quantify how much data is send to or read from our dCache SEs via HTTP-TPC, since there are no active transfers for that.

**Comment by alrossi** [comment]
As far as xroot is concerned, are we good?  Do you use native xroot TPC?  Are those not showing up?  My own test above seems to suggest there is nothing further to do there, that this is specifically an HTTPS problem (which I think Paul has promised to take care of ...)  

Al

**Comment by XMol** [comment]
Yes, chances are, this is exclusively about HTTPS-TPC.

**Comment by XMol** [comment]
This issue is solved by ed926ca25e388e7d6c07511dcbaf92c2088cdbf2, which went into 7.2.20 (4f0328d84c786288c049d74682b2ec4cbb997ba2), 8.0.10 (1fca124200792cd153521af3b5d02ab56201b252) and 8.1.4 (61e98372efd7352e0630a3dd1b1824d1f6fcf12b)
