### ISSUE TITLE
Webdav: Asking for sha digest/checksum on upload doesn't work

### ISSUE THREAD

**Issue by ZNikke** [dCache/dcache#6541]
Using dCache 7.2.10, uploading a file via webdav and requesting a sha checksum doesn't work:

```
+ curl -D- -L -T testfile -E /tmp/x509up_uNNNN -H 'Want-Digest: sha' https://dcache/checksums/file-sha
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Date: Mon, 14 Mar 2022 14:58:05 GMT
Server: dCache/7.2.10
Accept-Ranges: bytes
ETag: "0000687DAC661D484BF79C3A6837C74E9CE7_-1997556734"
Transfer-Encoding: chunked
```

However, when trying all variant spellings of sha/sha1/sha-1 I discovered that when requesting `sha-1` I actually get a `sha` checksum!

```
+ curl -D- -L -T testfile -E /tmp/x509up_uNNNN -H 'Want-Digest: sha-1' https://dcache/checksums/file-sha-1
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Date: Mon, 14 Mar 2022 14:58:06 GMT
Server: dCache/7.2.10
Accept-Ranges: bytes
ETag: "0000CE7A3B2B372B4459887868F9015AA230_-1997554854"
Digest: sha=Iep9y83KpKcLJUY0EqvYALvFeOE=
Transfer-Encoding: chunked
```

I'm guessing that this is a mapping gone wrong somewhere. I'm all for that sha/sha1/sha-1 should all be coerced to sha, but the current behavior is a bit too confusing to be correct :)

On a related note, the webdav checksum examples in [UserGuide 7.2](https://dcache.org/old/manuals/UserGuide-7.2/webdav.shtml#checksums) should probably be amended with the current checksum variants that dCache supports as of https://github.com/dCache/dcache/commit/0c19f644a86a3d11de5049002135753afe64b7f6 ...

**Comment by paulmillar** [comment]
I can confirm that [IANA registry](https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml) has `SHA` as the correct label.

**Comment by lemora** [comment]
According to [RFC 3230](https://datatracker.ietf.org/doc/html/rfc3230) `sha` is indeed the correct label for `sha-1`, thus the digest that is returned to you
`Digest: sha=Iep9y83KpKcLJUY0EqvYALvFeOE=`
is in fact of type sha-1, algorithmically. That you currently have to request `sha-1` explicitly, though, is wrong, of course. Thanks for reporting.

**Comment by ZNikke** [comment]
FYI, it's the same behavior for HEAD requests:

```
$ curl -E /tmp/x509up_uNNNN -H 'Want-Digest: sha' -I https://dcache/checksums/file-sha-1
HTTP/1.1 200 OK
Date: Tue, 15 Mar 2022 07:40:03 GMT
Server: dCache/7.2.10
Accept-Ranges: bytes
ETag: "00009D85B82213A6412DB23E5305EF7F74B2_-1937498276"
Last-Modified: Tue, 15 Mar 2022 07:39:03 GMT
Content-Length: 655360

$ curl -E /tmp/x509up_uNNNN -H 'Want-Digest: sha-1' -I https://dcache/checksums/file-sha-1
HTTP/1.1 200 OK
Date: Tue, 15 Mar 2022 07:40:20 GMT
Server: dCache/7.2.10
Accept-Ranges: bytes
ETag: "00009D85B82213A6412DB23E5305EF7F74B2_-1937498276"
Last-Modified: Tue, 15 Mar 2022 07:39:03 GMT
Digest: sha=Iep9y83KpKcLJUY0EqvYALvFeOE=
Content-Length: 655360
```

While also wrong, not a surprise. I would have been more worried if PUT and HEAD behaved differently...
