### ISSUE TITLE
dcache-frontend:  add namespace/dump/<path> resource

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6651]
See https://rt.dcache.org/Ticket/Display.html?id=10320

For ATLAS.

Provide dumps of basic directories through REST API (requested by Xavier Mol).

see:

1) https://twiki.cern.ch/twiki/bin/view/AtlasComputing/DDMDarkDataAndLostFiles#Automated_checks_Site_Responsibi

2) https://gitlab.cern.ch/atlas-adc-ddm-support/dark_data/blob/master/chimera_find.sh

**Comment by XMol** [comment]
Hi Al,

I've hinted ATLAS DDM about this proposition and although they like the idea and appreciate the effort, chances are very slim that they will depend on it for their workflows. For the simple reason that this is a specific solution to dCache SEs and they prefer a uniform solution where the dumps are found in a predetermined location and are downloadable with root protocol.

So with zero pressure to implement this feature, it might serve as just a use-case for reworking the REST API model such that it might become easier to extend it (maybe even with plugins). That however means a complete redo for the WebAPI, I presume, so you're free to close this request and forget about it.

Ciao,  
Xavier.

**Comment by alrossi** [comment]
(may return to the plugin idea at some later date)
