### ISSUE TITLE
Scrubber Idle: Index 0 out of bounds

### ISSUE THREAD

**Issue by elenamplanas** [dCache/dcache#6665]
We had a problem with a pool , and had to run xfs_repair to mount the disk again. After doing this, scrub is not running anymore. The error we are facing is:

`[dccore11] (local) admin > \s dc055_1 csm status
FullScan Idle  0 files: 0 corrupt, 0 unable to check
SingleScan Idle 
Scrubber Idle java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0  processed 0 of 0 files: 0 corrupt, 0 unable to check`

It seems that metadata could be corrupted. Is there a way to initialize it from scratch?

Thanks!

**Comment by lemora** [comment]
Hi Elena.

It seems your scrubber state file that is attempted to be loaded is empty -- could you check? It should be located at the `<pool path>/scrubber.state`.
If you remove that file the scrubbing should start immediately and check the whole pool.
