### ISSUE TITLE
NFSv4 doesn't work in proxy mode when POSIX file locking is used

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#6881]
As reported by @onnozweers NFS door hands when proxy IO combined with POSIX locking

```
 openat(AT_FDCWD, "/pnfs/..../file.nc", O_RDONLY) = 3
 fstat(3, {st_mode=S_IFREG|0660, st_size=61700250, ...}) = 0
 flock(3, LOCK_SH|LOCK_NB)               = 0
 mmap(NULL, 528384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) =
 0x7fe32e084000
 pread64(3,
 ### here it hangs
```

This is likely a result of sending lock-stateid to the pool. However, movers recognize only open-stateid. Thus
door must resolve open-stateid for provided lock-stateid before proxing the request.

**Comment by onnozweers** [comment]
Hi Tigran,

Cool, that was quick! Thanks!

**Comment by onnozweers** [comment]
Hi Tigran,

Thanks for the quick release in 7.2.28! I have installed it and the fix seems to work.

Kind regards,
Onno
