### ISSUE TITLE
Proxy xrootd door keep restarting

### ISSUE THREAD

**Issue by vingar** [dCache/dcache#6909]
Hello,

The Xrootd doors enabled with `xrootd.net.proxy-transfers=true` keep restarting on one of our instances.

The dCache version is 8.2.2.

Some observed error in the logs (see file 
[xrootd2-dcdndoor03Domain.log](https://github.com/dCache/dcache/files/10148865/xrootd2-dcdndoor03Domain.log)
in copy) are:

```04 Dec 2022 04:18:49 (Xrootd-dcdndoor03-externalsubnet) [] Thread Group "Xrootd-dcdndoor03-externalsubnet-threads":
Thread: pool-14-thread-1 [A--] (5) TIMED_WAITING
    java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
    java.base@11.0.16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
    java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
    java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
    java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
    java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
    java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
04 Dec 2022 04:18:49 (Xrootd-dcdndoor03-externalsubnet) [] Forcefully interrupting thread pool-14-thread-1 during shutdown.
04 Dec 2022 04:18:50 (Xrootd-dcdndoor03-externalsubnet) [] Thread Group "Xrootd-dcdndoor03-externalsubnet-threads":
Thread: pool-14-thread-1 [A--] (5) TIMED_WAITING
    java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
    java.base@11.0.16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
    java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
    java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
    java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
    java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
    java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
```

```
04 Dec 2022 07:02:25 (Xrootd-dcdndoor03-externalsubnet) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
```

```
04 Dec 2022 04:07:55 (Xrootd-dcdndoor03-externalsubnet) [] Outbound write on [id: 0x2818fb0f, L:::/0:0:0:0:0:0:0:0:47425]: {}
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
04 Dec 2022 04:07:55 (Xrootd-dcdndoor03-externalsubnet) [] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
04 Dec 2022 04:07:55 (Xrootd-dcdndoor03-externalsubnet) [] Outbound write on [id: 0x2818fb0f, L:::/0:0:0:0:0:0:0:0:47425]: {}
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
04 Dec 2022 04:07:55 (Xrootd-dcdndoor03-externalsubnet) [] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```
[xrootd2-dcdndoor03Domain.log](https://github.com/dCache/dcache/files/10148857/xrootd2-dcdndoor03Domain.log)

**Comment by alrossi** [comment]
It looks like the root cause might be the OutOfMemory exception.   If you have a lot of activity going through a single door, and it is all proxied transfers, that would make some sense I think.

How much memory have you allocated to the door?

**Comment by vingar** [comment]
Hi,
Does the proxy mode require more memory ? The load is about  19.6 K transfers per hour on this door (see plot). The same load on non proxied xrootd doors is fine for them.

![image](https://user-images.githubusercontent.com/9110689/205700190-37abe4ba-de03-4aee-82bc-ceb372bf0db0.png)

**Comment by alrossi** [comment]
I would think so.

You need to keep in mind that the transport pipeline is Netty, which tries to take advantage of Java NIO.  That means it will be trying to allocate direct (i.e., kernel) memory space rather than simple heap space.   Ordinarily the client is redirected for the actual transfer to the pool.  The normal connections which log in, request a pool and start the mover do not have a large memory footprint.  But now we are not only holding two connections per transfer in the door, but the second connection is a data connection, and while data is being streamed through the door mostly without deserialization/re-serialization, there is still a buffer it is written to and from that is allocated.

Netty tries to take advantage of Java NIO by writing this buffer directly in kernel space (avoiding two copy operations).  So it needs that kernel space (=direct) to be available.

I have a suspicion that your direct memory allocation is too low.   Remember, for Java, when you configure any dCache domain, you need to set them both.  For instance:

```
dcache.java.memory.heap=2048m
dcache.java.memory.direct=2048m   <<<<<<<<<<<<<<
```

It is the second one that I think is causing your issues, which is why I asked what you have it set to.   Unfortunately I can't really make recommendations yet because you are sort of our guinea pig here :-).  

In any event, take a look at what your pools are set to and maybe start with that setting for the door.

HTH,  Al

**Comment by cfgamboa** [comment]
The memory allocated is -Xmx512m -XX:MaxDirectMemorySize=512m which might be the default

[xrootd-${host.name}Domain]
dcache.java.memory.heap=2048m
dcache.java.memory.direct=2048m
[xrootd-${host.name}Domain/xrootd]
xrootd.cell.name=Xrootd-${host.name}
xrootd.net.port=1097
xrootd.net.proxy-transfers=true
xrootd.net.internal=10.42.64.27

It does not seem to take the new values for memory
```
root     17729 32.5  0.0 8292224 660052 ?      Ssl  14:57   0:45 /usr/bin/java -server -Xmx512m -XX:MaxDirectMemorySize=512m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=20000,50000 -Dorg.dcache.dcap.port=0 -Dorg.dcache.ftp.log-aborted-transfers=true -Dorg.dcache.net.tcp.portrange=33115:33315 -Djava.security.krb5.realm= -Djava.security.krb5.kdc= -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -Dcontent.types.user.table=/etc/dcache/content-types.properties -Dzookeeper.sasl.client=false -Dcurator-dont-log-connection-problems=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/dcache/xrootd-dcdndoor03Domain-oom.hprof -XX:+ExitOnOutOfMemoryError -XX:+StartAttachListener -XX:+UseCompressedOops -javaagent:/usr/share/dcache/classes/aspectjweaver-1.9.2.jar -Djava.net.preferIPv6Addresses=system -Djava.awt.headless=true -DwantLog4jSet
```

**Comment by alrossi** [comment]
```
[xrootd-1094-${host.name}Domain]
dcache.java.memory.heap=2048m
dcache.java.memory.direct=2048m
[xrootd-1094-${host.name}Domain/xrootd]
xrootd.cell.name=xrootd-1094-${host.name}
xrootd.net.port=1094
xrootd.authz.write-paths=/
xrootd.authz.read-paths=/
```

```
[root@fndcatemp2 ~]# ps auxwww | grep 1094
root     30816  467  0.7 8592816 512308 ?      Ssl  14:36   0:23 /usr/bin/java -server **-Xmx2048m** -**XX:MaxDirectMemorySize=2048m** -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=20000,25000 -Dorg.dcache.dcap.port=0 -Dorg.dcache.ftp.log-aborted-transfers=true -Dorg.dcache.net.tcp.portrange=33115:33145 -Djava.security.krb5.realm=FNAL.GOV -Djava.security.krb5.kdc= -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -Dcontent.types.user.table=/etc/dcache/content-types.properties -Dzookeeper.sasl.client=false -Dcurator-dont-log-connection-problems=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/dcache/xrootd-1094-fndcatemp2Domain-oom.hprof -XX:+ExitOnOutOfMemoryError -XX:+StartAttachListener -XX:+UseCompressedOops -javaagent:/usr/share/dcache/classes/aspectjweaver-1.9.9.1.jar -Djava.net.preferIPv6Addresses=system --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.sql/java.sql=ALL-UNNAMED --add-opens=java.base/java.math=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Djava.awt.headless=true -DwantLog4jSetup=n -Dorg.bouncycastle.dh.allow_unsafe_p_value=true -Djava.security.properties=/etc/dcache/max.java.security -Djdk.tls.ephemeralDHKeySize=2048 -Ddcache.home=/usr/share/dcache -Ddcache.paths.defaults=/usr/share/dcache/defaults org.dcache.boot.BootLoader start xrootd-1094-fndcatemp2Domain
```

did you do cold stop and start or just restart?

**Comment by cfgamboa** [comment]
The xrootd cell appears not to pass the values for memory.
I can change the values by enabling them externally
root     33330 14.5  0.1 10190876 982524 ?     Ssl  16:23   0:49 /usr/bin/java -server -Xmx2048m -XX:MaxDirectMemorySize=2048m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=20000,50000 -Dorg.dcache.dcap.port=0 -Dorg.dcache.ftp.log-aborted-transfers=true -Dorg.dcache.net.tcp.portrange=33115:33315 -Djava.security.krb5.realm= -Djava.security.krb5.kdc= -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -Dcontent.types.user.table=/etc/dcache/content-types.properties -Dzookeeper.sasl.client=false -Dcurator-dont-log-connection-problems=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/dcache/xrootd-dcdndoor03Domain-oom.hprof -XX:+ExitOnOutOfMemoryError -XX:+StartAttachListener -XX:+UseCompressedOops -javaagent:/usr/share/dcache/classes/aspectjweaver-1.9.2.jar -Djava.net.preferIPv6Addresses=system -Djava.awt.headless=true -DwantLog4jSetup=n -Dorg.bouncycastle.dh.allow_unsafe_p_value=true -Ddcache.home=/usr/share/dcache -Ddcache.paths.defaults=/usr/share/dcache/defaults org.dcache.boot.BootLoader start xrootd-dcdndoor03Domain

**Comment by kofemann** [comment]
You need to run 'systemctl daemon-reload' to propagate new java options to systemd units.

**Comment by cfgamboa** [comment]
That did it, I am able to see the new values for memory on the daemons.
Thank you.

**Comment by vingar** [comment]
After the change, It looks better and is being monitored

One side remark about the uncaught exceptions, Will it be possible to get dCache error messages ?

**Comment by alrossi** [comment]
Not sure what you mean by dCache error messages.  What you are seeing is in fact generated by dCache.  The system cell is the final arbiter of how uncaught exceptions are handled:

```

if (e instanceof VirtualMachineError) {
    kill();
    _log.error(AlarmMarkerFactory.getMarker(PredefinedAlarm.FATAL_JVM_ERROR,
                getCellDomainName(),
                getCellName()),
          "Restarting due to fatal JVM error: {}", e.toString());
    return;
}

```

thus:

```

04 Dec 2022 07:02:25 (Xrootd-dcdndoor03-externalsubnet) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory

```

What did you have in mind?

-Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
WH 566
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by alrossi** [comment]
Oh, the pipeline errors.  I've been meaning to add an error handler to clean up on these (they are rather unpredictable) ... but haven't gotten around to it yet.

Thanks, Al


________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
WH 566
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by alrossi** [comment]
These kinds of errors are hard to reproduce, so there are no absolute guarantees.  

But I have added what I think is a mitigation (suggested by Netty developers):

https://rb.dcache.org/r/13833/
