### ISSUE TITLE
API: changing QoS says "success" but doesn't work (master snapshot 9.0)

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#6914]
Dear dCache devs,

Changing the QoS of a file through the API seems broken in the master 9.0 snapshot. The API reports back "success" but the QoS of the file is not changed.
In our production instance (version 7.2) it works as expected.

Here's what I did:

Getting a macaroon with these properties:
```
location Optional.empty
identifier dIGgJazo
cid iid:Ru2zIwqu
cid id:31029;31040,40304,30013;onno
cid before:2022-12-07T22:03:45.516158Z
cid home:/users/onno
cid root:/users/onno
cid activity:LIST,DOWNLOAD,UPLOAD,MANAGE,DELETE,READ_METADATA,UPDATE_METADATA
cid ip:145.38.0.0/16,145.100.5.0/27,145.100.5.210/26,145.100.32.0/22,145.100.48.0/23,145.100.50.0/23,145.100.200.0/21,145.100.9.64/29,145.101.32.0/21,145.100.56.0/22,2001:610:108::/48
```
Listing a file:
```
11:07 ui.grid.surfsara.nl:/home/onno 
onno$ curl --config /home/onno/.ada/headers/authorization_header_3yL6CRUz2IfM -H 'accept: application/json' --fail --silent --show-error --ipv4 -X GET 'https://dcachetest.grid.surfsara.nl:20443/api/v1/namespace/%2Ftape%2Ftest?locality=true&qos=true'
{
  "fileMimeType" : "application/octet-stream",
  "fileLocality" : "ONLINE_AND_NEARLINE",
  "currentQos" : "tape",
  "labels" : [ ],
  "size" : 10485760,
  "creationTime" : 1669736063762,
  "fileType" : "REGULAR",
  "pnfsId" : "0000EC9AEB2B04304A8D8E34F530B55198F5",
  "nlink" : 1,
  "mtime" : 1669736064395,
  "mode" : 384
}
```
Changing the QoS returns "success":
```
11:08 ui.grid.surfsara.nl:/home/onno 
onno$ curl --config /home/onno/.ada/headers/authorization_header_3yL6CRUz2IfM -H 'accept: application/json' --fail --silent --show-error --ipv4 -H 'content-type: application/json' -X POST https://dcachetest.grid.surfsara.nl:20443/api/v1/namespace/%2Ftape%2Ftest -d '{"action":"qos","target":"disk+tape"}'
{"status":"success"}
```
But the QoS of the file has not changed:
```
11:09 ui.grid.surfsara.nl:/home/onno 
onno$ curl --config /home/onno/.ada/headers/authorization_header_3yL6CRUz2IfM -H 'accept: application/json' --fail --silent --show-error --ipv4 -X GET 'https://dcachetest.grid.surfsara.nl:20443/api/v1/namespace/%2Ftape%2Ftest?locality=true&qos=true'
{
  "fileMimeType" : "application/octet-stream",
  "fileLocality" : "ONLINE_AND_NEARLINE",
  "currentQos" : "tape",
  "labels" : [ ],
  "size" : 10485760,
  "creationTime" : 1669736063762,
  "fileType" : "REGULAR",
  "pnfsId" : "0000EC9AEB2B04304A8D8E34F530B55198F5",
  "nlink" : 1,
  "mtime" : 1669736064395,
  "mode" : 384
}
```
This was on our new test server. I tested this also on our old test server dolphin12, running a 9.0 master snapshot too. Same behaviour.

I would expect the API call to succeed in changing the QoS, or else report a failure.

Cheers,
Onno

**Comment by mksahakyan** [comment]
Hi Onno, 

normally, the request to change the QoS of the file is send to the scheduler and {"status":"success"} 
indicates that the request has been received. 


cheers 
Marina 


From: "Onno Zweers" ***@***.***> 
To: "dCache" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Wednesday, 7 December, 2022 11:32:09 
Subject: [dCache/dcache] API: changing QoS says "success" but doesn't work (master snapshot 9.0) (Issue #6914) 





Dear dCache devs, 

Changing the QoS of a file through the API seems broken in the master 9.0 snapshot. The API reports back "success" but the QoS of the file is not changed. 
In our production instance (version 7.2) it works as expected. 

Here's what I did: 

Getting a macaroon with these properties: 
location Optional.empty
identifier dIGgJazo
cid iid:Ru2zIwqu
cid id:31029;31040,40304,30013;onno
cid before:2022-12-07T22:03:45.516158Z
cid home:/users/onno
cid root:/users/onno
cid activity:LIST,DOWNLOAD,UPLOAD,MANAGE,DELETE,READ_METADATA,UPDATE_METADATA
cid ip:145.38.0.0/16,145.100.5.0/27,145.100.5.210/26,145.100.32.0/22,145.100.48.0/23,145.100.50.0/23,145.100.200.0/21,145.100.9.64/29,145.101.32.0/21,145.100.56.0/22,2001:610:108::/48 


Listing a file: 
11:07 ui.grid.surfsara.nl:/home/onno 
onno$ curl --config /home/onno/.ada/headers/authorization_header_3yL6CRUz2IfM -H 'accept: application/json' --fail --silent --show-error --ipv4 -X GET 'https://dcachetest.grid.surfsara.nl:20443/api/v1/namespace/%2Ftape%2Ftest?locality=true&qos=true'
{
  "fileMimeType" : "application/octet-stream",
  "fileLocality" : "ONLINE_AND_NEARLINE",
  "currentQos" : "tape",
  "labels" : [ ],
  "size" : 10485760,
  "creationTime" : 1669736063762,
  "fileType" : "REGULAR",
  "pnfsId" : "0000EC9AEB2B04304A8D8E34F530B55198F5",
  "nlink" : 1,
  "mtime" : 1669736064395,
  "mode" : 384
} 


Changing the QoS returns "success": 
11:08 ui.grid.surfsara.nl:/home/onno 
onno$ curl --config /home/onno/.ada/headers/authorization_header_3yL6CRUz2IfM -H 'accept: application/json' --fail --silent --show-error --ipv4 -H 'content-type: application/json' -X POST https://dcachetest.grid.surfsara.nl:20443/api/v1/namespace/%2Ftape%2Ftest -d '{"action":"qos","target":"disk+tape"}'
{"status":"success"} 


But the QoS of the file has not changed: 
11:09 ui.grid.surfsara.nl:/home/onno 
onno$ curl --config /home/onno/.ada/headers/authorization_header_3yL6CRUz2IfM -H 'accept: application/json' --fail --silent --show-error --ipv4 -X GET 'https://dcachetest.grid.surfsara.nl:20443/api/v1/namespace/%2Ftape%2Ftest?locality=true&qos=true'
{
  "fileMimeType" : "application/octet-stream",
  "fileLocality" : "ONLINE_AND_NEARLINE",
  "currentQos" : "tape",
  "labels" : [ ],
  "size" : 10485760,
  "creationTime" : 1669736063762,
  "fileType" : "REGULAR",
  "pnfsId" : "0000EC9AEB2B04304A8D8E34F530B55198F5",
  "nlink" : 1,
  "mtime" : 1669736064395,
  "mode" : 384
} 


This was on our new test server. I tested this also on our old test server dolphin12, running a 9.0 master snapshot too. Same behaviour. 

I would expect the API call to succeed in changing the QoS, or else report a failure. 

Cheers, 
Onno

**Comment by alrossi** [comment]
I can confirm that if the QoS services are running, the change of currentQoS is indeed immediate.  Hence its interpretation is "this is the QoS status the file _should_ have (from now on...)".

I can also confirm that without the services, you do indeed get a "success" but `currentQos` remains unchanged.

So I will see about returning failure in that case.

Thanks for pointing this out.

Cheers, Al

**Comment by onnozweers** [comment]
Hi Al,

Thanks for pointing me to the QoS changes. I had somehow missed them and I will check the documentation and configure the required services. I had read https://www.dcache.org/old/downloads/1.9/release-notes-8.2.shtml but had overlooked the QoS changes mentioned there.

Indeed it would be nice to have some kind of error like "internal server error" in this case, and perhaps a log entry explaining what's wrong.

Cheers,
Onno

**Comment by alrossi** [comment]
This should fix it.

https://rb.dcache.org/r/13810/
