### ISSUE TITLE
Webdav:  add .well-known/security.txt

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6927]
(from @onnozweers )

Our security officer requests us to implement a /.well-known/security.txt file for each HTTP capable interface. If you’ve never heard of this, please check [https://securitytxt.org/](https://urldefense.proofpoint.com/v2/url?u=https-3A__securitytxt.org_&d=DwMGaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=60rQ0HHqHmEY1P6VSdyuTQ&m=DlF0PJJnVEjSaIYa2UwyIT5Hik90FnJNbp02_0BvBSK67HbIWwNAgsfO0c4izaxI&s=Dvg9qbWlHbbIiGWwDz6p2eDfg1cjlrrfVX6aoyNZKNA&e=).

To complicate things, the request is to make it a forward to our institute’s centrally managed file at [https://www.surf.nl/.well-known/security.txt](https://urldefense.proofpoint.com/v2/url?u=https-3A__www.surf.nl_.well-2Dknown_security.txt&d=DwMGaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=60rQ0HHqHmEY1P6VSdyuTQ&m=DlF0PJJnVEjSaIYa2UwyIT5Hik90FnJNbp02_0BvBSK67HbIWwNAgsfO0c4izaxI&s=lkpnLaHibHAaPRbk-rAypHHVWYVnMESS-QIBhuCF76Q&e=).

-------
This requires implementation of the `WellKnownProducerFactory` for security.txt

**Comment by onnozweers** [comment]
Same for Frontend, if possible ☺️

**Comment by alrossi** [comment]
As it is right now, all well-known endpoints are exposed through webdav:2880.  That is, there is no frontend:3880/.well-known.   We added .well-known largely because of the WLCG requirements:

https://docs.google.com/document/d/1Zx_H5dRkQRfju3xIYZ2WgjKoOvmLtsafP2pKGpHqcfY/edit#heading=h.ozszs1lr7q93

I am not sure how much additional work would be required to expose well-known on the frontend door/port.

**Comment by alrossi** [comment]
Would it be possible to do this through webdav:2880 with an additional slash?


```
webdav:2880/.well-known/webav/security.txt
webdav:2880/.well-known/frontend/security.txt
```
?

**Comment by onnozweers** [comment]
My understanding is that the path should be fixed, `/.well-known/security.txt`, otherwise external security experts would not be able to find it.

**Comment by alrossi** [comment]
OK I'll have to see what needs to be done there.

Onno, may I ask you how urgent this is, so I can get an idea of prioritizing.   We are heading into a break and I will be gone from 22/12/2022 to 08/01/2023.  Thanks!

**Comment by onnozweers** [comment]
It can wait until after that. There is no deadline mentioned. Happy holidays!

**Comment by alrossi** [comment]
Same to you!

**Comment by alrossi** [comment]
NOTE:  I should add that the forwarding is an added complication, as you predicted.   So this is going to take require a bit of work.   I will try to address this as soon as I can.

**Comment by onnozweers** [comment]
Hi Al, if the forwarding is too difficult, I'm sure we can set up a cron job that wgets the security.txt and writes it into one of the dCache directories.

**Comment by alrossi** [comment]
Thanks Onno, I'll update this issue as I get a sense of what would need to be done.

**Comment by alrossi** [comment]
Hi Onno,

Please to report:  https://rb.dcache.org/r/13832/

Easier than anticipated.   

The property to use can be set to either a local file or a redirect URL:

```
#
# URI for the well-known security.txt info.  If a schema + host is provided,
#     the browser will be redirected to that endpoint; otherwise, the path
#     is local and will the contents will be loaded from that file.
#     NB only an 'https' schema is accepted.
#
#     Examples:
#
#             https://example.org.2901/.well-known/security.txt  (redirect)
#             /usr/local/security/security.txt                   (local file)
#
dcache.wellknown!security-txt.uri=${dcache.paths.httpd}/security.txt
```

I now await the review of the patch.  I don't know if the team will approve of a back-port to 8.2 yet.

Cheers, Al

**Comment by alrossi** [comment]
Onno,

This will be back-ported to 8.2 with the next update.

Happy Holidays!

Al

**Comment by onnozweers** [comment]
Hi Al,

That's awesome! Thanks a lot!

Happy holidays!

Cheers,
Onno

**Comment by onnozweers** [comment]
It appears to work as expected. Tested on:

https://dcachetest.grid.surfsara.nl/.well-known/security.txt (WebDAV with basic auth)
https://dcachetest.grid.surfsara.nl:2884/.well-known/security.txt (WebDAV with X509 auth)
https://dcachetest.grid.surfsara.nl:20443/.well-known/security.txt (Frontend/API)

**Comment by alrossi** [comment]
👍
