### ISSUE TITLE
https mover doesn't reload host certificate, if updated

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#6929]
If the host certificate is updated on a pool node, then https mover doesn't reloads it automatically, thus requires pool restart. This is of course unexpected behavior and have to be fixed.

**Comment by ageorget** [comment]
Hi @kofemann,
Is this affecting all 8.2 releases?
I was on my way to update 50 host certificates on 8.2.7 pool nodes with encrypted-transfers enabled so I'm wondering if I have to restart all pools after that...
Cheers,
Adrien

**Comment by mksahakyan** [comment]
Hi @ageorget,
 this is a bug that is affecting 8.2 and lower version of dCcahe.
we are working tofix it asap.

cheers
Marina
