### ISSUE TITLE
undefined dcache.paths.bulk in paths.properties

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#6940]
Hey.

Commit 763e2dfbb439241db9e20e675885c7ec02811f69 (@alrossi) removed the substitution of `@dcache.paths.bulk@` leaving behind invalid:
```
dcache.paths.bulk=@dcache.paths.bulk@
```
entries in `paths.properties`.

Either too much was removed, or `dcache.paths.bulk` should have been dropped, too.

Cheers,
Chris.

**Comment by alrossi** [comment]
Sorry I never noticed this earlier ...

indeed, `dcache.paths.bulk` should be removed.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/13859/
