### ISSUE TITLE
silently dropped configuration options

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#6949]
Hey.

Between 8.1 and 8.2 a rather great many of options were dropped from (at least) `qos.properties` without marking them as `obsolete` or `deprecated` as this is usually (sometimes) done.

As suggested in numerous similar such reports during the last years, there should be some automatism that resolves all options from the default files, prints changed (default) values and also indicates gone options, so that they can be properly mentioned in the release notes (we had it quite often that defaults silently changed, sometimes even important ones) respectively properly added to the `.properties` files.<br>
And this should obviously be used on new versions (from major to major, and minor to minor).

Cheers,
Chris.

**Comment by calestyo** [comment]
There's e.g. also a silently changed default between 8.1 and 8.2 of `pool.authn.namespace-mode`.

**Comment by calestyo** [comment]
`bulk` also lost at least one (didn't check further) option, which wasn't marked as `deprecated`.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/13845/
