### ISSUE TITLE
API bulk requests: pinning directories with "expand_directories" : "ALL" doesn't work

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#6955]
Dear dCache devs,

This one is probably for @alrossi.

My colleague @natalieda may have found a bug. She is trying to stage a directory, using our test server with today's master snapshot of dCache. Her JSON request:

```
{
  "activity": "PIN", 
  "arguments": {"lifetime": "300", "expand_directories": "ALL"}, 
  "target": ["/users/anatolid/tape/natalie"]
}
```

The request is accepted (code 200), but when she looks at the status of the request with `GET /bulk-requests/...`:

```
{
  "nextSeqNo": -1,
  "id": "6fe4c046-011f-4842-9beb-e1cb3fc6bb07",
  "arrivedAt": 1674037489801,
  "startedAt": 1674037489811,
  "lastModified": 1674037489828,
  "status": "COMPLETED",
  "targets": [
    {
      "target": "/users/anatolid/tape/natalie",
      "state": "FAILED",
      "submittedAt": 1674037489822,
      "startedAt": 1674037489822,
      "finishedAt": 1674037489825,
      "errorType": "java.lang.Throwable",
      "errorMessage": "[errorType: diskCacheV111.util.CacheException] Not a regular file.",
      "seqNo": 14
    }
  ]
}
```

From the User Guide it seems that this should work (though the syntax there is slightly different). https://dcache.org/manuals/UserGuide-9.0/frontend.shtml#bulk-requests

Also `"expand_directories": "TARGETS"` fails with the same error.

Could this be a bug?

Kind regards,
Onno

**Comment by alrossi** [comment]
Hi Onno,

The problem lies in the attribute name.   Could you please try "expandDirectories" instead of "expand_directories"?  (I believe the example in the User Guide does indeed show this, but I apologize for the confusion.)

Please let me know if this fixes it.

Al

**Comment by alrossi** [comment]
Oh, wait.  I think I see the issue.  We do support camel, snake and humpback expressions of 'expand_directories'.  The problem is, it is not an argument, but a top-level attribute (arguments are specific to the given activity).  

Please try:

```
{
  "activity": "PIN", 
  "arguments": {"lifetime": "300"}, 
 "expand_directories": "ALL",
  "target": ["/users/anatolid/tape/natalie"]
}

```

That should work.

**Comment by onnozweers** [comment]
Hi Al,

We've tried that but it doesn't work either:

```
{
  "activity": "PIN", 
  "arguments": {"lifetime": "300"}, 
  "expand_directories": "ALL",
  "target": ["/users/anatolid/tape/natalie"]
}
```
Response body
```
{
  "detail": "Forbidden",
  "title": "Forbidden",
  "status": "403"
}
```
Response headers 
content-length: 57  content-type: application/json  date: Wed, 18 Jan 2023 16:15:26 GMT  server: dCache/9.0.0-SNAPSHOT

With my directory the same error.

In the log:

```
18 Jan 2023 17:22:15 (bulk) [Frontend-hedgehog14 BulkRequest] messageArrived(BulkRequestMessage) BulkRequestMessage for request null, target: [/users/anatolid/tape/natalie], activity: PIN: org.dcache.services.bulk.BulkPermissionDeniedException: full directory recursion not permitted.
19 Jan 2023 11:02:44 (bulk) [Frontend-hedgehog14 BulkRequest] messageArrived(BulkRequestMessage) BulkRequestMessage for request null, target: [/users/onno/tape/], activity: PIN: org.dcache.services.bulk.BulkPermissionDeniedException: full directory recursion not permitted.
```

**Comment by alrossi** [comment]
```
full directory recursion not permitted
```

indicates that you need to modify:

```
#  ---- Global setting for directory expansion.
#
#           NONE:       do not allow any processing of targets inside a directory (depth 0)
#           TARGETS:    allow only the immediate children of directories to be processed (depth 1)
#           ALL:        allow full recursive processing of directories (depth N)
#
(one-of?NONE|TARGETS|ALL)bulk.allowed-directory-expansion=TARGETS
```

to ``ALL``

This can be done as a property, but you can also do it without restarting using the admin command:

```
\s bulk request policy -maxAllowedDepth=ALL
```

I apologize if this info is kind of buried.  It does not appear in the User Guide because it is an admin issue.  The Book chapter on bulk does refer to the `request policy` command.

[](https://www.dcache.org/manuals/Book-8.2/config-bulk.shtml#admin-commands)

HTH,  Al

**Comment by alrossi** [comment]
https://www.dcache.org/manuals/Book-8.2/config-bulk.shtml#admin-commands

**Comment by onnozweers** [comment]
Hi Al,

Thanks, indeed I wasn't aware of this configuration item.

However, I'm afraid I still don't understand it. I see from the bulk.properties that it is set to the default, TARGET:

```
[root@hedgehog14 /etc/dcache]# grep allowed-directory-expansion dcache.conf layouts/hedgehog14.conf /usr/share/dcache/defaults/bulk.properties 
/usr/share/dcache/defaults/bulk.properties:(one-of?NONE|TARGETS|ALL)bulk.allowed-directory-expansion=TARGETS
```

So, my understanding is that files within the directory should be processed, but subdirectories shouldn't.

The directory only contains files:

```
[root@hedgehog14 /users]# ls -l anatolid/tape/natalie/
total 10485760
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:37 1GBfile1
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:41 1GBfile10
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:37 1GBfile2
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:34 1GBfile3
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:32 1GBfile4
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:41 1GBfile5
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:39 1GBfile6
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:39 1GBfile7
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:32 1GBfile8
-rw------- 1 anatolid anatolid 1073741824 Dec  7 11:34 1GBfile9
```

Why would that be refused?

Cheers,
Onno

**Comment by onnozweers** [comment]
Hi Al,

Thanks for explaining! I understand it now. It does makes sense. I think we'll just set `bulk.allowed-directory-expansion=ALL` to make things easy and hope the users behave.

Cheers,
Onno
