### ISSUE TITLE
Missing credentials error spam in SRM door log

### ISSUE THREAD

**Issue by mteroerd** [dCache/dcache#7003]
Dear experts, 
our SRM door keeps rapidly logging sending error messages such as 

08 Feb 2023 12:16:42 (SrmManager) [door:WebDAV-grid-se049 SrmRequestCredential] error reading the credentials from database: java.io.FileNotFoundException: /var/lib/dcache/credentials/-218079561 (No such file or directory)

It seems to be related to the WebDAV domain, running on a different machine. Such messages do not appear there.

We only have one srmmanager running, so it is probably not interference between two srmmanagers. The srm domain has the srm door, srmmanager, and transfermanagers running.

There does not seem to be a problem with transfering files however. This error message started showing up with dcache 7.2, however we are now at 8.2 and the error message is still getting spammed. 

Cheers,
Marius

**Comment by lemora** [comment]
Hi Marius.

Did you at some point have two SrmManagers in your dCache instance before removing all but one after observing the issues? Did they persist ever since?

Could you please check if the `/var/lib/dcache/credentials` directory is empty or if the particular credential is indeed missing. Does it exist in the database and is only absent from the directory?

Thanks and regards
Lea

**Comment by mteroerd** [comment]
Hi Lea,
Thank you for your quick response.

Yes, we used to have multiple SrmManagers running and removed them when we started seeing the error.
Indeed the /var/lib/dcache/credentials directory is not empty, but the credential is missing from there while present in the srmrequestcredentials database.

**Comment by mteroerd** [comment]
@lemora Would a possible solution be to clean the srmrequestcredentials database and let it rebuild or would this potentially create worse problems?

**Comment by DmitryLitvintsev** [comment]
Hi Marius, 

We have discussed this issue and today's meeting. Could you confirm that your site is functioning. That is this is just the noise in the log or you actually have massive failure on your hands? 

Lea's suggestion seems good to me - clean srmrequestcredentials we may provide instructions if this is the way to go.

**Comment by mteroerd** [comment]
Hi Dmitry,
indeed the transfers seem to be working fine despite the error spam (since they have persisted since over a year ago, we would have probably noticed by now). However since the logs of the srm door get spammed, it's hard to read anything in them.

**Comment by DmitryLitvintsev** [comment]
OK, this is good news. 
if you could connect to srm database using psql and do:

```
delete from srmrequestcredentials where delegatedcredentials = ' /var/lib/dcache/credentials/-218079561'
```

Or, also, you can check what is the expiration time of this credential:

```
select TIMESTAMP WITH TIME ZONE 'epoch' +(credentialexpiration/1000) * INTERVAL '1 second' from srmrequestcredentials where delegatedcredentials = '/var/lib/dcache/credentials/-218079561';
```

if it is in the past,  we can be a bit more adventurous and remove all expired credentials:

```
delete * from srmrequestcredentials where TIMESTAMP WITH TIME ZONE 'epoch' +(credentialexpiration/1000) * INTERVAL '1 second' < current_date;
```
WARNING : above query will remove all credentials expired before start of the day. May be before running that delete, determine how many are there:

```
select count(*) from srmrequestcredentials where TIMESTAMP WITH TIME ZONE 'epoch' +(credentialexpiration/1000) * INTERVAL '1 second' < current_date;
```
If there is just a few thousand of these - no big deal. If there are millions - it may take time to complete. 

expired entries definitely are not good for anything so it is safe to remove. If, on the other hand, expiration of that credential '/var/lib/dcache/credentials/-218079561' is in the future then just remove that one credential. 

Paul is correct marking this as enhancement request - dCache probably needs to remove these from DB if they are not present in namespace

Cheers, 
Dmitry

**Comment by mteroerd** [comment]
Hi Dmitry,
thank you for the instructions. I checked for the credentials that were expired and found about 2200.  Of these, the ones that produced errors seemed to all be timestamped before the upgrade to dcache 7.2, which is when we started getting the errors. I deleted the expired credentials and hope that this will stop the errors.

Cheers,
Marius

**Comment by mteroerd** [comment]
I can confirm that no further errors have occured since then (there used to be a large number of errors every <10 minutes).
