### ISSUE TITLE
RemoteTransferManager (RTM) questions

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#7005]
Dear all,

I would like to understand the command 

```
[dcadmin02] (RemoteTransferManager@srm-dcsrm03Domain) admin > help ls external
ls external [-l] [<#transferId>]

[dcadmin02] (RemoteTransferManager@srm-dcsrm03Domain) admin > help ls internal
ls internal [-l] [<#transferId>]
```
I would like to understand how the RTM classify the transfers, whether is an internal or external one? What it the criteria?

Thank you 

Carlos

**Comment by paulmillar** [comment]
OK, this is (unfortunately) rather twisted and confusing, so let me explain a little before answering your actual question.

There is a _service_ (the thing you put in a layout file) called `transfermanagers`.   This service handles two kind of data movement: dCache internal copies and transfers.  The default (cell) name for this service is `RemoteTransferService`, which can be a little misleading.

Internal copies are when dCache duplicates a file, creating  a new file with identical contents and using up more storage capacity.  This is similar to the `cp` command, but with `cp` the client reads and the file's data and writes it back again[*]; in contrast, an internal copy duplicates the file without sending the client that file's data.  There are few protocols that support internal copies.  SRM and NFS v4.2 do.  Theoretically, WebDAV would allow the client to initiate an internal copy but dCache's WebDAV door currently doesn't support this.

Transfers are when dCache copies the data from a remote location or copies it to a remote location.  In theory, using RTM for third-party transfers was useful as it allowed the door to be restarted without affecting the transfer.  In practice, no one was using srmCopy to do third-party copies (they used GridFTP instead), so this give no particular benefit.

Currently, the WebDAV door implements HTTP-TPC by making requests to RTM.

So, to answer your question explicitly: internal transfers are where dCache is creating a copy of a file, similar to the `cp` command but without streaming the file's contents to the client. External transfers are ones where the dCache is acting as a client and connecting to a remote server.

[*] the caveat here is that NFS v4.2 supports server-side copying of a file, so it is possible for `cp` to avoid streaming the file's data.

**Comment by cfgamboa** [comment]
Hi Lea, Paul

Thank you. Yes please close this ticket.

All the best,
Carlos
