### ISSUE TITLE
Unable to parse the boolean system property java.net.preferIPv6Addresses

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#7056]
Hello,

I can see this error in pool logs : 

```
Mar 14 10:49:30 ccdcacli372.in2p3.fr dcache@ccdcacli372-pool-atlas-aod-read-li372a-Domain[231548]: 14 Mar 2023 10:49:30 (pool-atlas-aod-read-li372a) [door:webdav-ccdcatli406@webdav-ccdcatli406Domain:AAX22STgtqA pool-atlas-xferout-li421a PoolDeliverFile 00002F115ABB283D498B9923BAC66BE16053] Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false

Mar 14 11:31:54 ccdcacli375.in2p3.fr dcache@ccdcacli375-pool-atlas-aod-read-li375a-Domain[208189]: 14 Mar 2023 11:31:54 (pool-atlas-aod-read-li375a) [door:xrootd-ccdcacli331@xrootd-ccdcacli331Domain:AAX22SVRM4A pool-atlas-xferout-li300a PoolDeliverFile 000030F68E97F959420B9677705203FE3083] Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
```
We are using the default value `-Djava.net.preferIPv6Addresses=system` for dcache.java.options.
with dCache 8.2.16.

Cheers,
Adrien

**Comment by alrossi** [comment]
It seems to me that the system property should have either true or false values

https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

'system' is not valid.

**Comment by ageorget** [comment]
That's the default value used by dCache since the 8.2 version https://github.com/dCache/dcache/commit/da994201f1e90191030a631c54241c8bbe240565

```
(not-for-services)dcache.java.options=\
    -server \
    -Xmx${dcache.java.memory.heap} \
    -XX:MaxDirectMemorySize=${dcache.java.memory.direct} \
    -Dsun.net.inetaddr.ttl=${dcache.net.inetaddr.lifetime} \
    -Dorg.globus.tcp.port.range=${dcache.net.wan.port.min},${dcache.net.wan.port.max} \
    -Dorg.dcache.dcap.port=${pool.mover.dcap.port} \
    -Dorg.dcache.ftp.log-aborted-transfers=${pool.mover.ftp.enable.log-aborted-transfers} \
    -Dorg.dcache.net.tcp.portrange=${dcache.net.lan.port.min}:${dcache.net.lan.port.max} \
    -Djava.security.krb5.realm=${dcache.authn.kerberos.realm} \
    -Djava.security.krb5.kdc=${dcache.authn.kerberos.key-distribution-center-list} \
    -Djavax.security.auth.useSubjectCredsOnly=false \
    -Djava.security.auth.login.config=${dcache.authn.jaas.config} \
    -Dcontent.types.user.table=${dcache.paths.content-types} \
    -Dzookeeper.sasl.client=false \
    -Dcurator-dont-log-connection-problems=true \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath=${dcache.java.oom.file} \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+StartAttachListener \
    -XX:+UseCompressedOops \
    -javaagent:${dcache.paths.classes}/aspectjweaver-1.9.2.jar \
    -Djava.net.preferIPv6Addresses=system \
    ${dcache.java.options.common} \
    ${dcache.java.options.extra}
```

**Comment by paulmillar** [comment]
`java.net.preferIPv6Addresses=system` is [supported in OpenJDK v11](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/doc-files/net-properties.html) (and newer), but [not in OpenJDK v8](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html).

If you see this message, I assume you are running JDK v8.

According to our download page, all supported dCache versions require JDK v11 (or newer).

If you're currently running JDK v8 then I suggest upgrading to JDK v11 and see if that helps.

**Comment by paulmillar** [comment]
It's not a great test, but could you try the following commands?

```console
paul@sprocket:~$ echo 'System.out.println("Hello, world");' | jshell -J-Djava.net.preferIPv6Addresses=false -
Hello, world
paul@sprocket:~$ echo 'System.out.println("Hello, world");' | jshell -J-Djava.net.preferIPv6Addresses=foo -
Hello, world
paul@sprocket:~$ echo 'System.out.println("Hello, world");' | jshell -J-Djava.net.preferIPv6Addresses=true -
Launching JShell execution engine threw: FailOverExecutionControlProvider: FAILED: 0:jdi:hostname(0:0:0:0:0:0:0:1) [...]
[...]
paul@sprocket:~$ echo 'System.out.println("Hello, world");' | jshell -J-Djava.net.preferIPv6Addresses=system -
Launching JShell execution engine threw: FailOverExecutionControlProvider: FAILED: 0:jdi:hostname(0:0:0:0:0:0:0:1) [...]
[...]
paul@sprocket:~$ 
```

The above example is with Java 11:
```console
paul@sprocket:~$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)
paul@sprocket:~$ 
```

As an explanation, there's a bug in jshell where it crashes if given an IPv6 address to work with.

If `preferIPv6Addresses` is `false` or an unknown value (like `foo` above) then jshell has an IPv4 address (127.0.0.1) and everything is fine.  If it is `true` then it has an IPv6 address (::1) and the bug is triggered.

If your JRE supports `preferIPv6Addresses=system` then you should see a crash (like my last example above).  It `system` is not supported then jshell should launch without a problem (as `system` is an unknown value, so treated as `false`).

**Comment by alrossi** [comment]
This is a problem with Netty not supporting the system​ value.

I opened a GH issue with them, seems they have corrected the problem:

https://github.com/netty/netty/issues/13300

we will have to update the Netty dependency.

Al
________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
WH 566
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________
