### ISSUE TITLE
build:  system-test build broken on macOS for 9.0

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#7078]
` mvn -X clean package -am -pl packages/system-test -DskipTests | tee mvn.txt` is attached.

Specifically:

```
[DEBUG] Executing command line: [/bin/sh, -c, bin/populate 2>&1]
sed: 1: "s:subject= *\+/\?:/:;s: ...": RE error: repetition-operator operand invalid
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

This is on OS 12.6, Java 11.

**Comment by alrossi** [comment]
[mvn.txt](https://github.com/dCache/dcache/files/11053554/mvn.txt)

**Comment by paulmillar** [comment]
Note that changing the RE to `sed 's:subject= */\?:/:;s:, :/:g'` seems to work.

**Comment by paulmillar** [comment]
My problem is that I don't have access to a Mac, so cannot test any proposed solution.

**Comment by alrossi** [comment]
This issue was solved.
