### ISSUE TITLE
Pool migration ignores rdonly status of target

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#7114]
Dear dCache devs,

I have a strong impression that the "migration move" function of a pool ignores the rdonly (read only) status of a target pool.

This is a bit impractical when you have two pools that you want to drain simultaneously with the poolgroup as a target. They keep on writing files to each other, so it's difficult to get them to a stage where they are empty and can be decommissioned.

So, what I do is set the source pools to rdonly, in the PoolManager:

psu set pool shark11_atlasdisk rdonly
psu set pool shark12_atlasdisk rdonly

Then I drain them both like this:

migration move -concurrency=6 -target=pgroup atlas_writediskpools

And then they are writing files to many pools, including each other. I wouldn't expect that, since they are rdonly. It's actually worse: because they are getting emptier, they are becoming increasingly attractive target pools for each other's migrations.

I work around this by setting the max diskspace to 10 (bytes) repeatedly, so that they don't have any available space to write into. But that's a bit clumsy.

Cheers,
Onno

**Comment by kofemann** [comment]
I would say: `works as expected`. But it looks like that too many admins run into this situation. So maybe we need to update psu to disable the pool unless an extra `--soft` option is specified.

**Comment by paulmillar** [comment]
Good catch. I missed that it was a pool-manager `psu set pool` command that was disabling the pool.

So, I agree with @kofemann .

Just to add my 2c-worth, another option might be to update pools so they have an extra state (or extra states) where the pool would be disabled for client-triggered requests (upload/download/stage), but would still allow sys-admin triggered requests.  This would have broadly the same effect as the current `psu set pool` command, but the pool would be the authoritative source of information (pool-manager could cache this info, but that would be only a cache).

That would be a bigger change, but (I think) would bring clarity to a somewhat confusing situation.

**Comment by onnozweers** [comment]
Thanks guys, I wasn't aware that the poolmanager rdonly was something different than the pool rdonly. Thanks for clearing that up. 

I like @kofemann's idea to have the poolmanager's `psu set pool shark11_atlasdisk rdonly` command update also the pool status (unless specified otherwise). For now I guess I can use the `pool disable -rdonly` as workaround.

**Comment by kofemann** [comment]
this issues looks like a good candidate to test github discussions :). So, I here am I. 😎
