### ISSUE TITLE
gplazma2-xacml depends on  unsupported org.opensciencegrid:privilege-xacml package

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#7151]
The [`privilege-xacml`][1] is not supported by OSG, thus there are no reasons why dCache should continue to provide this functinality and depend on outdated package.

[1]: https://github.com/opensciencegrid/privilege-xacml

**Comment by paulmillar** [comment]
This would mean dropping the `gplazma2-xacml` module, right?

**Comment by alrossi** [comment]
I would favor that as well.   Do we have anyone actually using this anymore?

**Comment by kofemann** [comment]
> Do we have anyone actually using this anymore

No Idea. This was something that OSG was using it. If you don't have it at FNAL, then nobody uses it.

**Comment by DmitryLitvintsev** [comment]
This can be dropped

**Comment by alrossi** [comment]
DropIt!
