### ISSUE TITLE
Save HSM dynamic load command to setup files

### ISSUE THREAD

**Issue by christianvoss** [dCache/dcache#7251]
Hi all,

with 9.1 dCache started to to support the dynamic loading of HSM modules from a given path if the HSM plugin supports it. We've tried it successfully with the CTA-driver, however, currently the command
```
hsm load provider /usr/local/share/dcache/dcache-cta-0.10.0
```
is not saved to the pool setup file. Thus, when restarting the pool the libraries are not available and the pool will go into a restart loop until the CTA hsm create command is removed from the setup file:
```
20 Jul 2023 10:38:48 (System) [] Failure at startup: (666) URL [file:/usr/share/dcache/services/pool.batch]: line 135: (3) Error at /dcache/dcache-dot8-05/setup:18: (1) No such nearline storage provider: dcache-cta
```
When adding the line to the setup file, the pools starts without problems. Still, saving any changes to the pool setup file will overwrite this line.  As result any pool restart can break dCache and would need a manual clean-up. Alternatively, the setup would have to be maintained specifically through e.g. Puppet or Ansible. Maybe this is a local issue, that we change a lot of pool options or that we require quite a set of different configuration for different pools in the instance.

Still it would nice, if the loading path was also saved into setup.

Thanks a lot,
Christian

**Comment by svemeyer** [comment]
This was added in 9.1.5
