### ISSUE TITLE
current OpenSSH can no longer connect to dCache's ssh

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#7273]
Hey.

OpenSSH since 8.8p1 no longer (per default) connects to RSA/SHA1 signed keys (unless `PubkeyAcceptedAlgorithms +ssh-rsa`).

dCache's ssh server seems to use that.

Regenerating the server and user ssh keys doesn't help - it's apparently the server code that needs to be updated (tested with 9.1.2).

Cheers,
Chris.

**Comment by calestyo** [comment]
btw: When dcache cannot read the server SSH private key (and presumably the same for the public), it prints a stack trace, instead of a nice error message ;-)

**Comment by calestyo** [comment]
The key type shouldn't matter there, as the change is about the signature algorithm,... but anyway it's RSA keys for both, server and client sides.

Maybe your built of `ssh` has changed upstream defaults? Or your `ssh_config` has?

If you do something like:
```
ssh -G admin@localhost | grep -i ^PubkeyAcceptedAlgorithms
```
you should see the actually used algo preference string, if that contains `ssh-rsa` at some point it will work, but not for any OpenSSH built with upstream defaults.

Cheers,
Chris.

**Comment by calestyo** [comment]
See also https://www.openssh.com/txt/release-8.8, and there the “Potentially-incompatible changes” section.

**Comment by kofemann** [comment]
```
 $ ssh -G ***@***.*** | grep -i ^PubkeyAcceptedAlgorithms
pubkeyacceptedalgorithms ecdsa-sha2-nistp256,
***@***.******@***.***,
***@***.***,ecdsa-sha2-nistp384,
***@***.***,ecdsa-sha2-nistp521,
***@***.***,ssh-ed25519,
***@***.******@***.***,
***@***.***,rsa-sha2-256,
***@***.***,rsa-sha2-512,
***@***.***
```

-kofemann
/** caffeinated mutations of the core personality */

**Comment by calestyo** [comment]
That output looks unusual... mine looks like.
```
# ssh -p 59999 -G admin@localhost | grep -i ^PubkeyAcceptedAlgorithms
pubkeyacceptedalgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com
```


Anyway... meanwhile I tried with an `ed25519` **server** key... there the admin domain fails to start with some error. With `ecdsa` it starts, but same as with `rsa` key, I need to specify `-o PubkeyAcceptedAlgorithms=+ssh-rsa` or the connection fails.


It **does** however work, if I also replace the **client** key with an `ecdsa` one.

So I guess you need to try with all RSA keys and will then see the failure.

**Comment by samuraiii** [comment]
Hi,
the problem has a several causes "working" together to make it hard (at least on AlmaLinux9 and likes):
The rsa keys are considered obsolete so you need to allow them explicitly:
on cli:
`ssh -p 22224 -l admin localhost -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa`
or in config (~/.ssh/config):
```
Host loclahost
  HostName localhost
  PubkeyAcceptedKeyTypes +ssh-rsa
  HostKeyAlgorithms +ssh-rsa
```

Next you need to explicitly allow usage of SHA1 in libcyrpto
`/usr/bin/update-crypto-policies --set DEFAULT:SHA1`

And then you are good to go.
But all this point to need to update dcache supported keys to something more modern like `ecdsa-*` or better `ssh-ed25519`
Cheers 
S
