### ISSUE TITLE
404 link in The Book

### ISSUE THREAD

**Issue by samuraiii** [dCache/dcache#7307]
Hi,
the line 181 of The Book/config-nfs contains the link which is 404 on the other side:
https://github.com/dCache/dcache/blob/4071315e362e093d0b1b44721587bd34480a886c/docs/TheBook/src/main/markdown/config-nfs.md?plain=1#L181

Original link target is 
`https://docs.oracle.com/cd/E19253-01/816-4555/epubp/index.shtml`

I guess that the new target should be probably
`https://docs.oracle.com/en/operating-systems/solaris/oracle-solaris/11.4/manage-nfs/nfsmapid-and-dns-txt-records.html`

Cheers
AM

**Comment by kofemann** [comment]
Thanks!
