### ISSUE TITLE
dCache not sending back checksum values

### ISSUE THREAD

**Issue by murrayc3** [dCache/dcache#7467]
This GitHub issue is effectively a copy of the following dCache RT ticket: 

* https://rt.dcache.org/Ticket/Display.html?id=10510

I am creating this "copy" for three reasons.  Firstly the issue appears to be a development one, secondly access to GitHub is easier than access to https://rt.dcache.org (I cannot log in) and finally the FTS service would like to have a URL link from the following "about to be closed" FTS ticket to a "dCache" ticket:

* [INC3703873 ADLER32 checksum too quick?](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3703873)

When FTS asks dCache for the checksum of a successfully transferred file using the HTTP protocol,  dCache returns with a 200 everything is OK reply but the reply does not contain a checksum.  dCache experts believe that there is a race between the client, pool and door.

**Comment by kofemann** [comment]
We didn't have a full solution yet a workaround is under testing

https://rb.dcache.org/r/14182/
