### ISSUE TITLE
Overwrite doesn't work with xroot protocol and POSC

### ISSUE THREAD

**Issue by vokac** [dCache/dcache#7469]
Overwriting existing file during upload on dCache 9.2.6 (also 9.2.7, ) doesn't work with enabled POSC, e.g.
* successful upload of new file
```
[lxplus966]~% xrdcopy --version
v5.6.3

[lxplus966]~% xrdfs root://se1.farm.particle.cz:1094 stat /atlas/atlasscratchdisk/SAM/test
[ERROR] Server responded with an error: [3011] No such file

[lxplus966]~% xrdcopy -P -f /etc/services root://se1.farm.particle.cz:1094//atlas/atlasscratchdisk/SAM/test
[676kB/676kB][100%][==================================================][676kB/s]  
```
* overwriting existing file doesn't fail but file is not in the dCache
```
[lxplus966]~% xrdfs root://se1.farm.particle.cz:1094 stat /atlas/atlasscratchdisk/SAM/test                 
Path:   /atlas/atlasscratchdisk/SAM/test
Id:     0
Size:   692252
MTime:  2023-12-17 14:51:34
Flags:  48 (IsReadable|IsWritable)

[lxplus966]~% xrdcopy -P -f /etc/services root://se1.farm.particle.cz:1094//atlas/atlasscratchdisk/SAM/test
[676kB/676kB][100%][==================================================][676kB/s]  

[lxplus966]~% xrdfs root://se1.farm.particle.cz:1094 stat /atlas/atlasscratchdisk/SAM/test                 
[ERROR] Server responded with an error: [3011] No such file
```
It seems to me that xrd client with `XRD_LOGLEVEL=Dump` shows exactly same output except in the first example `kXR_stat` returns `kXR_error` while during second `xrdcopy` attempt when overwriting exiting file `kXR_stat` returns `kXR_ok`.

It seems that dCache 8.2.38 is not able to write files at all with POSC enabled
```
$ xrdcopy -P -f /etc/services root://dcache.farm.particle.cz:1094//atlas/test
[654.6kB/654.6kB][100%][==================================================][654.6kB/s]  
Run: [ERROR] Server responded with an error: [3012] directory is not empty (destination)

$ xrdcopy -f /etc/services root://dcache.farm.particle.cz:1094//atlas/test
[654.6kB/654.6kB][100%][==================================================][654.6kB/s]  
```
It is not clear to me why we did not observe this issue earlier, because gfal-copy by default use POSC (may be we are just lucky and our tools don't really use `xroot` protocol for file uploads)

**Comment by DmitryLitvintsev** [comment]
Hi Petr, 

This looks nasty - pseudo-successful copy and then nothing left to show for it. A recipe for losing data. Interestingly this issue sounds vaguely familiar (like "haven't we fixed it already once"). I will investigate. 

Dmitry

**Comment by DmitryLitvintsev** [comment]
OK, This is what I have:

in 8.2 (Fermilab production):

$ gfal-copy   foo.root root://fndcadoor/pnfs/fnal.gov/usr/test/litvinse/replica_online/foo.root
Copying file:///home/litvinse/foo.root   [DONE]  after 9s                                                                                                                               

$ gfal-copy -f   foo.root root://fndcadoor/pnfs/fnal.gov/usr/test/litvinse/replica_online/foo.root
Copying file:///home/litvinse/foo.root   [DONE]  after 9s                                                                                                                               

$ gfal-ls  root://fndcadoor/pnfs/fnal.gov/usr/test/litvinse/replica_online/foo.root
root://fndcadoor/pnfs/fnal.gov/usr/test/litvinse/replica_online/foo.root



(as you said gfal-copy yes POSC by default). 

In 9.2:

$ gfal-copy  foo.root root://cmsdcatapeitb01/WAX/11/store/user/litvinse/foo_xroot.root
Copying file:///home/litvinse/foo.root   [DONE]  after 7s                                                                                                                                                         

$ gfal-ls  root://cmsdcatapeitb01/WAX/11/store/user/litvinse/foo_xroot.root
root://cmsdcatapeitb01/WAX/11/store/user/litvinse/foo_xroot.root

$ gfal-copy -f  foo.root root://cmsdcatapeitb01/WAX/11/store/user/litvinse/foo_xroot.root
Copying file:///home/litvinse/foo.root   [DONE]  after 7s                                                                                                                                                         

$ gfal-ls  root://cmsdcatapeitb01/WAX/11/store/user/litvinse/foo_xroot.root
gfal-ls error: 2 (No such file or directory) - Failed to stat file (No such file or directory)
$ 

So my experience with 8.2 version running at FNAL is that it works properly and 9.2 fails. "Houston, we have a problem"

**Comment by DmitryLitvintsev** [comment]
I have run git bisect and offending commit is this one:

```
$ git bisect bad 
2fb9170283908f911bb7ae462e2ceafd77b25c01 is the first bad commit
commit 2fb9170283908f911bb7ae462e2ceafd77b25c01
Author: Paul Millar <paul.millar@desy.de>
Date:   Wed Aug 30 13:29:38 2023 +0200

    chimera: update FsSqlDriver#inodeOf to throw exception if file not found
    
    Motivation:
    
    Currently, `FsSqlDriver#inodeOf` returns `null` if the target directory
    element does not exist.
    
    Returning a `null` value is inherently dangerous operation, so this
    operation is undesirable.
    
    Moreover, in many places in the code, the return value is checked for
    the `null` value and, if present, the code throws a corresponding
    `FileNotFoundChimeraException`.  This is not DRY.
    
    Modification:
    
    Update `FsSqlDriver#inodeOf` so it now never returns a `null` value.
    Instead, the method will throw FileNotFoundException if the target does
    not exist.
    
    Remove redundant code that checked for a `null` value and throws a
    `FileNotFoundChimeraException`.
    
    Update a few places where a special value (either `null` or an empty
    collection) is returned so they continue to support returning this
    value.
    
    Result:
    
    No user or admin observable changes.
    
    The code base is (hopefully) simpler and easier to maintain.
    
    Target: master
    Requires-notes: no
    Requires-book: no
    Acked-by: Tigran Mkrtchyan
    Patch: https://rb.dcache.org/r/14033/

:040000 040000 96c49ea842fb684cf56ec507f5b11b616134ae4a ccb50b6b07447f39c18eb0f577b3f9a7d6c2f95f M	modules
```

**Comment by DmitryLitvintsev** [comment]
https://rb.dcache.org/r/14187 

(just reverts the match that caused issue)
