### ISSUE TITLE
File mode depends on access method

### ISSUE THREAD

**Issue by XMol** [dCache/dcache#7494]
Hello dCache.org,

@ArturAkh found out something quite confusing:
```
$ gfal-stat root://cmsxrootd-kit-disk.gridka.de:1094//store/user/aakhmets/blub/mt/DoubleMuon_Run2018A-UL2018_0.root | grep Uid
Access: (0400/-r--------)	Uid: 12126	Gid: 1200	

$ gfal-stat davs://cmswebdav-kit-disk.gridka.de:2880/pnfs/gridka.de/cms/disk-only/store/user/aakhmets/blub/mt/DoubleMuon_Run2018A-UL2018_0.root | grep Uid
Access: (0777/-rwxrwxrwx)	Uid: 0	Gid: 0	

$ voms-proxy-init (...) # creating voms proxy with different primary role

$ xrdfs root://cmsxrootd-kit-disk.gridka.de:1094 ls /store/user/aakhmets/blub/mt/DoubleMuon_Run2018A-UL2018_0.root -l
-rw- 2023-01-13 16:52:00   180796892 /store/user/aakhmets/blub/mt/DoubleMuon_Run2018A-UL2018_0.root
```
The owner, group and mode for a specific file returned to him seemingly depends on the protocol (i.e. the dCache door) and the effective uid/gid for dCache. On top of that, neither matches the file mode stored in the database.
```
$ admin_cell_command.sh PnfsManager metadataof /pnfs/gridka.de/cms/disk-only/store/user/aakhmets/blub/mt/DoubleMuon_Run2018A-UL2018_0.root
-rw-r--r--;32001;5600[c=2023-01-13T17:51:59+01:00;m=2023-01-13T17:52:00+01:00;a=2023-01-13T17:51:59+01:00]
```
Is this by design?

Thank you for your time,  
Xavier.

/cc @samuambroj

**Comment by DmitryLitvintsev** [comment]
Hi Xavier, 

This is not by design. I think it is a valid request to have output of ls to be harmonized across protocols. 

Dmitry

**Comment by paulmillar** [comment]
The situation here is actually rather complicated.

Different network protocols allow dCache to provide different subsets of the POSIX permissions and ownership model.  Faced with these problems, gfal does its best to map the protocol-provided information to corresponding POSIX model on the client-side.  In some cases, it has no choice but to "make up" the missing information.  From memory, WebDAV is particularly bad in this respect.

Given the client must make up some of the missing information, it's not a complete surprise that different clients implement different algorithms for "making up" the missing information: you see inconsistent results.

Of course, all this should be documented in dCache's Users Guide, as it isn't obvious and people will quite naturally wonder what is going on, here.

As an exercise, it would be a good idea to check that dCache is providing accurate information through the door; however, I don't believe there is any problem with dCache.  Rather, I suspect you are simply hitting the limits of what information dCache can provide over the various network protocols it supports.

You can open tickets against the various clients, asking that they provide consistent information back to the user.  If they have to "make up" information, they should do so in a consistent fashion.

Similarly, you could open tickets against the people supporting the network protocols, asking them to allow servers to describe their POSIX permissions more accurately.  As the network protocols improve, dCache could then be updated to provide more information and the user would see more accurate information.

**Comment by XMol** [comment]
Hi @DmitryLitvintsev, @paulmillar,

thanks for the confirmation and explanation. We internally also realized that POSIX is just one way to convey the information.

I doubt I'd be able to bring all parties together and sort this out. So hopefully I'll remember this when I or somebody else stumbles over it again in the future. 🙂 

Ciao,  
Xavier.
