### ISSUE TITLE
Run: [ERROR] Server responded with an error: [3012] Internal timeout (source)

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#7525]
Hello,

Transfers from 2/16 doors are failed with Run: [ERROR] Server responded with an error: [3012] Internal timeout (source) at client side.

See the example for one of the doors

```
[cgamboa@spool1579 ~]$ xrdcp -f 

root://dcdoor33.usatlas.bnl.gov:1094/pnfs/usatlas.bnl.gov/LOCALGROUPDISK/rucio/user/xiaoning/51/01/user.xiaoning.34252511._000054.myFlow.root /dev/null
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3012] Internal timeout (source)
```

billing shows the following error

```
../03/billing-2024.03.01:03.01 18:02:40 [door:Xrootd3-dcdoor33-internal@xrootd3-dcdoor33Domain:request] ["/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cgamboa/CN=658196/CN=Carlos Fernando Gamboa":9102:31152:130.199.150.98] [0000F4474EB10D7D46FBBA7A7706365E0BA8,10683900609] [/pnfs/usatlas.bnl.gov/LOCALGROUPDISK/rucio/user/xiaoning/51/01/user.xiaoning.34252511._000054.myFlow.root] GROUPDISK:LOCAL@osm 27 0 {10006:"Failed to deliver PoolDeliverFileMessage message <1017774433449823202:-4676193657072406478> to [>dc255_12@dc255twelveDomain]: Route for >dc255_12@dc255twelveDomain< not found at >dccore02CoreDomain<"}
```

The file can be retrieved from any of the other 14 doors. The file is available at the pool.

Restarting the pool permitted get the file via the two doors.

[cgamboa@spool1579 ~]$ xrdcp -f root://dcdoor33.usatlas.bnl.gov:1094/pnfs/usatlas.bnl.gov/LOCALGROUPDISK/rucio/user/xiaoning/d1/64/user.xiaoning.36723086._000023.myFlow.root /dev/null

dCache is running on 9.2.6

All the best,
Carlos

**Comment by lemora** [comment]
Hi Carlos,

although there is little information here, the `Route for >dc255_12@dc255twelveDomain< not found at >dccore02CoreDomain<"` points to a broken tunnel between the core domain and pool that is not reestablished until restarting the pool.

This is potentially fixed by 48e5cafb6830c70cb0fadeb937ea0c5b981abb59, which is included in 9.2.14.

Kind regards
Le

**Comment by cfgamboa** [comment]
Hi Lea,

The state persisted until the pools was restarted. In order words, transfers requested by the same two doors experience the Route for >dc255_12@dc255twelveDomain< not found at >dccore02CoreDomain<. This started to be observed on 9.2.6

All the best,
Carlos

**Comment by kofemann** [comment]
@cfgamboa as Lea has mentioned, the reconnect issued is hopefully addressed in 9.2.14.

Can you tell us the java and os versions?

**Comment by cfgamboa** [comment]
Hello,

Thank you. 

Doors/cores 

cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.8 (Ootpa)

***@***.*** ~]# java -version
openjdk version "11.0.20" 2023-07-18 LTS



The pools 

***@***.*** ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.9 (Maipo)

***@***.*** ~]# java -version
openjdk version "11.0.20" 2023-07-18 LTS


All the best,
Carlos

**Comment by cfgamboa** [comment]
Could you please confirm which component is affected, does the entire system needs to be updated to 9.2.14?

All the best,
Carlos

**Comment by kofemann** [comment]
our current assumption is that newer OSes report a different error, which breaks dCache. So, probably it's sufficient to update only doors. But we are not 100% sure. This is still under investigation (#7519).

**Comment by kofemann** [comment]
As it takes longer than expected, I suggest you update all dcache services to 9.2.14 or newer.

**Comment by cfgamboa** [comment]
Thank you for your feedback and suggestion.

Upon feasibility we will proceed accordingly.

All the best,
Carlos
