### ISSUE TITLE
xrootd door in proxy mode optional encryption door to pool

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#7574]
Dear all,

Currently, WebDAV doors are implemented with a configuration flag property to enforce encryption between the door and the pool for read and write transfers. The encryption is done between the client and the door, but it is optional for the door and the pool when the WebDAV door is enabled in proxy mode.

I do not think this property or flag is implemented for XRootD door.

Could you please advise?

All the best, Carlos

**Comment by DmitryLitvintsev** [comment]
From doc (https://www.dcache.org/manuals/Book-9.2/config-xrootd.shtml#proxying-transfers-through-the-door):

```
If the door uses proxying, then when an open request arrives, a proxy instance will be launched on a new port and the client redirected to it as if it were the pool endpoint. The proxy serves as both façade and client to the pool by intercepting requests from the initiating client and passing them on to the pool transfer service, and similarly relaying responses from the pool back to the client. The connections between client and proxy on the one hand and proxy and pool on the other are independently established (this is necessary to support TLS, should that be requested or required), but after login is complete, all subsequent requests and replies are passed through the proxy without further interpretation.
```

My ubderstanding of this is the following - if TLS is enabled it is TLS all the way through. And there is no way to turn it off for door / pool communication. 

What is your concern? Why do you want this disabled?

**Comment by cfgamboa** [comment]
An optional configuration set might reduce resources (i.e cpu) if  the pool and door are located in the same LAN. 
I am just trying to understand if this can be done, we have it enabled for webdav.

**Comment by DmitryLitvintsev** [comment]
_might_ or you are actually impacted?

**Comment by cfgamboa** [comment]
xroots was not enabled due to issue reported in [www.dcache.org #10562]

**Comment by DmitryLitvintsev** [comment]
So, since issue RT issue #10562 is closed, this is not here the issue as well?
\
