### ISSUE TITLE
Request: log when staging not allowed in partition

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#7622]
Dear dCache devs,

On our new test server, we couldn't stage. Stage requests were stuck in `PINNING` state, and it wasn't clear why. Today I found out: in the partition manager, `-stage-allowed` was set to `no`. This is the default value. But it was hard to find, even with the log level in the PinManager and the PoolManager to DEBUG. The logs said that two eligible pools are found, and then... nothing. No clue why the stage requests are not being picked up. It took me many hours to figure this out and in the end it was more luck than wisdom.

This was logged:
```
...
18 Jul 2024 16:36:44 (PinManager) [bulk PinManagerPin] Pool: hedgehog14_genericstage  (enabled=true;active=37;rdOnly=false;links=0;pgroups=1;hsm=[osm];mode=enabled) can read from tape? : true
18 Jul 2024 16:36:44 (PinManager) [bulk PinManagerPin] Pool: hedgehog14_generictape  (enabled=true;active=38;rdOnly=false;links=0;pgroups=1;hsm=[osm];mode=enabled) can read from tape? : true
18 Jul 2024 16:36:44 (PinManager) [bulk PinManagerPin] match done: [0] : hedgehog14_genericstage hedgehog14_generictape 
```
And after that no clues why none of these pools were used.

So, my request is, that if staging is not allowed by the partition manager, a clear explanation is logged, at least at debug level.

Cheers,
Onno

**Comment by kofemann** [comment]
Hi Onno,

Thanks for the issue. We will change the logging to reflect the situation. Moreover, enabling staging by default makes sense, too. If HSM is configured, it is probably intended to be used, isn't it?

**Comment by onnozweers** [comment]
Thanks, much appreciated! I wasn't sure if there were any reasons for this default that I missed. But indeed, if you have configured a tape backend you're probably going to use it.
